// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppointmentTbl = "appointment_tbl"

// AppointmentTbl mapped from table <appointment_tbl>
type AppointmentTbl struct {
	Openid      string `gorm:"column:openid" json:"openid"`
	Lockid      string `gorm:"column:lockid" json:"lockid"`
	ReserveTime string `gorm:"column:reserveTime" json:"reserveTime"`
	Status      string `gorm:"column:status" json:"status"`
	PlateNum    string `gorm:"column:plate_num" json:"plate_num"`
	PalteColor  string `gorm:"column:palte_color" json:"palte_color"`
}

// TableName AppointmentTbl's table name
func (*AppointmentTbl) TableName() string {
	return TableNameAppointmentTbl
}
