// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameChargingPriceTbl = "charging_price_tbl"

// ChargingPriceTbl 二轮车--电价
type ChargingPriceTbl struct {
	ID       int32           `gorm:"column:id;primaryKey;autoIncrement:true;comment:电价id" json:"id"` // 电价id
	Total    decimal.Decimal `gorm:"column:total;not null;comment:单价" json:"total"`                  // 单价
	Name     string          `gorm:"column:name;comment:电价名称" json:"name"`                           // 电价名称
	MinPower float64         `gorm:"column:min_power;comment:最小功率" json:"min_power"`                 // 最小功率
	MaxPower float64         `gorm:"column:max_power;comment:最大功率" json:"max_power"`                 // 最大功率
	Service  decimal.Decimal `gorm:"column:service;comment:服务费" json:"service"`                      // 服务费
}

// TableName ChargingPriceTbl's table name
func (*ChargingPriceTbl) TableName() string {
	return TableNameChargingPriceTbl
}
