// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChargingStationManagementTbl = "charging_station_management_tbl"

// ChargingStationManagementTbl 充电站管理表(管理人员注册表)
type ChargingStationManagementTbl struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`               // 主键id
	Openid     string    `gorm:"column:openid;comment:微信用户唯一openid" json:"openid"`                             // 微信用户唯一openid
	Name       string    `gorm:"column:name;comment:名称" json:"name"`                                           // 名称
	Place      string    `gorm:"column:place;comment:地址" json:"place"`                                         // 地址
	ParkingNum int32     `gorm:"column:parking_num;comment:车位数" json:"parking_num"`                            // 车位数
	ProductID  string    `gorm:"column:product_id;comment:产品id" json:"product_id"`                             // 产品id
	Phone      string    `gorm:"column:phone;comment:手机号" json:"phone"`                                        // 手机号
	Email      string    `gorm:"column:email;comment:邮箱" json:"email"`                                         // 邮箱
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"` // 添加时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_time"` // 修改时间
	Reviser    string    `gorm:"column:reviser;comment:修改人" json:"reviser"`                                    // 修改人
}

// TableName ChargingStationManagementTbl's table name
func (*ChargingStationManagementTbl) TableName() string {
	return TableNameChargingStationManagementTbl
}
