// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHotSearchItemTbl = "hot_search_item_tbl"

// HotSearchItemTbl mapped from table <hot_search_item_tbl>
type HotSearchItemTbl struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                          // 主键id
	PlatformID int32     `gorm:"column:platform_id;not null;comment:所属平台id" json:"platform_id"`                           // 所属平台id
	HotRank    int32     `gorm:"column:hot_rank;not null;comment:热搜排名" json:"hot_rank"`                                   // 热搜排名
	Title      string    `gorm:"column:title;not null;comment:热搜标题" json:"title"`                                         // 热搜标题
	URL        string    `gorm:"column:url;comment:热搜链接" json:"url"`                                                      // 热搜链接
	HotValue   string    `gorm:"column:hot_value;comment:热度值" json:"hot_value"`                                           // 热度值
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"update_time"` // 数据更新时间
}

// TableName HotSearchItemTbl's table name
func (*HotSearchItemTbl) TableName() string {
	return TableNameHotSearchItemTbl
}
