// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHotelTbl = "hotel_tbl"

// HotelTbl 酒店注册信息表
type HotelTbl struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`      // 主键
	Openid        string    `gorm:"column:openid;not null;comment:用户唯一标识符" json:"openid"`              // 用户唯一标识符
	HotelName     string    `gorm:"column:hotel_name;comment:酒店名称" json:"hotel_name"`                  // 酒店名称
	HotelAddress  string    `gorm:"column:hotel_address;comment:酒店地址" json:"hotel_address"`            // 酒店地址
	ParkingNumber int32     `gorm:"column:parking_number;comment:车位数量" json:"parking_number"`          // 车位数量
	Phone         string    `gorm:"column:phone;comment:手机号" json:"phone"`                             // 手机号
	Email         string    `gorm:"column:email;comment:邮箱" json:"email"`                              // 邮箱
	HotelTime     string    `gorm:"column:hotel_time;comment:营业时间" json:"hotel_time"`                  // 营业时间
	HotelImgID    int32     `gorm:"column:hotel_img_id;comment:酒店照片--在image表中的id" json:"hotel_img_id"` // 酒店照片--在image表中的id
	Review        int32     `gorm:"column:review;not null;comment:审核状态" json:"review"`                 // 审核状态
	CreatTime     time.Time `gorm:"column:creat_time;comment:创建时间" json:"creat_time"`                  // 创建时间
}

// TableName HotelTbl's table name
func (*HotelTbl) TableName() string {
	return TableNameHotelTbl
}
