// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocalchepaiTbl = "localchepai_tbl"

// LocalchepaiTbl mapped from table <localchepai_tbl>
type LocalchepaiTbl struct {
	PlateNum   string `gorm:"column:plate_num" json:"plate_num"`
	PlateColor string `gorm:"column:plate_color" json:"plate_color"`
}

// TableName LocalchepaiTbl's table name
func (*LocalchepaiTbl) TableName() string {
	return TableNameLocalchepaiTbl
}
