// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageTbl = "message_tbl"

// MessageTbl 未使用
type MessageTbl struct {
	Ownerid    string    `gorm:"column:ownerid;comment:业主id" json:"ownerid"`                                            // 业主id
	Message    string    `gorm:"column:message;comment:消息内容" json:"message"`                                            // 消息内容
	Msgtime    string    `gorm:"column:msgtime;comment:消息生成时间" json:"msgtime"`                                          // 消息生成时间
	Status     string    `gorm:"column:status;comment:用户读取状态" json:"status"`                                            // 用户读取状态
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:消息id" json:"id"`                        // 消息id
	IsDelete   int32     `gorm:"column:isDelete;not null;comment:逻辑删除" json:"isDelete"`                                 // 逻辑删除
	CreateTime time.Time `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"createTime"` // 记录创建时间
	UpdateTime time.Time `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"`   // 更新时间
}

// TableName MessageTbl's table name
func (*MessageTbl) TableName() string {
	return TableNameMessageTbl
}
