package model

import "gorm.io/gorm"

// AllModels 返回所有需要 AutoMigrate 的持久化对象（一张表对应一个结构体）。
// 新增 gorm 模型时请同步追加到此列表。
func AllModels() []interface{} {
	return []interface{}{
		&AccountPrivateTbl{},
		&AccountPublicTbl{},
		&AppointmentTbl{},
		&ChargeMessageTbl{},
		&ChargeOrderTbl{},
		&ChargeTbl{},
		&ChargingPriceTbl{},
		&ChargingStateTbl{},
		&ChargingStationManagementTbl{},
		&ChargingStationTbl{},
		&CommunityApplyTbl{},
		&ConfigTbl{},
		&DeviceDataTbl{},
		&DriveruseTbl{},
		&ExternalAPIApp{},
		&FaultTbl{},
		&FreeChargingUsersTbl{},
		&HotSearchItemTbl{},
		&HotelProductTbl{},
		&HotelStaffTbl{},
		&HotelTbl{},
		&ImeiTab{},
		&Invoice{},
		&InvoiceTitle{},
		&LedMacTbl{},
		&LedTbl{},
		&LocalchepaiTbl{},
		&LockTbl{},
		&LockUseTbl{},
		&MessageTbl{},
		&NeighborShareUserTbl{},
		&OmEmployee{},
		&OnlineLockstatus{},
		&OpenLockTbl{},
		&OrderPrivateTbl{},
		&OrderTbl{},
		&OrderTwiceTbl{},
		&OwnerTbl{},
		&PackageRecordTbl{},
		&PlaceTbl{},
		&PlaceapplyTbl{},
		&PlatformTbl{},
		&PointTbl{},
		&PrivateChargingPriceTbl{},
		&PrivateChargingTbl{},
		&PrivatePlaceTbl{},
		&PurchasePoleApplicationTbl{},
		&ReOrderElectronicTbl{},
		&ReceptaclePowerTbl{},
		&ReceptacleTbl{},
		&RechargeOrderTbl{},
		&RechargeOrderTblSorted{},
		&SaveyytimeTbl{},
		&ShopStaffTbl{},
		&ShopTbl{},
		&StaffTbl{},
		&SystemTbl{},
		&TabBalanceRecord{},
		&TabChargingGun{},
		&TabGateway{},
		&TabImage{},
		&TabOrderElectronic{},
		&TabParkingSpace{},
		&TabPrice{},
		&TabPriceTime{},
		&TabPriceTimeSpring{},
		&TabPriceTimeSummer{},
		&TabPriceTimeWinter{},
		&TabProduct{},
		&TabProfitSharingConfig{},
		&TabVideo{},
		&TabVideoWatchRecord{},
		&UserBankCardTbl{},
		&UserBluetoothBindingsTbl{},
		&UserShopTbl{},
		&UserTbl{},
		&UsercarTbl{},
		&UsermessageTbl{},
		&VersionTbl{},
		&WangguanTbl{},
		&WithdrawalRecordTbl{},
		&ZbbArea{},
	}
}

// Migrate 对给定 *gorm.DB 执行 AutoMigrate，创建/更新所有业务表（增量式，不改动既有列）。
func Migrate(db *gorm.DB) error {
	return db.Set("gorm:table_options", "ENGINE=InnoDB ROW_FORMAT=DYNAMIC").AutoMigrate(AllModels()...)
}
