// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOwnerTbl = "owner_tbl"

// OwnerTbl mapped from table <owner_tbl>
type OwnerTbl struct {
	Ownerid   string `gorm:"column:ownerid;primaryKey;comment:业主唯一标识" json:"ownerid"` // 业主唯一标识
	NickName  string `gorm:"column:nickName;comment:用户微信昵称" json:"nickName"`          // 用户微信昵称
	Gender    string `gorm:"column:gender;comment:性别" json:"gender"`                  // 性别
	AvatarURL string `gorm:"column:avatarUrl;comment:头像地址" json:"avatarUrl"`          // 头像地址
	Province  string `gorm:"column:province;comment:所在省" json:"province"`             // 所在省
	City      string `gorm:"column:city;comment:所在市" json:"city"`                     // 所在市
	Phone     string `gorm:"column:phone;comment:业主手机号" json:"phone"`                 // 业主手机号
	WxNumber  string `gorm:"column:wxNumber;comment:业主微信号" json:"wxNumber"`           // 业主微信号
	Email     string `gorm:"column:email;comment:邮箱" json:"email"`                    // 邮箱
	Account   string `gorm:"column:account;comment:支付账户" json:"account"`              // 支付账户
}

// TableName OwnerTbl's table name
func (*OwnerTbl) TableName() string {
	return TableNameOwnerTbl
}
