// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlaceapplyTbl = "placeapply_tbl"

// PlaceapplyTbl mapped from table <placeapply_tbl>
type PlaceapplyTbl struct {
	ID              string `gorm:"column:id" json:"id"`
	Ownerid         string `gorm:"column:ownerid;comment:业主id" json:"ownerid"`                 // 业主id
	Name            string `gorm:"column:name;comment:业主姓名" json:"name"`                       // 业主姓名
	IDNumber        string `gorm:"column:idNumber;comment:身份证号码" json:"idNumber"`              // 身份证号码
	IDCardP         string `gorm:"column:idCard_p;comment:身份证正面照" json:"idCard_p"`             // 身份证正面照
	IDCardR         string `gorm:"column:idCard_r;comment:身份证反面照" json:"idCard_r"`             // 身份证反面照
	Prove           string `gorm:"column:prove;comment:产权证明" json:"prove"`                     // 产权证明
	Province        string `gorm:"column:province;comment:省" json:"province"`                  // 省
	City            string `gorm:"column:city;comment:市" json:"city"`                          // 市
	District        string `gorm:"column:district;comment:区" json:"district"`                  // 区
	Code            string `gorm:"column:code;comment:六位行政码" json:"code"`                      // 六位行政码
	Streer          string `gorm:"column:streer;comment:街道" json:"streer"`                     // 街道
	RelatedBuilding string `gorm:"column:relatedBuilding;comment:所在小区" json:"relatedBuilding"` // 所在小区
	Carnumber       string `gorm:"column:carnumber;comment:车位编号防止重复提交" json:"carnumber"`       // 车位编号防止重复提交
	ApplyTime       string `gorm:"column:applyTime;comment:申请时间" json:"applyTime"`             // 申请时间
	State           string `gorm:"column:state;comment:状态" json:"state"`                       // 状态
}

// TableName PlaceapplyTbl's table name
func (*PlaceapplyTbl) TableName() string {
	return TableNamePlaceapplyTbl
}
