// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReOrderElectronicTbl = "re_order_electronic_tbl"

// ReOrderElectronicTbl 二轮车订单充电时段电量
type ReOrderElectronicTbl struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`               // 主键id
	OrderID     string    `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                        // 订单id
	StartValue  float64   `gorm:"column:start_value;comment:开始时电表值" json:"start_value"`                         // 开始时电表值
	OverValue   float64   `gorm:"column:over_value;comment:结束时电表值" json:"over_value"`                           // 结束时电表值
	PriceTimeID int32     `gorm:"column:price_time_id;comment:充电时段id" json:"price_time_id"`                     // 充电时段id
	Power       string    `gorm:"column:power;comment:功率" json:"power"`                                         // 功率
	Count       int32     `gorm:"column:count;comment:次数" json:"count"`                                         // 次数
	MaxPower    float64   `gorm:"column:max_power;comment:最大功率" json:"max_power"`                               // 最大功率
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName ReOrderElectronicTbl's table name
func (*ReOrderElectronicTbl) TableName() string {
	return TableNameReOrderElectronicTbl
}
