// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReceptacleTbl = "receptacle_tbl"

// ReceptacleTbl 二轮车插座表
type ReceptacleTbl struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`               // 主键id
	Name       string    `gorm:"column:name;comment:插座名" json:"name"`                                          // 插座名
	Number     int32     `gorm:"column:number;comment:插座编号" json:"number"`                                     // 插座编号
	Status     int32     `gorm:"column:status;comment:状态（0-空闲 1-充电中 -1-故障）" json:"status"`                     // 状态（0-空闲 1-充电中 -1-故障）
	Pid        string    `gorm:"column:pid;comment:pid" json:"pid"`                                            // pid
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:安装时间" json:"create_time"` // 安装时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName ReceptacleTbl's table name
func (*ReceptacleTbl) TableName() string {
	return TableNameReceptacleTbl
}
