// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTabOrderElectronic = "tab_order_electronic"

// TabOrderElectronic 四轮车订单充电时段电量
type TabOrderElectronic struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID     string    `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                        // 订单id
	StartValue  float64   `gorm:"column:start_value;comment:开始时电表值" json:"start_value"`                         // 开始时电表值
	OverValue   float64   `gorm:"column:over_value;comment:结束时电表值" json:"over_value"`                           // 结束时电表值
	PriceTimeID int32     `gorm:"column:price_time_id;not null;comment:充电时间段id" json:"price_time_id"`           // 充电时间段id
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName TabOrderElectronic's table name
func (*TabOrderElectronic) TableName() string {
	return TableNameTabOrderElectronic
}
