// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBankCardTbl = "user_bank_card_tbl"

// UserBankCardTbl 用户银行卡信息表
type UserBankCardTbl struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`               // 主键id
	Openid     string    `gorm:"column:openid;not null;comment:微信用户唯一openid" json:"openid"`                    // 微信用户唯一openid
	CardNumber string    `gorm:"column:card_number;not null;comment:银行卡账号" json:"card_number"`                 // 银行卡账号
	HolderName string    `gorm:"column:holder_name;not null;comment:开户人姓名" json:"holder_name"`                 // 开户人姓名
	Bank       string    `gorm:"column:bank;not null;comment:开户行" json:"bank"`                                 // 开户行
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName UserBankCardTbl's table name
func (*UserBankCardTbl) TableName() string {
	return TableNameUserBankCardTbl
}
