// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsermessageTbl = "usermessage_tbl"

// UsermessageTbl 已废弃
type UsermessageTbl struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Openid     string    `gorm:"column:openid" json:"openid"`
	Message    string    `gorm:"column:message" json:"message"`
	MsgTime    string    `gorm:"column:msgTime" json:"msgTime"`
	Status     string    `gorm:"column:status" json:"status"`
	IsDelete   int32     `gorm:"column:isDelete;not null" json:"isDelete"`
	CreateTime time.Time `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP" json:"createTime"`
	UpdateTime time.Time `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP" json:"updateTime"`
}

// TableName UsermessageTbl's table name
func (*UsermessageTbl) TableName() string {
	return TableNameUsermessageTbl
}
