// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVersionTbl = "version_tbl"

// VersionTbl 版本信息表
type VersionTbl struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`               // 主键id
	VersionNumber string    `gorm:"column:version_number;not null;comment:版本号" json:"version_number"`             // 版本号
	Content       string    `gorm:"column:content;comment:更新内容" json:"content"`                                   // 更新内容
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName VersionTbl's table name
func (*VersionTbl) TableName() string {
	return TableNameVersionTbl
}
