// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newAppointmentTbl(db *gorm.DB, opts ...gen.DOOption) appointmentTbl {
	_appointmentTbl := appointmentTbl{}

	_appointmentTbl.appointmentTblDo.UseDB(db, opts...)
	_appointmentTbl.appointmentTblDo.UseModel(&model.AppointmentTbl{})

	tableName := _appointmentTbl.appointmentTblDo.TableName()
	_appointmentTbl.ALL = field.NewAsterisk(tableName)
	_appointmentTbl.Openid = field.NewString(tableName, "openid")
	_appointmentTbl.Lockid = field.NewString(tableName, "lockid")
	_appointmentTbl.ReserveTime = field.NewString(tableName, "reserveTime")
	_appointmentTbl.Status = field.NewString(tableName, "status")
	_appointmentTbl.PlateNum = field.NewString(tableName, "plate_num")
	_appointmentTbl.PalteColor = field.NewString(tableName, "palte_color")

	_appointmentTbl.fillFieldMap()

	return _appointmentTbl
}

type appointmentTbl struct {
	appointmentTblDo appointmentTblDo

	ALL         field.Asterisk
	Openid      field.String
	Lockid      field.String
	ReserveTime field.String
	Status      field.String
	PlateNum    field.String
	PalteColor  field.String

	fieldMap map[string]field.Expr
}

func (a appointmentTbl) Table(newTableName string) *appointmentTbl {
	a.appointmentTblDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appointmentTbl) As(alias string) *appointmentTbl {
	a.appointmentTblDo.DO = *(a.appointmentTblDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appointmentTbl) updateTableName(table string) *appointmentTbl {
	a.ALL = field.NewAsterisk(table)
	a.Openid = field.NewString(table, "openid")
	a.Lockid = field.NewString(table, "lockid")
	a.ReserveTime = field.NewString(table, "reserveTime")
	a.Status = field.NewString(table, "status")
	a.PlateNum = field.NewString(table, "plate_num")
	a.PalteColor = field.NewString(table, "palte_color")

	a.fillFieldMap()

	return a
}

func (a *appointmentTbl) WithContext(ctx context.Context) IAppointmentTblDo {
	return a.appointmentTblDo.WithContext(ctx)
}

func (a appointmentTbl) TableName() string { return a.appointmentTblDo.TableName() }

func (a appointmentTbl) Alias() string { return a.appointmentTblDo.Alias() }

func (a appointmentTbl) Columns(cols ...field.Expr) gen.Columns {
	return a.appointmentTblDo.Columns(cols...)
}

func (a *appointmentTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appointmentTbl) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["openid"] = a.Openid
	a.fieldMap["lockid"] = a.Lockid
	a.fieldMap["reserveTime"] = a.ReserveTime
	a.fieldMap["status"] = a.Status
	a.fieldMap["plate_num"] = a.PlateNum
	a.fieldMap["palte_color"] = a.PalteColor
}

func (a appointmentTbl) clone(db *gorm.DB) appointmentTbl {
	a.appointmentTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appointmentTbl) replaceDB(db *gorm.DB) appointmentTbl {
	a.appointmentTblDo.ReplaceDB(db)
	return a
}

type appointmentTblDo struct{ gen.DO }

type IAppointmentTblDo interface {
	gen.SubQuery
	Debug() IAppointmentTblDo
	WithContext(ctx context.Context) IAppointmentTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppointmentTblDo
	WriteDB() IAppointmentTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppointmentTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppointmentTblDo
	Not(conds ...gen.Condition) IAppointmentTblDo
	Or(conds ...gen.Condition) IAppointmentTblDo
	Select(conds ...field.Expr) IAppointmentTblDo
	Where(conds ...gen.Condition) IAppointmentTblDo
	Order(conds ...field.Expr) IAppointmentTblDo
	Distinct(cols ...field.Expr) IAppointmentTblDo
	Omit(cols ...field.Expr) IAppointmentTblDo
	Join(table schema.Tabler, on ...field.Expr) IAppointmentTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppointmentTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppointmentTblDo
	Group(cols ...field.Expr) IAppointmentTblDo
	Having(conds ...gen.Condition) IAppointmentTblDo
	Limit(limit int) IAppointmentTblDo
	Offset(offset int) IAppointmentTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppointmentTblDo
	Unscoped() IAppointmentTblDo
	Create(values ...*model.AppointmentTbl) error
	CreateInBatches(values []*model.AppointmentTbl, batchSize int) error
	Save(values ...*model.AppointmentTbl) error
	First() (*model.AppointmentTbl, error)
	Take() (*model.AppointmentTbl, error)
	Last() (*model.AppointmentTbl, error)
	Find() ([]*model.AppointmentTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppointmentTbl, err error)
	FindInBatches(result *[]*model.AppointmentTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppointmentTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppointmentTblDo
	Assign(attrs ...field.AssignExpr) IAppointmentTblDo
	Joins(fields ...field.RelationField) IAppointmentTblDo
	Preload(fields ...field.RelationField) IAppointmentTblDo
	FirstOrInit() (*model.AppointmentTbl, error)
	FirstOrCreate() (*model.AppointmentTbl, error)
	FindByPage(offset int, limit int) (result []*model.AppointmentTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppointmentTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appointmentTblDo) Debug() IAppointmentTblDo {
	return a.withDO(a.DO.Debug())
}

func (a appointmentTblDo) WithContext(ctx context.Context) IAppointmentTblDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appointmentTblDo) ReadDB() IAppointmentTblDo {
	return a.Clauses(dbresolver.Read)
}

func (a appointmentTblDo) WriteDB() IAppointmentTblDo {
	return a.Clauses(dbresolver.Write)
}

func (a appointmentTblDo) Session(config *gorm.Session) IAppointmentTblDo {
	return a.withDO(a.DO.Session(config))
}

func (a appointmentTblDo) Clauses(conds ...clause.Expression) IAppointmentTblDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appointmentTblDo) Returning(value interface{}, columns ...string) IAppointmentTblDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appointmentTblDo) Not(conds ...gen.Condition) IAppointmentTblDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appointmentTblDo) Or(conds ...gen.Condition) IAppointmentTblDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appointmentTblDo) Select(conds ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appointmentTblDo) Where(conds ...gen.Condition) IAppointmentTblDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appointmentTblDo) Order(conds ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appointmentTblDo) Distinct(cols ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appointmentTblDo) Omit(cols ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appointmentTblDo) Join(table schema.Tabler, on ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appointmentTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appointmentTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appointmentTblDo) Group(cols ...field.Expr) IAppointmentTblDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appointmentTblDo) Having(conds ...gen.Condition) IAppointmentTblDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appointmentTblDo) Limit(limit int) IAppointmentTblDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appointmentTblDo) Offset(offset int) IAppointmentTblDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appointmentTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppointmentTblDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appointmentTblDo) Unscoped() IAppointmentTblDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appointmentTblDo) Create(values ...*model.AppointmentTbl) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appointmentTblDo) CreateInBatches(values []*model.AppointmentTbl, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appointmentTblDo) Save(values ...*model.AppointmentTbl) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appointmentTblDo) First() (*model.AppointmentTbl, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppointmentTbl), nil
	}
}

func (a appointmentTblDo) Take() (*model.AppointmentTbl, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppointmentTbl), nil
	}
}

func (a appointmentTblDo) Last() (*model.AppointmentTbl, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppointmentTbl), nil
	}
}

func (a appointmentTblDo) Find() ([]*model.AppointmentTbl, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppointmentTbl), err
}

func (a appointmentTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppointmentTbl, err error) {
	buf := make([]*model.AppointmentTbl, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appointmentTblDo) FindInBatches(result *[]*model.AppointmentTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appointmentTblDo) Attrs(attrs ...field.AssignExpr) IAppointmentTblDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appointmentTblDo) Assign(attrs ...field.AssignExpr) IAppointmentTblDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appointmentTblDo) Joins(fields ...field.RelationField) IAppointmentTblDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appointmentTblDo) Preload(fields ...field.RelationField) IAppointmentTblDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appointmentTblDo) FirstOrInit() (*model.AppointmentTbl, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppointmentTbl), nil
	}
}

func (a appointmentTblDo) FirstOrCreate() (*model.AppointmentTbl, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppointmentTbl), nil
	}
}

func (a appointmentTblDo) FindByPage(offset int, limit int) (result []*model.AppointmentTbl, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appointmentTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appointmentTblDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appointmentTblDo) Delete(models ...*model.AppointmentTbl) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appointmentTblDo) withDO(do gen.Dao) *appointmentTblDo {
	a.DO = *do.(*gen.DO)
	return a
}
