// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newChargeMessageTbl(db *gorm.DB, opts ...gen.DOOption) chargeMessageTbl {
	_chargeMessageTbl := chargeMessageTbl{}

	_chargeMessageTbl.chargeMessageTblDo.UseDB(db, opts...)
	_chargeMessageTbl.chargeMessageTblDo.UseModel(&model.ChargeMessageTbl{})

	tableName := _chargeMessageTbl.chargeMessageTblDo.TableName()
	_chargeMessageTbl.ALL = field.NewAsterisk(tableName)
	_chargeMessageTbl.Chargeid = field.NewString(tableName, "chargeid")
	_chargeMessageTbl.Placeid = field.NewString(tableName, "placeid")
	_chargeMessageTbl.IsDelete = field.NewInt32(tableName, "isDelete")
	_chargeMessageTbl.CreateTime = field.NewTime(tableName, "createTime")
	_chargeMessageTbl.UpdateTime = field.NewTime(tableName, "updateTime")
	_chargeMessageTbl.Nid = field.NewString(tableName, "nid")
	_chargeMessageTbl.Direction = field.NewString(tableName, "direction")
	_chargeMessageTbl.Ammeter = field.NewString(tableName, "ammeter")
	_chargeMessageTbl.ProductID = field.NewString(tableName, "ProductID")
	_chargeMessageTbl.Gateway = field.NewString(tableName, "gateway")

	_chargeMessageTbl.fillFieldMap()

	return _chargeMessageTbl
}

// chargeMessageTbl 业主车位对应的枪表
type chargeMessageTbl struct {
	chargeMessageTblDo chargeMessageTblDo

	ALL        field.Asterisk
	Chargeid   field.String
	Placeid    field.String // 绑定车位编号
	IsDelete   field.Int32  // 逻辑删除
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间
	Nid        field.String // 充电桩模块NID
	Direction  field.String // 车位位于充电桩左右
	Ammeter    field.String // 电表地址
	ProductID  field.String // 产品ID
	Gateway    field.String // 网关

	fieldMap map[string]field.Expr
}

func (c chargeMessageTbl) Table(newTableName string) *chargeMessageTbl {
	c.chargeMessageTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chargeMessageTbl) As(alias string) *chargeMessageTbl {
	c.chargeMessageTblDo.DO = *(c.chargeMessageTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chargeMessageTbl) updateTableName(table string) *chargeMessageTbl {
	c.ALL = field.NewAsterisk(table)
	c.Chargeid = field.NewString(table, "chargeid")
	c.Placeid = field.NewString(table, "placeid")
	c.IsDelete = field.NewInt32(table, "isDelete")
	c.CreateTime = field.NewTime(table, "createTime")
	c.UpdateTime = field.NewTime(table, "updateTime")
	c.Nid = field.NewString(table, "nid")
	c.Direction = field.NewString(table, "direction")
	c.Ammeter = field.NewString(table, "ammeter")
	c.ProductID = field.NewString(table, "ProductID")
	c.Gateway = field.NewString(table, "gateway")

	c.fillFieldMap()

	return c
}

func (c *chargeMessageTbl) WithContext(ctx context.Context) IChargeMessageTblDo {
	return c.chargeMessageTblDo.WithContext(ctx)
}

func (c chargeMessageTbl) TableName() string { return c.chargeMessageTblDo.TableName() }

func (c chargeMessageTbl) Alias() string { return c.chargeMessageTblDo.Alias() }

func (c chargeMessageTbl) Columns(cols ...field.Expr) gen.Columns {
	return c.chargeMessageTblDo.Columns(cols...)
}

func (c *chargeMessageTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chargeMessageTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["chargeid"] = c.Chargeid
	c.fieldMap["placeid"] = c.Placeid
	c.fieldMap["isDelete"] = c.IsDelete
	c.fieldMap["createTime"] = c.CreateTime
	c.fieldMap["updateTime"] = c.UpdateTime
	c.fieldMap["nid"] = c.Nid
	c.fieldMap["direction"] = c.Direction
	c.fieldMap["ammeter"] = c.Ammeter
	c.fieldMap["ProductID"] = c.ProductID
	c.fieldMap["gateway"] = c.Gateway
}

func (c chargeMessageTbl) clone(db *gorm.DB) chargeMessageTbl {
	c.chargeMessageTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chargeMessageTbl) replaceDB(db *gorm.DB) chargeMessageTbl {
	c.chargeMessageTblDo.ReplaceDB(db)
	return c
}

type chargeMessageTblDo struct{ gen.DO }

type IChargeMessageTblDo interface {
	gen.SubQuery
	Debug() IChargeMessageTblDo
	WithContext(ctx context.Context) IChargeMessageTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChargeMessageTblDo
	WriteDB() IChargeMessageTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChargeMessageTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChargeMessageTblDo
	Not(conds ...gen.Condition) IChargeMessageTblDo
	Or(conds ...gen.Condition) IChargeMessageTblDo
	Select(conds ...field.Expr) IChargeMessageTblDo
	Where(conds ...gen.Condition) IChargeMessageTblDo
	Order(conds ...field.Expr) IChargeMessageTblDo
	Distinct(cols ...field.Expr) IChargeMessageTblDo
	Omit(cols ...field.Expr) IChargeMessageTblDo
	Join(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo
	Group(cols ...field.Expr) IChargeMessageTblDo
	Having(conds ...gen.Condition) IChargeMessageTblDo
	Limit(limit int) IChargeMessageTblDo
	Offset(offset int) IChargeMessageTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChargeMessageTblDo
	Unscoped() IChargeMessageTblDo
	Create(values ...*model.ChargeMessageTbl) error
	CreateInBatches(values []*model.ChargeMessageTbl, batchSize int) error
	Save(values ...*model.ChargeMessageTbl) error
	First() (*model.ChargeMessageTbl, error)
	Take() (*model.ChargeMessageTbl, error)
	Last() (*model.ChargeMessageTbl, error)
	Find() ([]*model.ChargeMessageTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargeMessageTbl, err error)
	FindInBatches(result *[]*model.ChargeMessageTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChargeMessageTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChargeMessageTblDo
	Assign(attrs ...field.AssignExpr) IChargeMessageTblDo
	Joins(fields ...field.RelationField) IChargeMessageTblDo
	Preload(fields ...field.RelationField) IChargeMessageTblDo
	FirstOrInit() (*model.ChargeMessageTbl, error)
	FirstOrCreate() (*model.ChargeMessageTbl, error)
	FindByPage(offset int, limit int) (result []*model.ChargeMessageTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChargeMessageTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chargeMessageTblDo) Debug() IChargeMessageTblDo {
	return c.withDO(c.DO.Debug())
}

func (c chargeMessageTblDo) WithContext(ctx context.Context) IChargeMessageTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chargeMessageTblDo) ReadDB() IChargeMessageTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c chargeMessageTblDo) WriteDB() IChargeMessageTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c chargeMessageTblDo) Session(config *gorm.Session) IChargeMessageTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c chargeMessageTblDo) Clauses(conds ...clause.Expression) IChargeMessageTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chargeMessageTblDo) Returning(value interface{}, columns ...string) IChargeMessageTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chargeMessageTblDo) Not(conds ...gen.Condition) IChargeMessageTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chargeMessageTblDo) Or(conds ...gen.Condition) IChargeMessageTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chargeMessageTblDo) Select(conds ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chargeMessageTblDo) Where(conds ...gen.Condition) IChargeMessageTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chargeMessageTblDo) Order(conds ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chargeMessageTblDo) Distinct(cols ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chargeMessageTblDo) Omit(cols ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chargeMessageTblDo) Join(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chargeMessageTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chargeMessageTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chargeMessageTblDo) Group(cols ...field.Expr) IChargeMessageTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chargeMessageTblDo) Having(conds ...gen.Condition) IChargeMessageTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chargeMessageTblDo) Limit(limit int) IChargeMessageTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chargeMessageTblDo) Offset(offset int) IChargeMessageTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chargeMessageTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChargeMessageTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chargeMessageTblDo) Unscoped() IChargeMessageTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chargeMessageTblDo) Create(values ...*model.ChargeMessageTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chargeMessageTblDo) CreateInBatches(values []*model.ChargeMessageTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chargeMessageTblDo) Save(values ...*model.ChargeMessageTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chargeMessageTblDo) First() (*model.ChargeMessageTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeMessageTbl), nil
	}
}

func (c chargeMessageTblDo) Take() (*model.ChargeMessageTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeMessageTbl), nil
	}
}

func (c chargeMessageTblDo) Last() (*model.ChargeMessageTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeMessageTbl), nil
	}
}

func (c chargeMessageTblDo) Find() ([]*model.ChargeMessageTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChargeMessageTbl), err
}

func (c chargeMessageTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargeMessageTbl, err error) {
	buf := make([]*model.ChargeMessageTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chargeMessageTblDo) FindInBatches(result *[]*model.ChargeMessageTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chargeMessageTblDo) Attrs(attrs ...field.AssignExpr) IChargeMessageTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chargeMessageTblDo) Assign(attrs ...field.AssignExpr) IChargeMessageTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chargeMessageTblDo) Joins(fields ...field.RelationField) IChargeMessageTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chargeMessageTblDo) Preload(fields ...field.RelationField) IChargeMessageTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chargeMessageTblDo) FirstOrInit() (*model.ChargeMessageTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeMessageTbl), nil
	}
}

func (c chargeMessageTblDo) FirstOrCreate() (*model.ChargeMessageTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeMessageTbl), nil
	}
}

func (c chargeMessageTblDo) FindByPage(offset int, limit int) (result []*model.ChargeMessageTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chargeMessageTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chargeMessageTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chargeMessageTblDo) Delete(models ...*model.ChargeMessageTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chargeMessageTblDo) withDO(do gen.Dao) *chargeMessageTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
