// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newChargingStateTbl(db *gorm.DB, opts ...gen.DOOption) chargingStateTbl {
	_chargingStateTbl := chargingStateTbl{}

	_chargingStateTbl.chargingStateTblDo.UseDB(db, opts...)
	_chargingStateTbl.chargingStateTblDo.UseModel(&model.ChargingStateTbl{})

	tableName := _chargingStateTbl.chargingStateTblDo.TableName()
	_chargingStateTbl.ALL = field.NewAsterisk(tableName)
	_chargingStateTbl.ID = field.NewInt32(tableName, "id")
	_chargingStateTbl.ProductID = field.NewString(tableName, "product_id")
	_chargingStateTbl.Direction = field.NewString(tableName, "direction")
	_chargingStateTbl.EmergencyButtonState = field.NewString(tableName, "emergency_button_state")
	_chargingStateTbl.DoorLockState = field.NewString(tableName, "door_lock_state")
	_chargingStateTbl.ProductName = field.NewString(tableName, "product_name")
	_chargingStateTbl.Model = field.NewString(tableName, "model")
	_chargingStateTbl.Address = field.NewString(tableName, "address")
	_chargingStateTbl.Area = field.NewString(tableName, "area")
	_chargingStateTbl.AreaOmName = field.NewString(tableName, "area_om_name")
	_chargingStateTbl.AreaOmPhone = field.NewString(tableName, "area_om_phone")
	_chargingStateTbl.ProductOwnership = field.NewString(tableName, "product_ownership")
	_chargingStateTbl.Phone = field.NewString(tableName, "phone")
	_chargingStateTbl.CreateTime = field.NewTime(tableName, "create_time")
	_chargingStateTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_chargingStateTbl.fillFieldMap()

	return _chargingStateTbl
}

// chargingStateTbl 充电桩-实时状态表
type chargingStateTbl struct {
	chargingStateTblDo chargingStateTblDo

	ALL                  field.Asterisk
	ID                   field.Int32  // 主键id
	ProductID            field.String // 设备id
	Direction            field.String // 设备方向
	EmergencyButtonState field.String // 应急按钮状态
	DoorLockState        field.String // 门锁状态
	ProductName          field.String // 设备名称
	Model                field.String // 型号(220v/380v)
	Address              field.String // 安装位置
	Area                 field.String // 区域
	AreaOmName           field.String // 片区运维负责人
	AreaOmPhone          field.String // 联系电话
	ProductOwnership     field.String // 设备产权人
	Phone                field.String // 联系电话
	CreateTime           field.Time   // 创建时间
	UpdateTime           field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c chargingStateTbl) Table(newTableName string) *chargingStateTbl {
	c.chargingStateTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chargingStateTbl) As(alias string) *chargingStateTbl {
	c.chargingStateTblDo.DO = *(c.chargingStateTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chargingStateTbl) updateTableName(table string) *chargingStateTbl {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.ProductID = field.NewString(table, "product_id")
	c.Direction = field.NewString(table, "direction")
	c.EmergencyButtonState = field.NewString(table, "emergency_button_state")
	c.DoorLockState = field.NewString(table, "door_lock_state")
	c.ProductName = field.NewString(table, "product_name")
	c.Model = field.NewString(table, "model")
	c.Address = field.NewString(table, "address")
	c.Area = field.NewString(table, "area")
	c.AreaOmName = field.NewString(table, "area_om_name")
	c.AreaOmPhone = field.NewString(table, "area_om_phone")
	c.ProductOwnership = field.NewString(table, "product_ownership")
	c.Phone = field.NewString(table, "phone")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *chargingStateTbl) WithContext(ctx context.Context) IChargingStateTblDo {
	return c.chargingStateTblDo.WithContext(ctx)
}

func (c chargingStateTbl) TableName() string { return c.chargingStateTblDo.TableName() }

func (c chargingStateTbl) Alias() string { return c.chargingStateTblDo.Alias() }

func (c chargingStateTbl) Columns(cols ...field.Expr) gen.Columns {
	return c.chargingStateTblDo.Columns(cols...)
}

func (c *chargingStateTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chargingStateTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["id"] = c.ID
	c.fieldMap["product_id"] = c.ProductID
	c.fieldMap["direction"] = c.Direction
	c.fieldMap["emergency_button_state"] = c.EmergencyButtonState
	c.fieldMap["door_lock_state"] = c.DoorLockState
	c.fieldMap["product_name"] = c.ProductName
	c.fieldMap["model"] = c.Model
	c.fieldMap["address"] = c.Address
	c.fieldMap["area"] = c.Area
	c.fieldMap["area_om_name"] = c.AreaOmName
	c.fieldMap["area_om_phone"] = c.AreaOmPhone
	c.fieldMap["product_ownership"] = c.ProductOwnership
	c.fieldMap["phone"] = c.Phone
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c chargingStateTbl) clone(db *gorm.DB) chargingStateTbl {
	c.chargingStateTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chargingStateTbl) replaceDB(db *gorm.DB) chargingStateTbl {
	c.chargingStateTblDo.ReplaceDB(db)
	return c
}

type chargingStateTblDo struct{ gen.DO }

type IChargingStateTblDo interface {
	gen.SubQuery
	Debug() IChargingStateTblDo
	WithContext(ctx context.Context) IChargingStateTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChargingStateTblDo
	WriteDB() IChargingStateTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChargingStateTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChargingStateTblDo
	Not(conds ...gen.Condition) IChargingStateTblDo
	Or(conds ...gen.Condition) IChargingStateTblDo
	Select(conds ...field.Expr) IChargingStateTblDo
	Where(conds ...gen.Condition) IChargingStateTblDo
	Order(conds ...field.Expr) IChargingStateTblDo
	Distinct(cols ...field.Expr) IChargingStateTblDo
	Omit(cols ...field.Expr) IChargingStateTblDo
	Join(table schema.Tabler, on ...field.Expr) IChargingStateTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChargingStateTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChargingStateTblDo
	Group(cols ...field.Expr) IChargingStateTblDo
	Having(conds ...gen.Condition) IChargingStateTblDo
	Limit(limit int) IChargingStateTblDo
	Offset(offset int) IChargingStateTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingStateTblDo
	Unscoped() IChargingStateTblDo
	Create(values ...*model.ChargingStateTbl) error
	CreateInBatches(values []*model.ChargingStateTbl, batchSize int) error
	Save(values ...*model.ChargingStateTbl) error
	First() (*model.ChargingStateTbl, error)
	Take() (*model.ChargingStateTbl, error)
	Last() (*model.ChargingStateTbl, error)
	Find() ([]*model.ChargingStateTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingStateTbl, err error)
	FindInBatches(result *[]*model.ChargingStateTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChargingStateTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChargingStateTblDo
	Assign(attrs ...field.AssignExpr) IChargingStateTblDo
	Joins(fields ...field.RelationField) IChargingStateTblDo
	Preload(fields ...field.RelationField) IChargingStateTblDo
	FirstOrInit() (*model.ChargingStateTbl, error)
	FirstOrCreate() (*model.ChargingStateTbl, error)
	FindByPage(offset int, limit int) (result []*model.ChargingStateTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChargingStateTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chargingStateTblDo) Debug() IChargingStateTblDo {
	return c.withDO(c.DO.Debug())
}

func (c chargingStateTblDo) WithContext(ctx context.Context) IChargingStateTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chargingStateTblDo) ReadDB() IChargingStateTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c chargingStateTblDo) WriteDB() IChargingStateTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c chargingStateTblDo) Session(config *gorm.Session) IChargingStateTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c chargingStateTblDo) Clauses(conds ...clause.Expression) IChargingStateTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chargingStateTblDo) Returning(value interface{}, columns ...string) IChargingStateTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chargingStateTblDo) Not(conds ...gen.Condition) IChargingStateTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chargingStateTblDo) Or(conds ...gen.Condition) IChargingStateTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chargingStateTblDo) Select(conds ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chargingStateTblDo) Where(conds ...gen.Condition) IChargingStateTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chargingStateTblDo) Order(conds ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chargingStateTblDo) Distinct(cols ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chargingStateTblDo) Omit(cols ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chargingStateTblDo) Join(table schema.Tabler, on ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chargingStateTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chargingStateTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chargingStateTblDo) Group(cols ...field.Expr) IChargingStateTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chargingStateTblDo) Having(conds ...gen.Condition) IChargingStateTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chargingStateTblDo) Limit(limit int) IChargingStateTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chargingStateTblDo) Offset(offset int) IChargingStateTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chargingStateTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingStateTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chargingStateTblDo) Unscoped() IChargingStateTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chargingStateTblDo) Create(values ...*model.ChargingStateTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chargingStateTblDo) CreateInBatches(values []*model.ChargingStateTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chargingStateTblDo) Save(values ...*model.ChargingStateTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chargingStateTblDo) First() (*model.ChargingStateTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStateTbl), nil
	}
}

func (c chargingStateTblDo) Take() (*model.ChargingStateTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStateTbl), nil
	}
}

func (c chargingStateTblDo) Last() (*model.ChargingStateTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStateTbl), nil
	}
}

func (c chargingStateTblDo) Find() ([]*model.ChargingStateTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChargingStateTbl), err
}

func (c chargingStateTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingStateTbl, err error) {
	buf := make([]*model.ChargingStateTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chargingStateTblDo) FindInBatches(result *[]*model.ChargingStateTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chargingStateTblDo) Attrs(attrs ...field.AssignExpr) IChargingStateTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chargingStateTblDo) Assign(attrs ...field.AssignExpr) IChargingStateTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chargingStateTblDo) Joins(fields ...field.RelationField) IChargingStateTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chargingStateTblDo) Preload(fields ...field.RelationField) IChargingStateTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chargingStateTblDo) FirstOrInit() (*model.ChargingStateTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStateTbl), nil
	}
}

func (c chargingStateTblDo) FirstOrCreate() (*model.ChargingStateTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStateTbl), nil
	}
}

func (c chargingStateTblDo) FindByPage(offset int, limit int) (result []*model.ChargingStateTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chargingStateTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chargingStateTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chargingStateTblDo) Delete(models ...*model.ChargingStateTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chargingStateTblDo) withDO(do gen.Dao) *chargingStateTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
