// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newChargeTbl(db *gorm.DB, opts ...gen.DOOption) chargeTbl {
	_chargeTbl := chargeTbl{}

	_chargeTbl.chargeTblDo.UseDB(db, opts...)
	_chargeTbl.chargeTblDo.UseModel(&model.ChargeTbl{})

	tableName := _chargeTbl.chargeTblDo.TableName()
	_chargeTbl.ALL = field.NewAsterisk(tableName)
	_chargeTbl.Placeid = field.NewString(tableName, "placeid")
	_chargeTbl.Charge = field.NewString(tableName, "charge")

	_chargeTbl.fillFieldMap()

	return _chargeTbl
}

type chargeTbl struct {
	chargeTblDo chargeTblDo

	ALL     field.Asterisk
	Placeid field.String // 车位id
	Charge  field.String // 未通过；待审核；已通过

	fieldMap map[string]field.Expr
}

func (c chargeTbl) Table(newTableName string) *chargeTbl {
	c.chargeTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chargeTbl) As(alias string) *chargeTbl {
	c.chargeTblDo.DO = *(c.chargeTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chargeTbl) updateTableName(table string) *chargeTbl {
	c.ALL = field.NewAsterisk(table)
	c.Placeid = field.NewString(table, "placeid")
	c.Charge = field.NewString(table, "charge")

	c.fillFieldMap()

	return c
}

func (c *chargeTbl) WithContext(ctx context.Context) IChargeTblDo {
	return c.chargeTblDo.WithContext(ctx)
}

func (c chargeTbl) TableName() string { return c.chargeTblDo.TableName() }

func (c chargeTbl) Alias() string { return c.chargeTblDo.Alias() }

func (c chargeTbl) Columns(cols ...field.Expr) gen.Columns { return c.chargeTblDo.Columns(cols...) }

func (c *chargeTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chargeTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["placeid"] = c.Placeid
	c.fieldMap["charge"] = c.Charge
}

func (c chargeTbl) clone(db *gorm.DB) chargeTbl {
	c.chargeTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chargeTbl) replaceDB(db *gorm.DB) chargeTbl {
	c.chargeTblDo.ReplaceDB(db)
	return c
}

type chargeTblDo struct{ gen.DO }

type IChargeTblDo interface {
	gen.SubQuery
	Debug() IChargeTblDo
	WithContext(ctx context.Context) IChargeTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChargeTblDo
	WriteDB() IChargeTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChargeTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChargeTblDo
	Not(conds ...gen.Condition) IChargeTblDo
	Or(conds ...gen.Condition) IChargeTblDo
	Select(conds ...field.Expr) IChargeTblDo
	Where(conds ...gen.Condition) IChargeTblDo
	Order(conds ...field.Expr) IChargeTblDo
	Distinct(cols ...field.Expr) IChargeTblDo
	Omit(cols ...field.Expr) IChargeTblDo
	Join(table schema.Tabler, on ...field.Expr) IChargeTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChargeTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChargeTblDo
	Group(cols ...field.Expr) IChargeTblDo
	Having(conds ...gen.Condition) IChargeTblDo
	Limit(limit int) IChargeTblDo
	Offset(offset int) IChargeTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChargeTblDo
	Unscoped() IChargeTblDo
	Create(values ...*model.ChargeTbl) error
	CreateInBatches(values []*model.ChargeTbl, batchSize int) error
	Save(values ...*model.ChargeTbl) error
	First() (*model.ChargeTbl, error)
	Take() (*model.ChargeTbl, error)
	Last() (*model.ChargeTbl, error)
	Find() ([]*model.ChargeTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargeTbl, err error)
	FindInBatches(result *[]*model.ChargeTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChargeTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChargeTblDo
	Assign(attrs ...field.AssignExpr) IChargeTblDo
	Joins(fields ...field.RelationField) IChargeTblDo
	Preload(fields ...field.RelationField) IChargeTblDo
	FirstOrInit() (*model.ChargeTbl, error)
	FirstOrCreate() (*model.ChargeTbl, error)
	FindByPage(offset int, limit int) (result []*model.ChargeTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChargeTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chargeTblDo) Debug() IChargeTblDo {
	return c.withDO(c.DO.Debug())
}

func (c chargeTblDo) WithContext(ctx context.Context) IChargeTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chargeTblDo) ReadDB() IChargeTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c chargeTblDo) WriteDB() IChargeTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c chargeTblDo) Session(config *gorm.Session) IChargeTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c chargeTblDo) Clauses(conds ...clause.Expression) IChargeTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chargeTblDo) Returning(value interface{}, columns ...string) IChargeTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chargeTblDo) Not(conds ...gen.Condition) IChargeTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chargeTblDo) Or(conds ...gen.Condition) IChargeTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chargeTblDo) Select(conds ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chargeTblDo) Where(conds ...gen.Condition) IChargeTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chargeTblDo) Order(conds ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chargeTblDo) Distinct(cols ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chargeTblDo) Omit(cols ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chargeTblDo) Join(table schema.Tabler, on ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chargeTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chargeTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chargeTblDo) Group(cols ...field.Expr) IChargeTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chargeTblDo) Having(conds ...gen.Condition) IChargeTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chargeTblDo) Limit(limit int) IChargeTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chargeTblDo) Offset(offset int) IChargeTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chargeTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChargeTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chargeTblDo) Unscoped() IChargeTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chargeTblDo) Create(values ...*model.ChargeTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chargeTblDo) CreateInBatches(values []*model.ChargeTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chargeTblDo) Save(values ...*model.ChargeTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chargeTblDo) First() (*model.ChargeTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeTbl), nil
	}
}

func (c chargeTblDo) Take() (*model.ChargeTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeTbl), nil
	}
}

func (c chargeTblDo) Last() (*model.ChargeTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeTbl), nil
	}
}

func (c chargeTblDo) Find() ([]*model.ChargeTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChargeTbl), err
}

func (c chargeTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargeTbl, err error) {
	buf := make([]*model.ChargeTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chargeTblDo) FindInBatches(result *[]*model.ChargeTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chargeTblDo) Attrs(attrs ...field.AssignExpr) IChargeTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chargeTblDo) Assign(attrs ...field.AssignExpr) IChargeTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chargeTblDo) Joins(fields ...field.RelationField) IChargeTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chargeTblDo) Preload(fields ...field.RelationField) IChargeTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chargeTblDo) FirstOrInit() (*model.ChargeTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeTbl), nil
	}
}

func (c chargeTblDo) FirstOrCreate() (*model.ChargeTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargeTbl), nil
	}
}

func (c chargeTblDo) FindByPage(offset int, limit int) (result []*model.ChargeTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chargeTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chargeTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chargeTblDo) Delete(models ...*model.ChargeTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chargeTblDo) withDO(do gen.Dao) *chargeTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
