// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newChargingStationTbl(db *gorm.DB, opts ...gen.DOOption) chargingStationTbl {
	_chargingStationTbl := chargingStationTbl{}

	_chargingStationTbl.chargingStationTblDo.UseDB(db, opts...)
	_chargingStationTbl.chargingStationTblDo.UseModel(&model.ChargingStationTbl{})

	tableName := _chargingStationTbl.chargingStationTblDo.TableName()
	_chargingStationTbl.ALL = field.NewAsterisk(tableName)
	_chargingStationTbl.ID = field.NewInt32(tableName, "id")
	_chargingStationTbl.Point = field.NewString(tableName, "point")
	_chargingStationTbl.Place = field.NewString(tableName, "place")
	_chargingStationTbl.Name = field.NewString(tableName, "name")
	_chargingStationTbl.Openid = field.NewString(tableName, "openid")
	_chargingStationTbl.PowerMax = field.NewInt32(tableName, "power_max")
	_chargingStationTbl.Pid = field.NewString(tableName, "pid")
	_chargingStationTbl.CreateTime = field.NewTime(tableName, "create_time")
	_chargingStationTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_chargingStationTbl.fillFieldMap()

	return _chargingStationTbl
}

// chargingStationTbl 二轮车充电站
type chargingStationTbl struct {
	chargingStationTblDo chargingStationTblDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	Point      field.String // 经纬度点
	Place      field.String // 位置
	Name       field.String // 充电站名
	Openid     field.String // 用户openid
	PowerMax   field.Int32
	Pid        field.String // 产品id
	CreateTime field.Time   // 安装时间
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c chargingStationTbl) Table(newTableName string) *chargingStationTbl {
	c.chargingStationTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chargingStationTbl) As(alias string) *chargingStationTbl {
	c.chargingStationTblDo.DO = *(c.chargingStationTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chargingStationTbl) updateTableName(table string) *chargingStationTbl {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Point = field.NewString(table, "point")
	c.Place = field.NewString(table, "place")
	c.Name = field.NewString(table, "name")
	c.Openid = field.NewString(table, "openid")
	c.PowerMax = field.NewInt32(table, "power_max")
	c.Pid = field.NewString(table, "pid")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *chargingStationTbl) WithContext(ctx context.Context) IChargingStationTblDo {
	return c.chargingStationTblDo.WithContext(ctx)
}

func (c chargingStationTbl) TableName() string { return c.chargingStationTblDo.TableName() }

func (c chargingStationTbl) Alias() string { return c.chargingStationTblDo.Alias() }

func (c chargingStationTbl) Columns(cols ...field.Expr) gen.Columns {
	return c.chargingStationTblDo.Columns(cols...)
}

func (c *chargingStationTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chargingStationTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["point"] = c.Point
	c.fieldMap["place"] = c.Place
	c.fieldMap["name"] = c.Name
	c.fieldMap["openid"] = c.Openid
	c.fieldMap["power_max"] = c.PowerMax
	c.fieldMap["pid"] = c.Pid
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c chargingStationTbl) clone(db *gorm.DB) chargingStationTbl {
	c.chargingStationTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chargingStationTbl) replaceDB(db *gorm.DB) chargingStationTbl {
	c.chargingStationTblDo.ReplaceDB(db)
	return c
}

type chargingStationTblDo struct{ gen.DO }

type IChargingStationTblDo interface {
	gen.SubQuery
	Debug() IChargingStationTblDo
	WithContext(ctx context.Context) IChargingStationTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChargingStationTblDo
	WriteDB() IChargingStationTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChargingStationTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChargingStationTblDo
	Not(conds ...gen.Condition) IChargingStationTblDo
	Or(conds ...gen.Condition) IChargingStationTblDo
	Select(conds ...field.Expr) IChargingStationTblDo
	Where(conds ...gen.Condition) IChargingStationTblDo
	Order(conds ...field.Expr) IChargingStationTblDo
	Distinct(cols ...field.Expr) IChargingStationTblDo
	Omit(cols ...field.Expr) IChargingStationTblDo
	Join(table schema.Tabler, on ...field.Expr) IChargingStationTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChargingStationTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChargingStationTblDo
	Group(cols ...field.Expr) IChargingStationTblDo
	Having(conds ...gen.Condition) IChargingStationTblDo
	Limit(limit int) IChargingStationTblDo
	Offset(offset int) IChargingStationTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingStationTblDo
	Unscoped() IChargingStationTblDo
	Create(values ...*model.ChargingStationTbl) error
	CreateInBatches(values []*model.ChargingStationTbl, batchSize int) error
	Save(values ...*model.ChargingStationTbl) error
	First() (*model.ChargingStationTbl, error)
	Take() (*model.ChargingStationTbl, error)
	Last() (*model.ChargingStationTbl, error)
	Find() ([]*model.ChargingStationTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingStationTbl, err error)
	FindInBatches(result *[]*model.ChargingStationTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChargingStationTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChargingStationTblDo
	Assign(attrs ...field.AssignExpr) IChargingStationTblDo
	Joins(fields ...field.RelationField) IChargingStationTblDo
	Preload(fields ...field.RelationField) IChargingStationTblDo
	FirstOrInit() (*model.ChargingStationTbl, error)
	FirstOrCreate() (*model.ChargingStationTbl, error)
	FindByPage(offset int, limit int) (result []*model.ChargingStationTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChargingStationTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chargingStationTblDo) Debug() IChargingStationTblDo {
	return c.withDO(c.DO.Debug())
}

func (c chargingStationTblDo) WithContext(ctx context.Context) IChargingStationTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chargingStationTblDo) ReadDB() IChargingStationTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c chargingStationTblDo) WriteDB() IChargingStationTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c chargingStationTblDo) Session(config *gorm.Session) IChargingStationTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c chargingStationTblDo) Clauses(conds ...clause.Expression) IChargingStationTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chargingStationTblDo) Returning(value interface{}, columns ...string) IChargingStationTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chargingStationTblDo) Not(conds ...gen.Condition) IChargingStationTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chargingStationTblDo) Or(conds ...gen.Condition) IChargingStationTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chargingStationTblDo) Select(conds ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chargingStationTblDo) Where(conds ...gen.Condition) IChargingStationTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chargingStationTblDo) Order(conds ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chargingStationTblDo) Distinct(cols ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chargingStationTblDo) Omit(cols ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chargingStationTblDo) Join(table schema.Tabler, on ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chargingStationTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chargingStationTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chargingStationTblDo) Group(cols ...field.Expr) IChargingStationTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chargingStationTblDo) Having(conds ...gen.Condition) IChargingStationTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chargingStationTblDo) Limit(limit int) IChargingStationTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chargingStationTblDo) Offset(offset int) IChargingStationTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chargingStationTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingStationTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chargingStationTblDo) Unscoped() IChargingStationTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chargingStationTblDo) Create(values ...*model.ChargingStationTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chargingStationTblDo) CreateInBatches(values []*model.ChargingStationTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chargingStationTblDo) Save(values ...*model.ChargingStationTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chargingStationTblDo) First() (*model.ChargingStationTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStationTbl), nil
	}
}

func (c chargingStationTblDo) Take() (*model.ChargingStationTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStationTbl), nil
	}
}

func (c chargingStationTblDo) Last() (*model.ChargingStationTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStationTbl), nil
	}
}

func (c chargingStationTblDo) Find() ([]*model.ChargingStationTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChargingStationTbl), err
}

func (c chargingStationTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingStationTbl, err error) {
	buf := make([]*model.ChargingStationTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chargingStationTblDo) FindInBatches(result *[]*model.ChargingStationTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chargingStationTblDo) Attrs(attrs ...field.AssignExpr) IChargingStationTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chargingStationTblDo) Assign(attrs ...field.AssignExpr) IChargingStationTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chargingStationTblDo) Joins(fields ...field.RelationField) IChargingStationTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chargingStationTblDo) Preload(fields ...field.RelationField) IChargingStationTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chargingStationTblDo) FirstOrInit() (*model.ChargingStationTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStationTbl), nil
	}
}

func (c chargingStationTblDo) FirstOrCreate() (*model.ChargingStationTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingStationTbl), nil
	}
}

func (c chargingStationTblDo) FindByPage(offset int, limit int) (result []*model.ChargingStationTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chargingStationTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chargingStationTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chargingStationTblDo) Delete(models ...*model.ChargingStationTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chargingStationTblDo) withDO(do gen.Dao) *chargingStationTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
