// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newChargingPriceTbl(db *gorm.DB, opts ...gen.DOOption) chargingPriceTbl {
	_chargingPriceTbl := chargingPriceTbl{}

	_chargingPriceTbl.chargingPriceTblDo.UseDB(db, opts...)
	_chargingPriceTbl.chargingPriceTblDo.UseModel(&model.ChargingPriceTbl{})

	tableName := _chargingPriceTbl.chargingPriceTblDo.TableName()
	_chargingPriceTbl.ALL = field.NewAsterisk(tableName)
	_chargingPriceTbl.ID = field.NewInt32(tableName, "id")
	_chargingPriceTbl.Total = field.NewFloat64(tableName, "total")
	_chargingPriceTbl.Name = field.NewString(tableName, "name")
	_chargingPriceTbl.MinPower = field.NewFloat64(tableName, "min_power")
	_chargingPriceTbl.MaxPower = field.NewFloat64(tableName, "max_power")
	_chargingPriceTbl.Service = field.NewFloat64(tableName, "service")

	_chargingPriceTbl.fillFieldMap()

	return _chargingPriceTbl
}

// chargingPriceTbl 二轮车--电价
type chargingPriceTbl struct {
	chargingPriceTblDo chargingPriceTblDo

	ALL      field.Asterisk
	ID       field.Int32   // 电价id
	Total    field.Float64 // 单价
	Name     field.String  // 电价名称
	MinPower field.Float64 // 最小功率
	MaxPower field.Float64 // 最大功率
	Service  field.Float64 // 服务费

	fieldMap map[string]field.Expr
}

func (c chargingPriceTbl) Table(newTableName string) *chargingPriceTbl {
	c.chargingPriceTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chargingPriceTbl) As(alias string) *chargingPriceTbl {
	c.chargingPriceTblDo.DO = *(c.chargingPriceTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chargingPriceTbl) updateTableName(table string) *chargingPriceTbl {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Total = field.NewFloat64(table, "total")
	c.Name = field.NewString(table, "name")
	c.MinPower = field.NewFloat64(table, "min_power")
	c.MaxPower = field.NewFloat64(table, "max_power")
	c.Service = field.NewFloat64(table, "service")

	c.fillFieldMap()

	return c
}

func (c *chargingPriceTbl) WithContext(ctx context.Context) IChargingPriceTblDo {
	return c.chargingPriceTblDo.WithContext(ctx)
}

func (c chargingPriceTbl) TableName() string { return c.chargingPriceTblDo.TableName() }

func (c chargingPriceTbl) Alias() string { return c.chargingPriceTblDo.Alias() }

func (c chargingPriceTbl) Columns(cols ...field.Expr) gen.Columns {
	return c.chargingPriceTblDo.Columns(cols...)
}

func (c *chargingPriceTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chargingPriceTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["total"] = c.Total
	c.fieldMap["name"] = c.Name
	c.fieldMap["min_power"] = c.MinPower
	c.fieldMap["max_power"] = c.MaxPower
	c.fieldMap["service"] = c.Service
}

func (c chargingPriceTbl) clone(db *gorm.DB) chargingPriceTbl {
	c.chargingPriceTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chargingPriceTbl) replaceDB(db *gorm.DB) chargingPriceTbl {
	c.chargingPriceTblDo.ReplaceDB(db)
	return c
}

type chargingPriceTblDo struct{ gen.DO }

type IChargingPriceTblDo interface {
	gen.SubQuery
	Debug() IChargingPriceTblDo
	WithContext(ctx context.Context) IChargingPriceTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChargingPriceTblDo
	WriteDB() IChargingPriceTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChargingPriceTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChargingPriceTblDo
	Not(conds ...gen.Condition) IChargingPriceTblDo
	Or(conds ...gen.Condition) IChargingPriceTblDo
	Select(conds ...field.Expr) IChargingPriceTblDo
	Where(conds ...gen.Condition) IChargingPriceTblDo
	Order(conds ...field.Expr) IChargingPriceTblDo
	Distinct(cols ...field.Expr) IChargingPriceTblDo
	Omit(cols ...field.Expr) IChargingPriceTblDo
	Join(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo
	Group(cols ...field.Expr) IChargingPriceTblDo
	Having(conds ...gen.Condition) IChargingPriceTblDo
	Limit(limit int) IChargingPriceTblDo
	Offset(offset int) IChargingPriceTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingPriceTblDo
	Unscoped() IChargingPriceTblDo
	Create(values ...*model.ChargingPriceTbl) error
	CreateInBatches(values []*model.ChargingPriceTbl, batchSize int) error
	Save(values ...*model.ChargingPriceTbl) error
	First() (*model.ChargingPriceTbl, error)
	Take() (*model.ChargingPriceTbl, error)
	Last() (*model.ChargingPriceTbl, error)
	Find() ([]*model.ChargingPriceTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingPriceTbl, err error)
	FindInBatches(result *[]*model.ChargingPriceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChargingPriceTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChargingPriceTblDo
	Assign(attrs ...field.AssignExpr) IChargingPriceTblDo
	Joins(fields ...field.RelationField) IChargingPriceTblDo
	Preload(fields ...field.RelationField) IChargingPriceTblDo
	FirstOrInit() (*model.ChargingPriceTbl, error)
	FirstOrCreate() (*model.ChargingPriceTbl, error)
	FindByPage(offset int, limit int) (result []*model.ChargingPriceTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChargingPriceTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chargingPriceTblDo) Debug() IChargingPriceTblDo {
	return c.withDO(c.DO.Debug())
}

func (c chargingPriceTblDo) WithContext(ctx context.Context) IChargingPriceTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chargingPriceTblDo) ReadDB() IChargingPriceTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c chargingPriceTblDo) WriteDB() IChargingPriceTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c chargingPriceTblDo) Session(config *gorm.Session) IChargingPriceTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c chargingPriceTblDo) Clauses(conds ...clause.Expression) IChargingPriceTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chargingPriceTblDo) Returning(value interface{}, columns ...string) IChargingPriceTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chargingPriceTblDo) Not(conds ...gen.Condition) IChargingPriceTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chargingPriceTblDo) Or(conds ...gen.Condition) IChargingPriceTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chargingPriceTblDo) Select(conds ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chargingPriceTblDo) Where(conds ...gen.Condition) IChargingPriceTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chargingPriceTblDo) Order(conds ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chargingPriceTblDo) Distinct(cols ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chargingPriceTblDo) Omit(cols ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chargingPriceTblDo) Join(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chargingPriceTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chargingPriceTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chargingPriceTblDo) Group(cols ...field.Expr) IChargingPriceTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chargingPriceTblDo) Having(conds ...gen.Condition) IChargingPriceTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chargingPriceTblDo) Limit(limit int) IChargingPriceTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chargingPriceTblDo) Offset(offset int) IChargingPriceTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chargingPriceTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChargingPriceTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chargingPriceTblDo) Unscoped() IChargingPriceTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chargingPriceTblDo) Create(values ...*model.ChargingPriceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chargingPriceTblDo) CreateInBatches(values []*model.ChargingPriceTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chargingPriceTblDo) Save(values ...*model.ChargingPriceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chargingPriceTblDo) First() (*model.ChargingPriceTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingPriceTbl), nil
	}
}

func (c chargingPriceTblDo) Take() (*model.ChargingPriceTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingPriceTbl), nil
	}
}

func (c chargingPriceTblDo) Last() (*model.ChargingPriceTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingPriceTbl), nil
	}
}

func (c chargingPriceTblDo) Find() ([]*model.ChargingPriceTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChargingPriceTbl), err
}

func (c chargingPriceTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChargingPriceTbl, err error) {
	buf := make([]*model.ChargingPriceTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chargingPriceTblDo) FindInBatches(result *[]*model.ChargingPriceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chargingPriceTblDo) Attrs(attrs ...field.AssignExpr) IChargingPriceTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chargingPriceTblDo) Assign(attrs ...field.AssignExpr) IChargingPriceTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chargingPriceTblDo) Joins(fields ...field.RelationField) IChargingPriceTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chargingPriceTblDo) Preload(fields ...field.RelationField) IChargingPriceTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chargingPriceTblDo) FirstOrInit() (*model.ChargingPriceTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingPriceTbl), nil
	}
}

func (c chargingPriceTblDo) FirstOrCreate() (*model.ChargingPriceTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChargingPriceTbl), nil
	}
}

func (c chargingPriceTblDo) FindByPage(offset int, limit int) (result []*model.ChargingPriceTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chargingPriceTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chargingPriceTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chargingPriceTblDo) Delete(models ...*model.ChargingPriceTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chargingPriceTblDo) withDO(do gen.Dao) *chargingPriceTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
