// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newCommunityApplyTbl(db *gorm.DB, opts ...gen.DOOption) communityApplyTbl {
	_communityApplyTbl := communityApplyTbl{}

	_communityApplyTbl.communityApplyTblDo.UseDB(db, opts...)
	_communityApplyTbl.communityApplyTblDo.UseModel(&model.CommunityApplyTbl{})

	tableName := _communityApplyTbl.communityApplyTblDo.TableName()
	_communityApplyTbl.ALL = field.NewAsterisk(tableName)
	_communityApplyTbl.ID = field.NewInt32(tableName, "id")
	_communityApplyTbl.DeviceType = field.NewString(tableName, "device_type")
	_communityApplyTbl.DeviceModel = field.NewString(tableName, "device_model")
	_communityApplyTbl.UsageScenario = field.NewString(tableName, "usage_scenario")
	_communityApplyTbl.InstallationAddress = field.NewString(tableName, "installation_address")
	_communityApplyTbl.ExpectedInstallationTime = field.NewTime(tableName, "expected_installation_time")
	_communityApplyTbl.CommunityName = field.NewString(tableName, "community_name")
	_communityApplyTbl.ApplicantName = field.NewString(tableName, "applicant_name")
	_communityApplyTbl.ContactPhone = field.NewString(tableName, "contact_phone")
	_communityApplyTbl.SitePhotoID = field.NewInt32(tableName, "site_photo_id")
	_communityApplyTbl.ApplyTime = field.NewTime(tableName, "apply_time")

	_communityApplyTbl.fillFieldMap()

	return _communityApplyTbl
}

// communityApplyTbl 小区申请表
type communityApplyTbl struct {
	communityApplyTblDo communityApplyTblDo

	ALL                      field.Asterisk
	ID                       field.Int32  // 主键ID
	DeviceType               field.String // 设备类型
	DeviceModel              field.String // 设备型号
	UsageScenario            field.String // 使用场景
	InstallationAddress      field.String // 安装地址
	ExpectedInstallationTime field.Time   // 期望安装时间
	CommunityName            field.String // 小区名称
	ApplicantName            field.String // 姓名
	ContactPhone             field.String // 联系电话
	SitePhotoID              field.Int32  // 现场照片id
	ApplyTime                field.Time   // 申请时间

	fieldMap map[string]field.Expr
}

func (c communityApplyTbl) Table(newTableName string) *communityApplyTbl {
	c.communityApplyTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c communityApplyTbl) As(alias string) *communityApplyTbl {
	c.communityApplyTblDo.DO = *(c.communityApplyTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *communityApplyTbl) updateTableName(table string) *communityApplyTbl {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.DeviceType = field.NewString(table, "device_type")
	c.DeviceModel = field.NewString(table, "device_model")
	c.UsageScenario = field.NewString(table, "usage_scenario")
	c.InstallationAddress = field.NewString(table, "installation_address")
	c.ExpectedInstallationTime = field.NewTime(table, "expected_installation_time")
	c.CommunityName = field.NewString(table, "community_name")
	c.ApplicantName = field.NewString(table, "applicant_name")
	c.ContactPhone = field.NewString(table, "contact_phone")
	c.SitePhotoID = field.NewInt32(table, "site_photo_id")
	c.ApplyTime = field.NewTime(table, "apply_time")

	c.fillFieldMap()

	return c
}

func (c *communityApplyTbl) WithContext(ctx context.Context) ICommunityApplyTblDo {
	return c.communityApplyTblDo.WithContext(ctx)
}

func (c communityApplyTbl) TableName() string { return c.communityApplyTblDo.TableName() }

func (c communityApplyTbl) Alias() string { return c.communityApplyTblDo.Alias() }

func (c communityApplyTbl) Columns(cols ...field.Expr) gen.Columns {
	return c.communityApplyTblDo.Columns(cols...)
}

func (c *communityApplyTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *communityApplyTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["device_type"] = c.DeviceType
	c.fieldMap["device_model"] = c.DeviceModel
	c.fieldMap["usage_scenario"] = c.UsageScenario
	c.fieldMap["installation_address"] = c.InstallationAddress
	c.fieldMap["expected_installation_time"] = c.ExpectedInstallationTime
	c.fieldMap["community_name"] = c.CommunityName
	c.fieldMap["applicant_name"] = c.ApplicantName
	c.fieldMap["contact_phone"] = c.ContactPhone
	c.fieldMap["site_photo_id"] = c.SitePhotoID
	c.fieldMap["apply_time"] = c.ApplyTime
}

func (c communityApplyTbl) clone(db *gorm.DB) communityApplyTbl {
	c.communityApplyTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c communityApplyTbl) replaceDB(db *gorm.DB) communityApplyTbl {
	c.communityApplyTblDo.ReplaceDB(db)
	return c
}

type communityApplyTblDo struct{ gen.DO }

type ICommunityApplyTblDo interface {
	gen.SubQuery
	Debug() ICommunityApplyTblDo
	WithContext(ctx context.Context) ICommunityApplyTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommunityApplyTblDo
	WriteDB() ICommunityApplyTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommunityApplyTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommunityApplyTblDo
	Not(conds ...gen.Condition) ICommunityApplyTblDo
	Or(conds ...gen.Condition) ICommunityApplyTblDo
	Select(conds ...field.Expr) ICommunityApplyTblDo
	Where(conds ...gen.Condition) ICommunityApplyTblDo
	Order(conds ...field.Expr) ICommunityApplyTblDo
	Distinct(cols ...field.Expr) ICommunityApplyTblDo
	Omit(cols ...field.Expr) ICommunityApplyTblDo
	Join(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo
	Group(cols ...field.Expr) ICommunityApplyTblDo
	Having(conds ...gen.Condition) ICommunityApplyTblDo
	Limit(limit int) ICommunityApplyTblDo
	Offset(offset int) ICommunityApplyTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommunityApplyTblDo
	Unscoped() ICommunityApplyTblDo
	Create(values ...*model.CommunityApplyTbl) error
	CreateInBatches(values []*model.CommunityApplyTbl, batchSize int) error
	Save(values ...*model.CommunityApplyTbl) error
	First() (*model.CommunityApplyTbl, error)
	Take() (*model.CommunityApplyTbl, error)
	Last() (*model.CommunityApplyTbl, error)
	Find() ([]*model.CommunityApplyTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommunityApplyTbl, err error)
	FindInBatches(result *[]*model.CommunityApplyTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CommunityApplyTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommunityApplyTblDo
	Assign(attrs ...field.AssignExpr) ICommunityApplyTblDo
	Joins(fields ...field.RelationField) ICommunityApplyTblDo
	Preload(fields ...field.RelationField) ICommunityApplyTblDo
	FirstOrInit() (*model.CommunityApplyTbl, error)
	FirstOrCreate() (*model.CommunityApplyTbl, error)
	FindByPage(offset int, limit int) (result []*model.CommunityApplyTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommunityApplyTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c communityApplyTblDo) Debug() ICommunityApplyTblDo {
	return c.withDO(c.DO.Debug())
}

func (c communityApplyTblDo) WithContext(ctx context.Context) ICommunityApplyTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c communityApplyTblDo) ReadDB() ICommunityApplyTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c communityApplyTblDo) WriteDB() ICommunityApplyTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c communityApplyTblDo) Session(config *gorm.Session) ICommunityApplyTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c communityApplyTblDo) Clauses(conds ...clause.Expression) ICommunityApplyTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c communityApplyTblDo) Returning(value interface{}, columns ...string) ICommunityApplyTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c communityApplyTblDo) Not(conds ...gen.Condition) ICommunityApplyTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c communityApplyTblDo) Or(conds ...gen.Condition) ICommunityApplyTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c communityApplyTblDo) Select(conds ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c communityApplyTblDo) Where(conds ...gen.Condition) ICommunityApplyTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c communityApplyTblDo) Order(conds ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c communityApplyTblDo) Distinct(cols ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c communityApplyTblDo) Omit(cols ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c communityApplyTblDo) Join(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c communityApplyTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c communityApplyTblDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c communityApplyTblDo) Group(cols ...field.Expr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c communityApplyTblDo) Having(conds ...gen.Condition) ICommunityApplyTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c communityApplyTblDo) Limit(limit int) ICommunityApplyTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c communityApplyTblDo) Offset(offset int) ICommunityApplyTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c communityApplyTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommunityApplyTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c communityApplyTblDo) Unscoped() ICommunityApplyTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c communityApplyTblDo) Create(values ...*model.CommunityApplyTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c communityApplyTblDo) CreateInBatches(values []*model.CommunityApplyTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c communityApplyTblDo) Save(values ...*model.CommunityApplyTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c communityApplyTblDo) First() (*model.CommunityApplyTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommunityApplyTbl), nil
	}
}

func (c communityApplyTblDo) Take() (*model.CommunityApplyTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommunityApplyTbl), nil
	}
}

func (c communityApplyTblDo) Last() (*model.CommunityApplyTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommunityApplyTbl), nil
	}
}

func (c communityApplyTblDo) Find() ([]*model.CommunityApplyTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommunityApplyTbl), err
}

func (c communityApplyTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommunityApplyTbl, err error) {
	buf := make([]*model.CommunityApplyTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c communityApplyTblDo) FindInBatches(result *[]*model.CommunityApplyTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c communityApplyTblDo) Attrs(attrs ...field.AssignExpr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c communityApplyTblDo) Assign(attrs ...field.AssignExpr) ICommunityApplyTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c communityApplyTblDo) Joins(fields ...field.RelationField) ICommunityApplyTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c communityApplyTblDo) Preload(fields ...field.RelationField) ICommunityApplyTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c communityApplyTblDo) FirstOrInit() (*model.CommunityApplyTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommunityApplyTbl), nil
	}
}

func (c communityApplyTblDo) FirstOrCreate() (*model.CommunityApplyTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommunityApplyTbl), nil
	}
}

func (c communityApplyTblDo) FindByPage(offset int, limit int) (result []*model.CommunityApplyTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c communityApplyTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c communityApplyTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c communityApplyTblDo) Delete(models ...*model.CommunityApplyTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *communityApplyTblDo) withDO(do gen.Dao) *communityApplyTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
