// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newConfigTbl(db *gorm.DB, opts ...gen.DOOption) configTbl {
	_configTbl := configTbl{}

	_configTbl.configTblDo.UseDB(db, opts...)
	_configTbl.configTblDo.UseModel(&model.ConfigTbl{})

	tableName := _configTbl.configTblDo.TableName()
	_configTbl.ALL = field.NewAsterisk(tableName)
	_configTbl.Orderid = field.NewString(tableName, "orderid")
	_configTbl.ChargeGun = field.NewInt32(tableName, "charge_gun")
	_configTbl.CreateTime = field.NewTime(tableName, "create_time")
	_configTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_configTbl.fillFieldMap()

	return _configTbl
}

// configTbl 参数表
type configTbl struct {
	configTblDo configTblDo

	ALL        field.Asterisk
	Orderid    field.String // 订单id
	ChargeGun  field.Int32  // 开启充电枪指令是否发送:0-未发 1-已发
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c configTbl) Table(newTableName string) *configTbl {
	c.configTblDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c configTbl) As(alias string) *configTbl {
	c.configTblDo.DO = *(c.configTblDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *configTbl) updateTableName(table string) *configTbl {
	c.ALL = field.NewAsterisk(table)
	c.Orderid = field.NewString(table, "orderid")
	c.ChargeGun = field.NewInt32(table, "charge_gun")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *configTbl) WithContext(ctx context.Context) IConfigTblDo {
	return c.configTblDo.WithContext(ctx)
}

func (c configTbl) TableName() string { return c.configTblDo.TableName() }

func (c configTbl) Alias() string { return c.configTblDo.Alias() }

func (c configTbl) Columns(cols ...field.Expr) gen.Columns { return c.configTblDo.Columns(cols...) }

func (c *configTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *configTbl) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["orderid"] = c.Orderid
	c.fieldMap["charge_gun"] = c.ChargeGun
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c configTbl) clone(db *gorm.DB) configTbl {
	c.configTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c configTbl) replaceDB(db *gorm.DB) configTbl {
	c.configTblDo.ReplaceDB(db)
	return c
}

type configTblDo struct{ gen.DO }

type IConfigTblDo interface {
	gen.SubQuery
	Debug() IConfigTblDo
	WithContext(ctx context.Context) IConfigTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfigTblDo
	WriteDB() IConfigTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfigTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfigTblDo
	Not(conds ...gen.Condition) IConfigTblDo
	Or(conds ...gen.Condition) IConfigTblDo
	Select(conds ...field.Expr) IConfigTblDo
	Where(conds ...gen.Condition) IConfigTblDo
	Order(conds ...field.Expr) IConfigTblDo
	Distinct(cols ...field.Expr) IConfigTblDo
	Omit(cols ...field.Expr) IConfigTblDo
	Join(table schema.Tabler, on ...field.Expr) IConfigTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfigTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfigTblDo
	Group(cols ...field.Expr) IConfigTblDo
	Having(conds ...gen.Condition) IConfigTblDo
	Limit(limit int) IConfigTblDo
	Offset(offset int) IConfigTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigTblDo
	Unscoped() IConfigTblDo
	Create(values ...*model.ConfigTbl) error
	CreateInBatches(values []*model.ConfigTbl, batchSize int) error
	Save(values ...*model.ConfigTbl) error
	First() (*model.ConfigTbl, error)
	Take() (*model.ConfigTbl, error)
	Last() (*model.ConfigTbl, error)
	Find() ([]*model.ConfigTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigTbl, err error)
	FindInBatches(result *[]*model.ConfigTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConfigTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfigTblDo
	Assign(attrs ...field.AssignExpr) IConfigTblDo
	Joins(fields ...field.RelationField) IConfigTblDo
	Preload(fields ...field.RelationField) IConfigTblDo
	FirstOrInit() (*model.ConfigTbl, error)
	FirstOrCreate() (*model.ConfigTbl, error)
	FindByPage(offset int, limit int) (result []*model.ConfigTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfigTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c configTblDo) Debug() IConfigTblDo {
	return c.withDO(c.DO.Debug())
}

func (c configTblDo) WithContext(ctx context.Context) IConfigTblDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c configTblDo) ReadDB() IConfigTblDo {
	return c.Clauses(dbresolver.Read)
}

func (c configTblDo) WriteDB() IConfigTblDo {
	return c.Clauses(dbresolver.Write)
}

func (c configTblDo) Session(config *gorm.Session) IConfigTblDo {
	return c.withDO(c.DO.Session(config))
}

func (c configTblDo) Clauses(conds ...clause.Expression) IConfigTblDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c configTblDo) Returning(value interface{}, columns ...string) IConfigTblDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c configTblDo) Not(conds ...gen.Condition) IConfigTblDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c configTblDo) Or(conds ...gen.Condition) IConfigTblDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c configTblDo) Select(conds ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c configTblDo) Where(conds ...gen.Condition) IConfigTblDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c configTblDo) Order(conds ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c configTblDo) Distinct(cols ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c configTblDo) Omit(cols ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c configTblDo) Join(table schema.Tabler, on ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c configTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c configTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c configTblDo) Group(cols ...field.Expr) IConfigTblDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c configTblDo) Having(conds ...gen.Condition) IConfigTblDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c configTblDo) Limit(limit int) IConfigTblDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c configTblDo) Offset(offset int) IConfigTblDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c configTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigTblDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c configTblDo) Unscoped() IConfigTblDo {
	return c.withDO(c.DO.Unscoped())
}

func (c configTblDo) Create(values ...*model.ConfigTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c configTblDo) CreateInBatches(values []*model.ConfigTbl, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c configTblDo) Save(values ...*model.ConfigTbl) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c configTblDo) First() (*model.ConfigTbl, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigTbl), nil
	}
}

func (c configTblDo) Take() (*model.ConfigTbl, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigTbl), nil
	}
}

func (c configTblDo) Last() (*model.ConfigTbl, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigTbl), nil
	}
}

func (c configTblDo) Find() ([]*model.ConfigTbl, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConfigTbl), err
}

func (c configTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigTbl, err error) {
	buf := make([]*model.ConfigTbl, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c configTblDo) FindInBatches(result *[]*model.ConfigTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c configTblDo) Attrs(attrs ...field.AssignExpr) IConfigTblDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c configTblDo) Assign(attrs ...field.AssignExpr) IConfigTblDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c configTblDo) Joins(fields ...field.RelationField) IConfigTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c configTblDo) Preload(fields ...field.RelationField) IConfigTblDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c configTblDo) FirstOrInit() (*model.ConfigTbl, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigTbl), nil
	}
}

func (c configTblDo) FirstOrCreate() (*model.ConfigTbl, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigTbl), nil
	}
}

func (c configTblDo) FindByPage(offset int, limit int) (result []*model.ConfigTbl, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c configTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c configTblDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c configTblDo) Delete(models ...*model.ConfigTbl) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *configTblDo) withDO(do gen.Dao) *configTblDo {
	c.DO = *do.(*gen.DO)
	return c
}
