// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newExternalAPIApp(db *gorm.DB, opts ...gen.DOOption) externalAPIApp {
	_externalAPIApp := externalAPIApp{}

	_externalAPIApp.externalAPIAppDo.UseDB(db, opts...)
	_externalAPIApp.externalAPIAppDo.UseModel(&model.ExternalAPIApp{})

	tableName := _externalAPIApp.externalAPIAppDo.TableName()
	_externalAPIApp.ALL = field.NewAsterisk(tableName)
	_externalAPIApp.ID = field.NewInt64(tableName, "id")
	_externalAPIApp.AppKey = field.NewString(tableName, "app_key")
	_externalAPIApp.AppSecret = field.NewString(tableName, "app_secret")
	_externalAPIApp.AppName = field.NewString(tableName, "app_name")
	_externalAPIApp.Enabled = field.NewInt32(tableName, "enabled")
	_externalAPIApp.RateLimit = field.NewInt32(tableName, "rate_limit")
	_externalAPIApp.CreatedTime = field.NewTime(tableName, "created_time")
	_externalAPIApp.UpdatedTime = field.NewTime(tableName, "updated_time")
	_externalAPIApp.Deleted = field.NewInt32(tableName, "deleted")

	_externalAPIApp.fillFieldMap()

	return _externalAPIApp
}

// externalAPIApp 外部 API 应用密钥
type externalAPIApp struct {
	externalAPIAppDo externalAPIAppDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键
	AppKey      field.String // 应用标识 (AppKey), 调用方放在 X-App-Key 请求头
	AppSecret   field.String // 应用密钥 (AppSecret), 调用方用于 HMAC 签名, 绝对不能在网络传输
	AppName     field.String // 应用名称, 记录是谁在用, 方便排查
	Enabled     field.Int32  // 是否启用 1-启用 0-禁用
	RateLimit   field.Int32  // 每秒限流阈值, NULL 则使用全局默认值 (10次/秒)
	CreatedTime field.Time   // 创建时间
	UpdatedTime field.Time   // 更新时间
	Deleted     field.Int32  // 逻辑删除 0-未删除 1-已删除

	fieldMap map[string]field.Expr
}

func (e externalAPIApp) Table(newTableName string) *externalAPIApp {
	e.externalAPIAppDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e externalAPIApp) As(alias string) *externalAPIApp {
	e.externalAPIAppDo.DO = *(e.externalAPIAppDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *externalAPIApp) updateTableName(table string) *externalAPIApp {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.AppKey = field.NewString(table, "app_key")
	e.AppSecret = field.NewString(table, "app_secret")
	e.AppName = field.NewString(table, "app_name")
	e.Enabled = field.NewInt32(table, "enabled")
	e.RateLimit = field.NewInt32(table, "rate_limit")
	e.CreatedTime = field.NewTime(table, "created_time")
	e.UpdatedTime = field.NewTime(table, "updated_time")
	e.Deleted = field.NewInt32(table, "deleted")

	e.fillFieldMap()

	return e
}

func (e *externalAPIApp) WithContext(ctx context.Context) IExternalAPIAppDo {
	return e.externalAPIAppDo.WithContext(ctx)
}

func (e externalAPIApp) TableName() string { return e.externalAPIAppDo.TableName() }

func (e externalAPIApp) Alias() string { return e.externalAPIAppDo.Alias() }

func (e externalAPIApp) Columns(cols ...field.Expr) gen.Columns {
	return e.externalAPIAppDo.Columns(cols...)
}

func (e *externalAPIApp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *externalAPIApp) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["app_key"] = e.AppKey
	e.fieldMap["app_secret"] = e.AppSecret
	e.fieldMap["app_name"] = e.AppName
	e.fieldMap["enabled"] = e.Enabled
	e.fieldMap["rate_limit"] = e.RateLimit
	e.fieldMap["created_time"] = e.CreatedTime
	e.fieldMap["updated_time"] = e.UpdatedTime
	e.fieldMap["deleted"] = e.Deleted
}

func (e externalAPIApp) clone(db *gorm.DB) externalAPIApp {
	e.externalAPIAppDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e externalAPIApp) replaceDB(db *gorm.DB) externalAPIApp {
	e.externalAPIAppDo.ReplaceDB(db)
	return e
}

type externalAPIAppDo struct{ gen.DO }

type IExternalAPIAppDo interface {
	gen.SubQuery
	Debug() IExternalAPIAppDo
	WithContext(ctx context.Context) IExternalAPIAppDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExternalAPIAppDo
	WriteDB() IExternalAPIAppDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExternalAPIAppDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExternalAPIAppDo
	Not(conds ...gen.Condition) IExternalAPIAppDo
	Or(conds ...gen.Condition) IExternalAPIAppDo
	Select(conds ...field.Expr) IExternalAPIAppDo
	Where(conds ...gen.Condition) IExternalAPIAppDo
	Order(conds ...field.Expr) IExternalAPIAppDo
	Distinct(cols ...field.Expr) IExternalAPIAppDo
	Omit(cols ...field.Expr) IExternalAPIAppDo
	Join(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo
	Group(cols ...field.Expr) IExternalAPIAppDo
	Having(conds ...gen.Condition) IExternalAPIAppDo
	Limit(limit int) IExternalAPIAppDo
	Offset(offset int) IExternalAPIAppDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalAPIAppDo
	Unscoped() IExternalAPIAppDo
	Create(values ...*model.ExternalAPIApp) error
	CreateInBatches(values []*model.ExternalAPIApp, batchSize int) error
	Save(values ...*model.ExternalAPIApp) error
	First() (*model.ExternalAPIApp, error)
	Take() (*model.ExternalAPIApp, error)
	Last() (*model.ExternalAPIApp, error)
	Find() ([]*model.ExternalAPIApp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalAPIApp, err error)
	FindInBatches(result *[]*model.ExternalAPIApp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ExternalAPIApp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExternalAPIAppDo
	Assign(attrs ...field.AssignExpr) IExternalAPIAppDo
	Joins(fields ...field.RelationField) IExternalAPIAppDo
	Preload(fields ...field.RelationField) IExternalAPIAppDo
	FirstOrInit() (*model.ExternalAPIApp, error)
	FirstOrCreate() (*model.ExternalAPIApp, error)
	FindByPage(offset int, limit int) (result []*model.ExternalAPIApp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExternalAPIAppDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e externalAPIAppDo) Debug() IExternalAPIAppDo {
	return e.withDO(e.DO.Debug())
}

func (e externalAPIAppDo) WithContext(ctx context.Context) IExternalAPIAppDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e externalAPIAppDo) ReadDB() IExternalAPIAppDo {
	return e.Clauses(dbresolver.Read)
}

func (e externalAPIAppDo) WriteDB() IExternalAPIAppDo {
	return e.Clauses(dbresolver.Write)
}

func (e externalAPIAppDo) Session(config *gorm.Session) IExternalAPIAppDo {
	return e.withDO(e.DO.Session(config))
}

func (e externalAPIAppDo) Clauses(conds ...clause.Expression) IExternalAPIAppDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e externalAPIAppDo) Returning(value interface{}, columns ...string) IExternalAPIAppDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e externalAPIAppDo) Not(conds ...gen.Condition) IExternalAPIAppDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e externalAPIAppDo) Or(conds ...gen.Condition) IExternalAPIAppDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e externalAPIAppDo) Select(conds ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e externalAPIAppDo) Where(conds ...gen.Condition) IExternalAPIAppDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e externalAPIAppDo) Order(conds ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e externalAPIAppDo) Distinct(cols ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e externalAPIAppDo) Omit(cols ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e externalAPIAppDo) Join(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e externalAPIAppDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e externalAPIAppDo) RightJoin(table schema.Tabler, on ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e externalAPIAppDo) Group(cols ...field.Expr) IExternalAPIAppDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e externalAPIAppDo) Having(conds ...gen.Condition) IExternalAPIAppDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e externalAPIAppDo) Limit(limit int) IExternalAPIAppDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e externalAPIAppDo) Offset(offset int) IExternalAPIAppDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e externalAPIAppDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalAPIAppDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e externalAPIAppDo) Unscoped() IExternalAPIAppDo {
	return e.withDO(e.DO.Unscoped())
}

func (e externalAPIAppDo) Create(values ...*model.ExternalAPIApp) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e externalAPIAppDo) CreateInBatches(values []*model.ExternalAPIApp, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e externalAPIAppDo) Save(values ...*model.ExternalAPIApp) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e externalAPIAppDo) First() (*model.ExternalAPIApp, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalAPIApp), nil
	}
}

func (e externalAPIAppDo) Take() (*model.ExternalAPIApp, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalAPIApp), nil
	}
}

func (e externalAPIAppDo) Last() (*model.ExternalAPIApp, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalAPIApp), nil
	}
}

func (e externalAPIAppDo) Find() ([]*model.ExternalAPIApp, error) {
	result, err := e.DO.Find()
	return result.([]*model.ExternalAPIApp), err
}

func (e externalAPIAppDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalAPIApp, err error) {
	buf := make([]*model.ExternalAPIApp, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e externalAPIAppDo) FindInBatches(result *[]*model.ExternalAPIApp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e externalAPIAppDo) Attrs(attrs ...field.AssignExpr) IExternalAPIAppDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e externalAPIAppDo) Assign(attrs ...field.AssignExpr) IExternalAPIAppDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e externalAPIAppDo) Joins(fields ...field.RelationField) IExternalAPIAppDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e externalAPIAppDo) Preload(fields ...field.RelationField) IExternalAPIAppDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e externalAPIAppDo) FirstOrInit() (*model.ExternalAPIApp, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalAPIApp), nil
	}
}

func (e externalAPIAppDo) FirstOrCreate() (*model.ExternalAPIApp, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalAPIApp), nil
	}
}

func (e externalAPIAppDo) FindByPage(offset int, limit int) (result []*model.ExternalAPIApp, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e externalAPIAppDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e externalAPIAppDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e externalAPIAppDo) Delete(models ...*model.ExternalAPIApp) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *externalAPIAppDo) withDO(do gen.Dao) *externalAPIAppDo {
	e.DO = *do.(*gen.DO)
	return e
}
