// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newFreeChargingUsersTbl(db *gorm.DB, opts ...gen.DOOption) freeChargingUsersTbl {
	_freeChargingUsersTbl := freeChargingUsersTbl{}

	_freeChargingUsersTbl.freeChargingUsersTblDo.UseDB(db, opts...)
	_freeChargingUsersTbl.freeChargingUsersTblDo.UseModel(&model.FreeChargingUsersTbl{})

	tableName := _freeChargingUsersTbl.freeChargingUsersTblDo.TableName()
	_freeChargingUsersTbl.ALL = field.NewAsterisk(tableName)
	_freeChargingUsersTbl.ID = field.NewInt32(tableName, "id")
	_freeChargingUsersTbl.Openid = field.NewString(tableName, "openid")
	_freeChargingUsersTbl.Name = field.NewString(tableName, "name")
	_freeChargingUsersTbl.Phone = field.NewString(tableName, "phone")
	_freeChargingUsersTbl.Email = field.NewString(tableName, "email")
	_freeChargingUsersTbl.ChargingStationID = field.NewInt32(tableName, "charging_station_id")
	_freeChargingUsersTbl.StartDate = field.NewTime(tableName, "start_date")
	_freeChargingUsersTbl.EndDate = field.NewTime(tableName, "end_date")
	_freeChargingUsersTbl.Status = field.NewBool(tableName, "status")
	_freeChargingUsersTbl.CreateTime = field.NewTime(tableName, "create_time")
	_freeChargingUsersTbl.UpdateTime = field.NewTime(tableName, "update_time")
	_freeChargingUsersTbl.Reviser = field.NewString(tableName, "reviser")

	_freeChargingUsersTbl.fillFieldMap()

	return _freeChargingUsersTbl
}

// freeChargingUsersTbl 享受充电站免服务费人员信息表
type freeChargingUsersTbl struct {
	freeChargingUsersTblDo freeChargingUsersTblDo

	ALL               field.Asterisk
	ID                field.Int32  // 主键ID
	Openid            field.String // 微信用户唯一openid
	Name              field.String // 姓名
	Phone             field.String // 联系电话
	Email             field.String // 电子邮箱
	ChargingStationID field.Int32  // 充电站ID
	StartDate         field.Time   // 享受免服务费的开始日期
	EndDate           field.Time   // 享受免服务费的结束日期
	Status            field.Bool   // 状态
	CreateTime        field.Time   // 添加时间
	UpdateTime        field.Time   // 修改时间
	Reviser           field.String // 修改人

	fieldMap map[string]field.Expr
}

func (f freeChargingUsersTbl) Table(newTableName string) *freeChargingUsersTbl {
	f.freeChargingUsersTblDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f freeChargingUsersTbl) As(alias string) *freeChargingUsersTbl {
	f.freeChargingUsersTblDo.DO = *(f.freeChargingUsersTblDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *freeChargingUsersTbl) updateTableName(table string) *freeChargingUsersTbl {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.Openid = field.NewString(table, "openid")
	f.Name = field.NewString(table, "name")
	f.Phone = field.NewString(table, "phone")
	f.Email = field.NewString(table, "email")
	f.ChargingStationID = field.NewInt32(table, "charging_station_id")
	f.StartDate = field.NewTime(table, "start_date")
	f.EndDate = field.NewTime(table, "end_date")
	f.Status = field.NewBool(table, "status")
	f.CreateTime = field.NewTime(table, "create_time")
	f.UpdateTime = field.NewTime(table, "update_time")
	f.Reviser = field.NewString(table, "reviser")

	f.fillFieldMap()

	return f
}

func (f *freeChargingUsersTbl) WithContext(ctx context.Context) IFreeChargingUsersTblDo {
	return f.freeChargingUsersTblDo.WithContext(ctx)
}

func (f freeChargingUsersTbl) TableName() string { return f.freeChargingUsersTblDo.TableName() }

func (f freeChargingUsersTbl) Alias() string { return f.freeChargingUsersTblDo.Alias() }

func (f freeChargingUsersTbl) Columns(cols ...field.Expr) gen.Columns {
	return f.freeChargingUsersTblDo.Columns(cols...)
}

func (f *freeChargingUsersTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *freeChargingUsersTbl) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 12)
	f.fieldMap["id"] = f.ID
	f.fieldMap["openid"] = f.Openid
	f.fieldMap["name"] = f.Name
	f.fieldMap["phone"] = f.Phone
	f.fieldMap["email"] = f.Email
	f.fieldMap["charging_station_id"] = f.ChargingStationID
	f.fieldMap["start_date"] = f.StartDate
	f.fieldMap["end_date"] = f.EndDate
	f.fieldMap["status"] = f.Status
	f.fieldMap["create_time"] = f.CreateTime
	f.fieldMap["update_time"] = f.UpdateTime
	f.fieldMap["reviser"] = f.Reviser
}

func (f freeChargingUsersTbl) clone(db *gorm.DB) freeChargingUsersTbl {
	f.freeChargingUsersTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f freeChargingUsersTbl) replaceDB(db *gorm.DB) freeChargingUsersTbl {
	f.freeChargingUsersTblDo.ReplaceDB(db)
	return f
}

type freeChargingUsersTblDo struct{ gen.DO }

type IFreeChargingUsersTblDo interface {
	gen.SubQuery
	Debug() IFreeChargingUsersTblDo
	WithContext(ctx context.Context) IFreeChargingUsersTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFreeChargingUsersTblDo
	WriteDB() IFreeChargingUsersTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFreeChargingUsersTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFreeChargingUsersTblDo
	Not(conds ...gen.Condition) IFreeChargingUsersTblDo
	Or(conds ...gen.Condition) IFreeChargingUsersTblDo
	Select(conds ...field.Expr) IFreeChargingUsersTblDo
	Where(conds ...gen.Condition) IFreeChargingUsersTblDo
	Order(conds ...field.Expr) IFreeChargingUsersTblDo
	Distinct(cols ...field.Expr) IFreeChargingUsersTblDo
	Omit(cols ...field.Expr) IFreeChargingUsersTblDo
	Join(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo
	Group(cols ...field.Expr) IFreeChargingUsersTblDo
	Having(conds ...gen.Condition) IFreeChargingUsersTblDo
	Limit(limit int) IFreeChargingUsersTblDo
	Offset(offset int) IFreeChargingUsersTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFreeChargingUsersTblDo
	Unscoped() IFreeChargingUsersTblDo
	Create(values ...*model.FreeChargingUsersTbl) error
	CreateInBatches(values []*model.FreeChargingUsersTbl, batchSize int) error
	Save(values ...*model.FreeChargingUsersTbl) error
	First() (*model.FreeChargingUsersTbl, error)
	Take() (*model.FreeChargingUsersTbl, error)
	Last() (*model.FreeChargingUsersTbl, error)
	Find() ([]*model.FreeChargingUsersTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FreeChargingUsersTbl, err error)
	FindInBatches(result *[]*model.FreeChargingUsersTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FreeChargingUsersTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFreeChargingUsersTblDo
	Assign(attrs ...field.AssignExpr) IFreeChargingUsersTblDo
	Joins(fields ...field.RelationField) IFreeChargingUsersTblDo
	Preload(fields ...field.RelationField) IFreeChargingUsersTblDo
	FirstOrInit() (*model.FreeChargingUsersTbl, error)
	FirstOrCreate() (*model.FreeChargingUsersTbl, error)
	FindByPage(offset int, limit int) (result []*model.FreeChargingUsersTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFreeChargingUsersTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f freeChargingUsersTblDo) Debug() IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Debug())
}

func (f freeChargingUsersTblDo) WithContext(ctx context.Context) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f freeChargingUsersTblDo) ReadDB() IFreeChargingUsersTblDo {
	return f.Clauses(dbresolver.Read)
}

func (f freeChargingUsersTblDo) WriteDB() IFreeChargingUsersTblDo {
	return f.Clauses(dbresolver.Write)
}

func (f freeChargingUsersTblDo) Session(config *gorm.Session) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Session(config))
}

func (f freeChargingUsersTblDo) Clauses(conds ...clause.Expression) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f freeChargingUsersTblDo) Returning(value interface{}, columns ...string) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f freeChargingUsersTblDo) Not(conds ...gen.Condition) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f freeChargingUsersTblDo) Or(conds ...gen.Condition) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f freeChargingUsersTblDo) Select(conds ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f freeChargingUsersTblDo) Where(conds ...gen.Condition) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f freeChargingUsersTblDo) Order(conds ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f freeChargingUsersTblDo) Distinct(cols ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f freeChargingUsersTblDo) Omit(cols ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f freeChargingUsersTblDo) Join(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f freeChargingUsersTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f freeChargingUsersTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f freeChargingUsersTblDo) Group(cols ...field.Expr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f freeChargingUsersTblDo) Having(conds ...gen.Condition) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f freeChargingUsersTblDo) Limit(limit int) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f freeChargingUsersTblDo) Offset(offset int) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f freeChargingUsersTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f freeChargingUsersTblDo) Unscoped() IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Unscoped())
}

func (f freeChargingUsersTblDo) Create(values ...*model.FreeChargingUsersTbl) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f freeChargingUsersTblDo) CreateInBatches(values []*model.FreeChargingUsersTbl, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f freeChargingUsersTblDo) Save(values ...*model.FreeChargingUsersTbl) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f freeChargingUsersTblDo) First() (*model.FreeChargingUsersTbl, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FreeChargingUsersTbl), nil
	}
}

func (f freeChargingUsersTblDo) Take() (*model.FreeChargingUsersTbl, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FreeChargingUsersTbl), nil
	}
}

func (f freeChargingUsersTblDo) Last() (*model.FreeChargingUsersTbl, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FreeChargingUsersTbl), nil
	}
}

func (f freeChargingUsersTblDo) Find() ([]*model.FreeChargingUsersTbl, error) {
	result, err := f.DO.Find()
	return result.([]*model.FreeChargingUsersTbl), err
}

func (f freeChargingUsersTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FreeChargingUsersTbl, err error) {
	buf := make([]*model.FreeChargingUsersTbl, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f freeChargingUsersTblDo) FindInBatches(result *[]*model.FreeChargingUsersTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f freeChargingUsersTblDo) Attrs(attrs ...field.AssignExpr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f freeChargingUsersTblDo) Assign(attrs ...field.AssignExpr) IFreeChargingUsersTblDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f freeChargingUsersTblDo) Joins(fields ...field.RelationField) IFreeChargingUsersTblDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f freeChargingUsersTblDo) Preload(fields ...field.RelationField) IFreeChargingUsersTblDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f freeChargingUsersTblDo) FirstOrInit() (*model.FreeChargingUsersTbl, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FreeChargingUsersTbl), nil
	}
}

func (f freeChargingUsersTblDo) FirstOrCreate() (*model.FreeChargingUsersTbl, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FreeChargingUsersTbl), nil
	}
}

func (f freeChargingUsersTblDo) FindByPage(offset int, limit int) (result []*model.FreeChargingUsersTbl, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f freeChargingUsersTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f freeChargingUsersTblDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f freeChargingUsersTblDo) Delete(models ...*model.FreeChargingUsersTbl) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *freeChargingUsersTblDo) withDO(do gen.Dao) *freeChargingUsersTblDo {
	f.DO = *do.(*gen.DO)
	return f
}
