// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                            = new(Query)
	AccountPrivateTbl            *accountPrivateTbl
	AccountPublicTbl             *accountPublicTbl
	AppointmentTbl               *appointmentTbl
	ChargeMessageTbl             *chargeMessageTbl
	ChargeOrderTbl               *chargeOrderTbl
	ChargeTbl                    *chargeTbl
	ChargingPriceTbl             *chargingPriceTbl
	ChargingStateTbl             *chargingStateTbl
	ChargingStationManagementTbl *chargingStationManagementTbl
	ChargingStationTbl           *chargingStationTbl
	CommunityApplyTbl            *communityApplyTbl
	ConfigTbl                    *configTbl
	DeviceDataTbl                *deviceDataTbl
	DriveruseTbl                 *driveruseTbl
	ExternalAPIApp               *externalAPIApp
	FaultTbl                     *faultTbl
	FreeChargingUsersTbl         *freeChargingUsersTbl
	HotSearchItemTbl             *hotSearchItemTbl
	HotelProductTbl              *hotelProductTbl
	HotelStaffTbl                *hotelStaffTbl
	HotelTbl                     *hotelTbl
	ImeiTab                      *imeiTab
	Invoice                      *invoice
	InvoiceTitle                 *invoiceTitle
	LedMacTbl                    *ledMacTbl
	LedTbl                       *ledTbl
	LocalchepaiTbl               *localchepaiTbl
	LockTbl                      *lockTbl
	LockUseTbl                   *lockUseTbl
	MessageTbl                   *messageTbl
	NeighborShareUserTbl         *neighborShareUserTbl
	OmEmployee                   *omEmployee
	OpenLockTbl                  *openLockTbl
	OrderPrivateTbl              *orderPrivateTbl
	OrderTbl                     *orderTbl
	OrderTwiceTbl                *orderTwiceTbl
	OwnerTbl                     *ownerTbl
	PackageRecordTbl             *packageRecordTbl
	PlaceTbl                     *placeTbl
	PlaceapplyTbl                *placeapplyTbl
	PlatformTbl                  *platformTbl
	PointTbl                     *pointTbl
	PrivateChargingPriceTbl      *privateChargingPriceTbl
	PrivateChargingTbl           *privateChargingTbl
	PrivatePlaceTbl              *privatePlaceTbl
	PurchasePoleApplicationTbl   *purchasePoleApplicationTbl
	ReOrderElectronicTbl         *reOrderElectronicTbl
	ReceptaclePowerTbl           *receptaclePowerTbl
	ReceptacleTbl                *receptacleTbl
	RechargeOrderTbl             *rechargeOrderTbl
	RechargeOrderTblSorted       *rechargeOrderTblSorted
	SaveyytimeTbl                *saveyytimeTbl
	ShopStaffTbl                 *shopStaffTbl
	ShopTbl                      *shopTbl
	StaffTbl                     *staffTbl
	SystemTbl                    *systemTbl
	TabBalanceRecord             *tabBalanceRecord
	TabChargingGun               *tabChargingGun
	TabGateway                   *tabGateway
	TabImage                     *tabImage
	TabOrderElectronic           *tabOrderElectronic
	TabParkingSpace              *tabParkingSpace
	TabPrice                     *tabPrice
	TabPriceTime                 *tabPriceTime
	TabPriceTimeSpring           *tabPriceTimeSpring
	TabPriceTimeSummer           *tabPriceTimeSummer
	TabPriceTimeWinter           *tabPriceTimeWinter
	TabProduct                   *tabProduct
	TabProfitSharingConfig       *tabProfitSharingConfig
	TabVideo                     *tabVideo
	TabVideoWatchRecord          *tabVideoWatchRecord
	UserBankCardTbl              *userBankCardTbl
	UserBluetoothBindingsTbl     *userBluetoothBindingsTbl
	UserShopTbl                  *userShopTbl
	UserTbl                      *userTbl
	UsercarTbl                   *usercarTbl
	UsermessageTbl               *usermessageTbl
	VersionTbl                   *versionTbl
	WangguanTbl                  *wangguanTbl
	WithdrawalRecordTbl          *withdrawalRecordTbl
	ZbbArea                      *zbbArea
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AccountPrivateTbl = &Q.AccountPrivateTbl
	AccountPublicTbl = &Q.AccountPublicTbl
	AppointmentTbl = &Q.AppointmentTbl
	ChargeMessageTbl = &Q.ChargeMessageTbl
	ChargeOrderTbl = &Q.ChargeOrderTbl
	ChargeTbl = &Q.ChargeTbl
	ChargingPriceTbl = &Q.ChargingPriceTbl
	ChargingStateTbl = &Q.ChargingStateTbl
	ChargingStationManagementTbl = &Q.ChargingStationManagementTbl
	ChargingStationTbl = &Q.ChargingStationTbl
	CommunityApplyTbl = &Q.CommunityApplyTbl
	ConfigTbl = &Q.ConfigTbl
	DeviceDataTbl = &Q.DeviceDataTbl
	DriveruseTbl = &Q.DriveruseTbl
	ExternalAPIApp = &Q.ExternalAPIApp
	FaultTbl = &Q.FaultTbl
	FreeChargingUsersTbl = &Q.FreeChargingUsersTbl
	HotSearchItemTbl = &Q.HotSearchItemTbl
	HotelProductTbl = &Q.HotelProductTbl
	HotelStaffTbl = &Q.HotelStaffTbl
	HotelTbl = &Q.HotelTbl
	ImeiTab = &Q.ImeiTab
	Invoice = &Q.Invoice
	InvoiceTitle = &Q.InvoiceTitle
	LedMacTbl = &Q.LedMacTbl
	LedTbl = &Q.LedTbl
	LocalchepaiTbl = &Q.LocalchepaiTbl
	LockTbl = &Q.LockTbl
	LockUseTbl = &Q.LockUseTbl
	MessageTbl = &Q.MessageTbl
	NeighborShareUserTbl = &Q.NeighborShareUserTbl
	OmEmployee = &Q.OmEmployee
	OpenLockTbl = &Q.OpenLockTbl
	OrderPrivateTbl = &Q.OrderPrivateTbl
	OrderTbl = &Q.OrderTbl
	OrderTwiceTbl = &Q.OrderTwiceTbl
	OwnerTbl = &Q.OwnerTbl
	PackageRecordTbl = &Q.PackageRecordTbl
	PlaceTbl = &Q.PlaceTbl
	PlaceapplyTbl = &Q.PlaceapplyTbl
	PlatformTbl = &Q.PlatformTbl
	PointTbl = &Q.PointTbl
	PrivateChargingPriceTbl = &Q.PrivateChargingPriceTbl
	PrivateChargingTbl = &Q.PrivateChargingTbl
	PrivatePlaceTbl = &Q.PrivatePlaceTbl
	PurchasePoleApplicationTbl = &Q.PurchasePoleApplicationTbl
	ReOrderElectronicTbl = &Q.ReOrderElectronicTbl
	ReceptaclePowerTbl = &Q.ReceptaclePowerTbl
	ReceptacleTbl = &Q.ReceptacleTbl
	RechargeOrderTbl = &Q.RechargeOrderTbl
	RechargeOrderTblSorted = &Q.RechargeOrderTblSorted
	SaveyytimeTbl = &Q.SaveyytimeTbl
	ShopStaffTbl = &Q.ShopStaffTbl
	ShopTbl = &Q.ShopTbl
	StaffTbl = &Q.StaffTbl
	SystemTbl = &Q.SystemTbl
	TabBalanceRecord = &Q.TabBalanceRecord
	TabChargingGun = &Q.TabChargingGun
	TabGateway = &Q.TabGateway
	TabImage = &Q.TabImage
	TabOrderElectronic = &Q.TabOrderElectronic
	TabParkingSpace = &Q.TabParkingSpace
	TabPrice = &Q.TabPrice
	TabPriceTime = &Q.TabPriceTime
	TabPriceTimeSpring = &Q.TabPriceTimeSpring
	TabPriceTimeSummer = &Q.TabPriceTimeSummer
	TabPriceTimeWinter = &Q.TabPriceTimeWinter
	TabProduct = &Q.TabProduct
	TabProfitSharingConfig = &Q.TabProfitSharingConfig
	TabVideo = &Q.TabVideo
	TabVideoWatchRecord = &Q.TabVideoWatchRecord
	UserBankCardTbl = &Q.UserBankCardTbl
	UserBluetoothBindingsTbl = &Q.UserBluetoothBindingsTbl
	UserShopTbl = &Q.UserShopTbl
	UserTbl = &Q.UserTbl
	UsercarTbl = &Q.UsercarTbl
	UsermessageTbl = &Q.UsermessageTbl
	VersionTbl = &Q.VersionTbl
	WangguanTbl = &Q.WangguanTbl
	WithdrawalRecordTbl = &Q.WithdrawalRecordTbl
	ZbbArea = &Q.ZbbArea
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                           db,
		AccountPrivateTbl:            newAccountPrivateTbl(db, opts...),
		AccountPublicTbl:             newAccountPublicTbl(db, opts...),
		AppointmentTbl:               newAppointmentTbl(db, opts...),
		ChargeMessageTbl:             newChargeMessageTbl(db, opts...),
		ChargeOrderTbl:               newChargeOrderTbl(db, opts...),
		ChargeTbl:                    newChargeTbl(db, opts...),
		ChargingPriceTbl:             newChargingPriceTbl(db, opts...),
		ChargingStateTbl:             newChargingStateTbl(db, opts...),
		ChargingStationManagementTbl: newChargingStationManagementTbl(db, opts...),
		ChargingStationTbl:           newChargingStationTbl(db, opts...),
		CommunityApplyTbl:            newCommunityApplyTbl(db, opts...),
		ConfigTbl:                    newConfigTbl(db, opts...),
		DeviceDataTbl:                newDeviceDataTbl(db, opts...),
		DriveruseTbl:                 newDriveruseTbl(db, opts...),
		ExternalAPIApp:               newExternalAPIApp(db, opts...),
		FaultTbl:                     newFaultTbl(db, opts...),
		FreeChargingUsersTbl:         newFreeChargingUsersTbl(db, opts...),
		HotSearchItemTbl:             newHotSearchItemTbl(db, opts...),
		HotelProductTbl:              newHotelProductTbl(db, opts...),
		HotelStaffTbl:                newHotelStaffTbl(db, opts...),
		HotelTbl:                     newHotelTbl(db, opts...),
		ImeiTab:                      newImeiTab(db, opts...),
		Invoice:                      newInvoice(db, opts...),
		InvoiceTitle:                 newInvoiceTitle(db, opts...),
		LedMacTbl:                    newLedMacTbl(db, opts...),
		LedTbl:                       newLedTbl(db, opts...),
		LocalchepaiTbl:               newLocalchepaiTbl(db, opts...),
		LockTbl:                      newLockTbl(db, opts...),
		LockUseTbl:                   newLockUseTbl(db, opts...),
		MessageTbl:                   newMessageTbl(db, opts...),
		NeighborShareUserTbl:         newNeighborShareUserTbl(db, opts...),
		OmEmployee:                   newOmEmployee(db, opts...),
		OpenLockTbl:                  newOpenLockTbl(db, opts...),
		OrderPrivateTbl:              newOrderPrivateTbl(db, opts...),
		OrderTbl:                     newOrderTbl(db, opts...),
		OrderTwiceTbl:                newOrderTwiceTbl(db, opts...),
		OwnerTbl:                     newOwnerTbl(db, opts...),
		PackageRecordTbl:             newPackageRecordTbl(db, opts...),
		PlaceTbl:                     newPlaceTbl(db, opts...),
		PlaceapplyTbl:                newPlaceapplyTbl(db, opts...),
		PlatformTbl:                  newPlatformTbl(db, opts...),
		PointTbl:                     newPointTbl(db, opts...),
		PrivateChargingPriceTbl:      newPrivateChargingPriceTbl(db, opts...),
		PrivateChargingTbl:           newPrivateChargingTbl(db, opts...),
		PrivatePlaceTbl:              newPrivatePlaceTbl(db, opts...),
		PurchasePoleApplicationTbl:   newPurchasePoleApplicationTbl(db, opts...),
		ReOrderElectronicTbl:         newReOrderElectronicTbl(db, opts...),
		ReceptaclePowerTbl:           newReceptaclePowerTbl(db, opts...),
		ReceptacleTbl:                newReceptacleTbl(db, opts...),
		RechargeOrderTbl:             newRechargeOrderTbl(db, opts...),
		RechargeOrderTblSorted:       newRechargeOrderTblSorted(db, opts...),
		SaveyytimeTbl:                newSaveyytimeTbl(db, opts...),
		ShopStaffTbl:                 newShopStaffTbl(db, opts...),
		ShopTbl:                      newShopTbl(db, opts...),
		StaffTbl:                     newStaffTbl(db, opts...),
		SystemTbl:                    newSystemTbl(db, opts...),
		TabBalanceRecord:             newTabBalanceRecord(db, opts...),
		TabChargingGun:               newTabChargingGun(db, opts...),
		TabGateway:                   newTabGateway(db, opts...),
		TabImage:                     newTabImage(db, opts...),
		TabOrderElectronic:           newTabOrderElectronic(db, opts...),
		TabParkingSpace:              newTabParkingSpace(db, opts...),
		TabPrice:                     newTabPrice(db, opts...),
		TabPriceTime:                 newTabPriceTime(db, opts...),
		TabPriceTimeSpring:           newTabPriceTimeSpring(db, opts...),
		TabPriceTimeSummer:           newTabPriceTimeSummer(db, opts...),
		TabPriceTimeWinter:           newTabPriceTimeWinter(db, opts...),
		TabProduct:                   newTabProduct(db, opts...),
		TabProfitSharingConfig:       newTabProfitSharingConfig(db, opts...),
		TabVideo:                     newTabVideo(db, opts...),
		TabVideoWatchRecord:          newTabVideoWatchRecord(db, opts...),
		UserBankCardTbl:              newUserBankCardTbl(db, opts...),
		UserBluetoothBindingsTbl:     newUserBluetoothBindingsTbl(db, opts...),
		UserShopTbl:                  newUserShopTbl(db, opts...),
		UserTbl:                      newUserTbl(db, opts...),
		UsercarTbl:                   newUsercarTbl(db, opts...),
		UsermessageTbl:               newUsermessageTbl(db, opts...),
		VersionTbl:                   newVersionTbl(db, opts...),
		WangguanTbl:                  newWangguanTbl(db, opts...),
		WithdrawalRecordTbl:          newWithdrawalRecordTbl(db, opts...),
		ZbbArea:                      newZbbArea(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AccountPrivateTbl            accountPrivateTbl
	AccountPublicTbl             accountPublicTbl
	AppointmentTbl               appointmentTbl
	ChargeMessageTbl             chargeMessageTbl
	ChargeOrderTbl               chargeOrderTbl
	ChargeTbl                    chargeTbl
	ChargingPriceTbl             chargingPriceTbl
	ChargingStateTbl             chargingStateTbl
	ChargingStationManagementTbl chargingStationManagementTbl
	ChargingStationTbl           chargingStationTbl
	CommunityApplyTbl            communityApplyTbl
	ConfigTbl                    configTbl
	DeviceDataTbl                deviceDataTbl
	DriveruseTbl                 driveruseTbl
	ExternalAPIApp               externalAPIApp
	FaultTbl                     faultTbl
	FreeChargingUsersTbl         freeChargingUsersTbl
	HotSearchItemTbl             hotSearchItemTbl
	HotelProductTbl              hotelProductTbl
	HotelStaffTbl                hotelStaffTbl
	HotelTbl                     hotelTbl
	ImeiTab                      imeiTab
	Invoice                      invoice
	InvoiceTitle                 invoiceTitle
	LedMacTbl                    ledMacTbl
	LedTbl                       ledTbl
	LocalchepaiTbl               localchepaiTbl
	LockTbl                      lockTbl
	LockUseTbl                   lockUseTbl
	MessageTbl                   messageTbl
	NeighborShareUserTbl         neighborShareUserTbl
	OmEmployee                   omEmployee
	OpenLockTbl                  openLockTbl
	OrderPrivateTbl              orderPrivateTbl
	OrderTbl                     orderTbl
	OrderTwiceTbl                orderTwiceTbl
	OwnerTbl                     ownerTbl
	PackageRecordTbl             packageRecordTbl
	PlaceTbl                     placeTbl
	PlaceapplyTbl                placeapplyTbl
	PlatformTbl                  platformTbl
	PointTbl                     pointTbl
	PrivateChargingPriceTbl      privateChargingPriceTbl
	PrivateChargingTbl           privateChargingTbl
	PrivatePlaceTbl              privatePlaceTbl
	PurchasePoleApplicationTbl   purchasePoleApplicationTbl
	ReOrderElectronicTbl         reOrderElectronicTbl
	ReceptaclePowerTbl           receptaclePowerTbl
	ReceptacleTbl                receptacleTbl
	RechargeOrderTbl             rechargeOrderTbl
	RechargeOrderTblSorted       rechargeOrderTblSorted
	SaveyytimeTbl                saveyytimeTbl
	ShopStaffTbl                 shopStaffTbl
	ShopTbl                      shopTbl
	StaffTbl                     staffTbl
	SystemTbl                    systemTbl
	TabBalanceRecord             tabBalanceRecord
	TabChargingGun               tabChargingGun
	TabGateway                   tabGateway
	TabImage                     tabImage
	TabOrderElectronic           tabOrderElectronic
	TabParkingSpace              tabParkingSpace
	TabPrice                     tabPrice
	TabPriceTime                 tabPriceTime
	TabPriceTimeSpring           tabPriceTimeSpring
	TabPriceTimeSummer           tabPriceTimeSummer
	TabPriceTimeWinter           tabPriceTimeWinter
	TabProduct                   tabProduct
	TabProfitSharingConfig       tabProfitSharingConfig
	TabVideo                     tabVideo
	TabVideoWatchRecord          tabVideoWatchRecord
	UserBankCardTbl              userBankCardTbl
	UserBluetoothBindingsTbl     userBluetoothBindingsTbl
	UserShopTbl                  userShopTbl
	UserTbl                      userTbl
	UsercarTbl                   usercarTbl
	UsermessageTbl               usermessageTbl
	VersionTbl                   versionTbl
	WangguanTbl                  wangguanTbl
	WithdrawalRecordTbl          withdrawalRecordTbl
	ZbbArea                      zbbArea
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                           db,
		AccountPrivateTbl:            q.AccountPrivateTbl.clone(db),
		AccountPublicTbl:             q.AccountPublicTbl.clone(db),
		AppointmentTbl:               q.AppointmentTbl.clone(db),
		ChargeMessageTbl:             q.ChargeMessageTbl.clone(db),
		ChargeOrderTbl:               q.ChargeOrderTbl.clone(db),
		ChargeTbl:                    q.ChargeTbl.clone(db),
		ChargingPriceTbl:             q.ChargingPriceTbl.clone(db),
		ChargingStateTbl:             q.ChargingStateTbl.clone(db),
		ChargingStationManagementTbl: q.ChargingStationManagementTbl.clone(db),
		ChargingStationTbl:           q.ChargingStationTbl.clone(db),
		CommunityApplyTbl:            q.CommunityApplyTbl.clone(db),
		ConfigTbl:                    q.ConfigTbl.clone(db),
		DeviceDataTbl:                q.DeviceDataTbl.clone(db),
		DriveruseTbl:                 q.DriveruseTbl.clone(db),
		ExternalAPIApp:               q.ExternalAPIApp.clone(db),
		FaultTbl:                     q.FaultTbl.clone(db),
		FreeChargingUsersTbl:         q.FreeChargingUsersTbl.clone(db),
		HotSearchItemTbl:             q.HotSearchItemTbl.clone(db),
		HotelProductTbl:              q.HotelProductTbl.clone(db),
		HotelStaffTbl:                q.HotelStaffTbl.clone(db),
		HotelTbl:                     q.HotelTbl.clone(db),
		ImeiTab:                      q.ImeiTab.clone(db),
		Invoice:                      q.Invoice.clone(db),
		InvoiceTitle:                 q.InvoiceTitle.clone(db),
		LedMacTbl:                    q.LedMacTbl.clone(db),
		LedTbl:                       q.LedTbl.clone(db),
		LocalchepaiTbl:               q.LocalchepaiTbl.clone(db),
		LockTbl:                      q.LockTbl.clone(db),
		LockUseTbl:                   q.LockUseTbl.clone(db),
		MessageTbl:                   q.MessageTbl.clone(db),
		NeighborShareUserTbl:         q.NeighborShareUserTbl.clone(db),
		OmEmployee:                   q.OmEmployee.clone(db),
		OpenLockTbl:                  q.OpenLockTbl.clone(db),
		OrderPrivateTbl:              q.OrderPrivateTbl.clone(db),
		OrderTbl:                     q.OrderTbl.clone(db),
		OrderTwiceTbl:                q.OrderTwiceTbl.clone(db),
		OwnerTbl:                     q.OwnerTbl.clone(db),
		PackageRecordTbl:             q.PackageRecordTbl.clone(db),
		PlaceTbl:                     q.PlaceTbl.clone(db),
		PlaceapplyTbl:                q.PlaceapplyTbl.clone(db),
		PlatformTbl:                  q.PlatformTbl.clone(db),
		PointTbl:                     q.PointTbl.clone(db),
		PrivateChargingPriceTbl:      q.PrivateChargingPriceTbl.clone(db),
		PrivateChargingTbl:           q.PrivateChargingTbl.clone(db),
		PrivatePlaceTbl:              q.PrivatePlaceTbl.clone(db),
		PurchasePoleApplicationTbl:   q.PurchasePoleApplicationTbl.clone(db),
		ReOrderElectronicTbl:         q.ReOrderElectronicTbl.clone(db),
		ReceptaclePowerTbl:           q.ReceptaclePowerTbl.clone(db),
		ReceptacleTbl:                q.ReceptacleTbl.clone(db),
		RechargeOrderTbl:             q.RechargeOrderTbl.clone(db),
		RechargeOrderTblSorted:       q.RechargeOrderTblSorted.clone(db),
		SaveyytimeTbl:                q.SaveyytimeTbl.clone(db),
		ShopStaffTbl:                 q.ShopStaffTbl.clone(db),
		ShopTbl:                      q.ShopTbl.clone(db),
		StaffTbl:                     q.StaffTbl.clone(db),
		SystemTbl:                    q.SystemTbl.clone(db),
		TabBalanceRecord:             q.TabBalanceRecord.clone(db),
		TabChargingGun:               q.TabChargingGun.clone(db),
		TabGateway:                   q.TabGateway.clone(db),
		TabImage:                     q.TabImage.clone(db),
		TabOrderElectronic:           q.TabOrderElectronic.clone(db),
		TabParkingSpace:              q.TabParkingSpace.clone(db),
		TabPrice:                     q.TabPrice.clone(db),
		TabPriceTime:                 q.TabPriceTime.clone(db),
		TabPriceTimeSpring:           q.TabPriceTimeSpring.clone(db),
		TabPriceTimeSummer:           q.TabPriceTimeSummer.clone(db),
		TabPriceTimeWinter:           q.TabPriceTimeWinter.clone(db),
		TabProduct:                   q.TabProduct.clone(db),
		TabProfitSharingConfig:       q.TabProfitSharingConfig.clone(db),
		TabVideo:                     q.TabVideo.clone(db),
		TabVideoWatchRecord:          q.TabVideoWatchRecord.clone(db),
		UserBankCardTbl:              q.UserBankCardTbl.clone(db),
		UserBluetoothBindingsTbl:     q.UserBluetoothBindingsTbl.clone(db),
		UserShopTbl:                  q.UserShopTbl.clone(db),
		UserTbl:                      q.UserTbl.clone(db),
		UsercarTbl:                   q.UsercarTbl.clone(db),
		UsermessageTbl:               q.UsermessageTbl.clone(db),
		VersionTbl:                   q.VersionTbl.clone(db),
		WangguanTbl:                  q.WangguanTbl.clone(db),
		WithdrawalRecordTbl:          q.WithdrawalRecordTbl.clone(db),
		ZbbArea:                      q.ZbbArea.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                           db,
		AccountPrivateTbl:            q.AccountPrivateTbl.replaceDB(db),
		AccountPublicTbl:             q.AccountPublicTbl.replaceDB(db),
		AppointmentTbl:               q.AppointmentTbl.replaceDB(db),
		ChargeMessageTbl:             q.ChargeMessageTbl.replaceDB(db),
		ChargeOrderTbl:               q.ChargeOrderTbl.replaceDB(db),
		ChargeTbl:                    q.ChargeTbl.replaceDB(db),
		ChargingPriceTbl:             q.ChargingPriceTbl.replaceDB(db),
		ChargingStateTbl:             q.ChargingStateTbl.replaceDB(db),
		ChargingStationManagementTbl: q.ChargingStationManagementTbl.replaceDB(db),
		ChargingStationTbl:           q.ChargingStationTbl.replaceDB(db),
		CommunityApplyTbl:            q.CommunityApplyTbl.replaceDB(db),
		ConfigTbl:                    q.ConfigTbl.replaceDB(db),
		DeviceDataTbl:                q.DeviceDataTbl.replaceDB(db),
		DriveruseTbl:                 q.DriveruseTbl.replaceDB(db),
		ExternalAPIApp:               q.ExternalAPIApp.replaceDB(db),
		FaultTbl:                     q.FaultTbl.replaceDB(db),
		FreeChargingUsersTbl:         q.FreeChargingUsersTbl.replaceDB(db),
		HotSearchItemTbl:             q.HotSearchItemTbl.replaceDB(db),
		HotelProductTbl:              q.HotelProductTbl.replaceDB(db),
		HotelStaffTbl:                q.HotelStaffTbl.replaceDB(db),
		HotelTbl:                     q.HotelTbl.replaceDB(db),
		ImeiTab:                      q.ImeiTab.replaceDB(db),
		Invoice:                      q.Invoice.replaceDB(db),
		InvoiceTitle:                 q.InvoiceTitle.replaceDB(db),
		LedMacTbl:                    q.LedMacTbl.replaceDB(db),
		LedTbl:                       q.LedTbl.replaceDB(db),
		LocalchepaiTbl:               q.LocalchepaiTbl.replaceDB(db),
		LockTbl:                      q.LockTbl.replaceDB(db),
		LockUseTbl:                   q.LockUseTbl.replaceDB(db),
		MessageTbl:                   q.MessageTbl.replaceDB(db),
		NeighborShareUserTbl:         q.NeighborShareUserTbl.replaceDB(db),
		OmEmployee:                   q.OmEmployee.replaceDB(db),
		OpenLockTbl:                  q.OpenLockTbl.replaceDB(db),
		OrderPrivateTbl:              q.OrderPrivateTbl.replaceDB(db),
		OrderTbl:                     q.OrderTbl.replaceDB(db),
		OrderTwiceTbl:                q.OrderTwiceTbl.replaceDB(db),
		OwnerTbl:                     q.OwnerTbl.replaceDB(db),
		PackageRecordTbl:             q.PackageRecordTbl.replaceDB(db),
		PlaceTbl:                     q.PlaceTbl.replaceDB(db),
		PlaceapplyTbl:                q.PlaceapplyTbl.replaceDB(db),
		PlatformTbl:                  q.PlatformTbl.replaceDB(db),
		PointTbl:                     q.PointTbl.replaceDB(db),
		PrivateChargingPriceTbl:      q.PrivateChargingPriceTbl.replaceDB(db),
		PrivateChargingTbl:           q.PrivateChargingTbl.replaceDB(db),
		PrivatePlaceTbl:              q.PrivatePlaceTbl.replaceDB(db),
		PurchasePoleApplicationTbl:   q.PurchasePoleApplicationTbl.replaceDB(db),
		ReOrderElectronicTbl:         q.ReOrderElectronicTbl.replaceDB(db),
		ReceptaclePowerTbl:           q.ReceptaclePowerTbl.replaceDB(db),
		ReceptacleTbl:                q.ReceptacleTbl.replaceDB(db),
		RechargeOrderTbl:             q.RechargeOrderTbl.replaceDB(db),
		RechargeOrderTblSorted:       q.RechargeOrderTblSorted.replaceDB(db),
		SaveyytimeTbl:                q.SaveyytimeTbl.replaceDB(db),
		ShopStaffTbl:                 q.ShopStaffTbl.replaceDB(db),
		ShopTbl:                      q.ShopTbl.replaceDB(db),
		StaffTbl:                     q.StaffTbl.replaceDB(db),
		SystemTbl:                    q.SystemTbl.replaceDB(db),
		TabBalanceRecord:             q.TabBalanceRecord.replaceDB(db),
		TabChargingGun:               q.TabChargingGun.replaceDB(db),
		TabGateway:                   q.TabGateway.replaceDB(db),
		TabImage:                     q.TabImage.replaceDB(db),
		TabOrderElectronic:           q.TabOrderElectronic.replaceDB(db),
		TabParkingSpace:              q.TabParkingSpace.replaceDB(db),
		TabPrice:                     q.TabPrice.replaceDB(db),
		TabPriceTime:                 q.TabPriceTime.replaceDB(db),
		TabPriceTimeSpring:           q.TabPriceTimeSpring.replaceDB(db),
		TabPriceTimeSummer:           q.TabPriceTimeSummer.replaceDB(db),
		TabPriceTimeWinter:           q.TabPriceTimeWinter.replaceDB(db),
		TabProduct:                   q.TabProduct.replaceDB(db),
		TabProfitSharingConfig:       q.TabProfitSharingConfig.replaceDB(db),
		TabVideo:                     q.TabVideo.replaceDB(db),
		TabVideoWatchRecord:          q.TabVideoWatchRecord.replaceDB(db),
		UserBankCardTbl:              q.UserBankCardTbl.replaceDB(db),
		UserBluetoothBindingsTbl:     q.UserBluetoothBindingsTbl.replaceDB(db),
		UserShopTbl:                  q.UserShopTbl.replaceDB(db),
		UserTbl:                      q.UserTbl.replaceDB(db),
		UsercarTbl:                   q.UsercarTbl.replaceDB(db),
		UsermessageTbl:               q.UsermessageTbl.replaceDB(db),
		VersionTbl:                   q.VersionTbl.replaceDB(db),
		WangguanTbl:                  q.WangguanTbl.replaceDB(db),
		WithdrawalRecordTbl:          q.WithdrawalRecordTbl.replaceDB(db),
		ZbbArea:                      q.ZbbArea.replaceDB(db),
	}
}

type queryCtx struct {
	AccountPrivateTbl            IAccountPrivateTblDo
	AccountPublicTbl             IAccountPublicTblDo
	AppointmentTbl               IAppointmentTblDo
	ChargeMessageTbl             IChargeMessageTblDo
	ChargeOrderTbl               IChargeOrderTblDo
	ChargeTbl                    IChargeTblDo
	ChargingPriceTbl             IChargingPriceTblDo
	ChargingStateTbl             IChargingStateTblDo
	ChargingStationManagementTbl IChargingStationManagementTblDo
	ChargingStationTbl           IChargingStationTblDo
	CommunityApplyTbl            ICommunityApplyTblDo
	ConfigTbl                    IConfigTblDo
	DeviceDataTbl                IDeviceDataTblDo
	DriveruseTbl                 IDriveruseTblDo
	ExternalAPIApp               IExternalAPIAppDo
	FaultTbl                     IFaultTblDo
	FreeChargingUsersTbl         IFreeChargingUsersTblDo
	HotSearchItemTbl             IHotSearchItemTblDo
	HotelProductTbl              IHotelProductTblDo
	HotelStaffTbl                IHotelStaffTblDo
	HotelTbl                     IHotelTblDo
	ImeiTab                      IImeiTabDo
	Invoice                      IInvoiceDo
	InvoiceTitle                 IInvoiceTitleDo
	LedMacTbl                    ILedMacTblDo
	LedTbl                       ILedTblDo
	LocalchepaiTbl               ILocalchepaiTblDo
	LockTbl                      ILockTblDo
	LockUseTbl                   ILockUseTblDo
	MessageTbl                   IMessageTblDo
	NeighborShareUserTbl         INeighborShareUserTblDo
	OmEmployee                   IOmEmployeeDo
	OpenLockTbl                  IOpenLockTblDo
	OrderPrivateTbl              IOrderPrivateTblDo
	OrderTbl                     IOrderTblDo
	OrderTwiceTbl                IOrderTwiceTblDo
	OwnerTbl                     IOwnerTblDo
	PackageRecordTbl             IPackageRecordTblDo
	PlaceTbl                     IPlaceTblDo
	PlaceapplyTbl                IPlaceapplyTblDo
	PlatformTbl                  IPlatformTblDo
	PointTbl                     IPointTblDo
	PrivateChargingPriceTbl      IPrivateChargingPriceTblDo
	PrivateChargingTbl           IPrivateChargingTblDo
	PrivatePlaceTbl              IPrivatePlaceTblDo
	PurchasePoleApplicationTbl   IPurchasePoleApplicationTblDo
	ReOrderElectronicTbl         IReOrderElectronicTblDo
	ReceptaclePowerTbl           IReceptaclePowerTblDo
	ReceptacleTbl                IReceptacleTblDo
	RechargeOrderTbl             IRechargeOrderTblDo
	RechargeOrderTblSorted       IRechargeOrderTblSortedDo
	SaveyytimeTbl                ISaveyytimeTblDo
	ShopStaffTbl                 IShopStaffTblDo
	ShopTbl                      IShopTblDo
	StaffTbl                     IStaffTblDo
	SystemTbl                    ISystemTblDo
	TabBalanceRecord             ITabBalanceRecordDo
	TabChargingGun               ITabChargingGunDo
	TabGateway                   ITabGatewayDo
	TabImage                     ITabImageDo
	TabOrderElectronic           ITabOrderElectronicDo
	TabParkingSpace              ITabParkingSpaceDo
	TabPrice                     ITabPriceDo
	TabPriceTime                 ITabPriceTimeDo
	TabPriceTimeSpring           ITabPriceTimeSpringDo
	TabPriceTimeSummer           ITabPriceTimeSummerDo
	TabPriceTimeWinter           ITabPriceTimeWinterDo
	TabProduct                   ITabProductDo
	TabProfitSharingConfig       ITabProfitSharingConfigDo
	TabVideo                     ITabVideoDo
	TabVideoWatchRecord          ITabVideoWatchRecordDo
	UserBankCardTbl              IUserBankCardTblDo
	UserBluetoothBindingsTbl     IUserBluetoothBindingsTblDo
	UserShopTbl                  IUserShopTblDo
	UserTbl                      IUserTblDo
	UsercarTbl                   IUsercarTblDo
	UsermessageTbl               IUsermessageTblDo
	VersionTbl                   IVersionTblDo
	WangguanTbl                  IWangguanTblDo
	WithdrawalRecordTbl          IWithdrawalRecordTblDo
	ZbbArea                      IZbbAreaDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AccountPrivateTbl:            q.AccountPrivateTbl.WithContext(ctx),
		AccountPublicTbl:             q.AccountPublicTbl.WithContext(ctx),
		AppointmentTbl:               q.AppointmentTbl.WithContext(ctx),
		ChargeMessageTbl:             q.ChargeMessageTbl.WithContext(ctx),
		ChargeOrderTbl:               q.ChargeOrderTbl.WithContext(ctx),
		ChargeTbl:                    q.ChargeTbl.WithContext(ctx),
		ChargingPriceTbl:             q.ChargingPriceTbl.WithContext(ctx),
		ChargingStateTbl:             q.ChargingStateTbl.WithContext(ctx),
		ChargingStationManagementTbl: q.ChargingStationManagementTbl.WithContext(ctx),
		ChargingStationTbl:           q.ChargingStationTbl.WithContext(ctx),
		CommunityApplyTbl:            q.CommunityApplyTbl.WithContext(ctx),
		ConfigTbl:                    q.ConfigTbl.WithContext(ctx),
		DeviceDataTbl:                q.DeviceDataTbl.WithContext(ctx),
		DriveruseTbl:                 q.DriveruseTbl.WithContext(ctx),
		ExternalAPIApp:               q.ExternalAPIApp.WithContext(ctx),
		FaultTbl:                     q.FaultTbl.WithContext(ctx),
		FreeChargingUsersTbl:         q.FreeChargingUsersTbl.WithContext(ctx),
		HotSearchItemTbl:             q.HotSearchItemTbl.WithContext(ctx),
		HotelProductTbl:              q.HotelProductTbl.WithContext(ctx),
		HotelStaffTbl:                q.HotelStaffTbl.WithContext(ctx),
		HotelTbl:                     q.HotelTbl.WithContext(ctx),
		ImeiTab:                      q.ImeiTab.WithContext(ctx),
		Invoice:                      q.Invoice.WithContext(ctx),
		InvoiceTitle:                 q.InvoiceTitle.WithContext(ctx),
		LedMacTbl:                    q.LedMacTbl.WithContext(ctx),
		LedTbl:                       q.LedTbl.WithContext(ctx),
		LocalchepaiTbl:               q.LocalchepaiTbl.WithContext(ctx),
		LockTbl:                      q.LockTbl.WithContext(ctx),
		LockUseTbl:                   q.LockUseTbl.WithContext(ctx),
		MessageTbl:                   q.MessageTbl.WithContext(ctx),
		NeighborShareUserTbl:         q.NeighborShareUserTbl.WithContext(ctx),
		OmEmployee:                   q.OmEmployee.WithContext(ctx),
		OpenLockTbl:                  q.OpenLockTbl.WithContext(ctx),
		OrderPrivateTbl:              q.OrderPrivateTbl.WithContext(ctx),
		OrderTbl:                     q.OrderTbl.WithContext(ctx),
		OrderTwiceTbl:                q.OrderTwiceTbl.WithContext(ctx),
		OwnerTbl:                     q.OwnerTbl.WithContext(ctx),
		PackageRecordTbl:             q.PackageRecordTbl.WithContext(ctx),
		PlaceTbl:                     q.PlaceTbl.WithContext(ctx),
		PlaceapplyTbl:                q.PlaceapplyTbl.WithContext(ctx),
		PlatformTbl:                  q.PlatformTbl.WithContext(ctx),
		PointTbl:                     q.PointTbl.WithContext(ctx),
		PrivateChargingPriceTbl:      q.PrivateChargingPriceTbl.WithContext(ctx),
		PrivateChargingTbl:           q.PrivateChargingTbl.WithContext(ctx),
		PrivatePlaceTbl:              q.PrivatePlaceTbl.WithContext(ctx),
		PurchasePoleApplicationTbl:   q.PurchasePoleApplicationTbl.WithContext(ctx),
		ReOrderElectronicTbl:         q.ReOrderElectronicTbl.WithContext(ctx),
		ReceptaclePowerTbl:           q.ReceptaclePowerTbl.WithContext(ctx),
		ReceptacleTbl:                q.ReceptacleTbl.WithContext(ctx),
		RechargeOrderTbl:             q.RechargeOrderTbl.WithContext(ctx),
		RechargeOrderTblSorted:       q.RechargeOrderTblSorted.WithContext(ctx),
		SaveyytimeTbl:                q.SaveyytimeTbl.WithContext(ctx),
		ShopStaffTbl:                 q.ShopStaffTbl.WithContext(ctx),
		ShopTbl:                      q.ShopTbl.WithContext(ctx),
		StaffTbl:                     q.StaffTbl.WithContext(ctx),
		SystemTbl:                    q.SystemTbl.WithContext(ctx),
		TabBalanceRecord:             q.TabBalanceRecord.WithContext(ctx),
		TabChargingGun:               q.TabChargingGun.WithContext(ctx),
		TabGateway:                   q.TabGateway.WithContext(ctx),
		TabImage:                     q.TabImage.WithContext(ctx),
		TabOrderElectronic:           q.TabOrderElectronic.WithContext(ctx),
		TabParkingSpace:              q.TabParkingSpace.WithContext(ctx),
		TabPrice:                     q.TabPrice.WithContext(ctx),
		TabPriceTime:                 q.TabPriceTime.WithContext(ctx),
		TabPriceTimeSpring:           q.TabPriceTimeSpring.WithContext(ctx),
		TabPriceTimeSummer:           q.TabPriceTimeSummer.WithContext(ctx),
		TabPriceTimeWinter:           q.TabPriceTimeWinter.WithContext(ctx),
		TabProduct:                   q.TabProduct.WithContext(ctx),
		TabProfitSharingConfig:       q.TabProfitSharingConfig.WithContext(ctx),
		TabVideo:                     q.TabVideo.WithContext(ctx),
		TabVideoWatchRecord:          q.TabVideoWatchRecord.WithContext(ctx),
		UserBankCardTbl:              q.UserBankCardTbl.WithContext(ctx),
		UserBluetoothBindingsTbl:     q.UserBluetoothBindingsTbl.WithContext(ctx),
		UserShopTbl:                  q.UserShopTbl.WithContext(ctx),
		UserTbl:                      q.UserTbl.WithContext(ctx),
		UsercarTbl:                   q.UsercarTbl.WithContext(ctx),
		UsermessageTbl:               q.UsermessageTbl.WithContext(ctx),
		VersionTbl:                   q.VersionTbl.WithContext(ctx),
		WangguanTbl:                  q.WangguanTbl.WithContext(ctx),
		WithdrawalRecordTbl:          q.WithdrawalRecordTbl.WithContext(ctx),
		ZbbArea:                      q.ZbbArea.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
