// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newHotSearchItemTbl(db *gorm.DB, opts ...gen.DOOption) hotSearchItemTbl {
	_hotSearchItemTbl := hotSearchItemTbl{}

	_hotSearchItemTbl.hotSearchItemTblDo.UseDB(db, opts...)
	_hotSearchItemTbl.hotSearchItemTblDo.UseModel(&model.HotSearchItemTbl{})

	tableName := _hotSearchItemTbl.hotSearchItemTblDo.TableName()
	_hotSearchItemTbl.ALL = field.NewAsterisk(tableName)
	_hotSearchItemTbl.ID = field.NewInt32(tableName, "id")
	_hotSearchItemTbl.PlatformID = field.NewInt32(tableName, "platform_id")
	_hotSearchItemTbl.HotRank = field.NewInt32(tableName, "hot_rank")
	_hotSearchItemTbl.Title = field.NewString(tableName, "title")
	_hotSearchItemTbl.URL = field.NewString(tableName, "url")
	_hotSearchItemTbl.HotValue = field.NewString(tableName, "hot_value")
	_hotSearchItemTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_hotSearchItemTbl.fillFieldMap()

	return _hotSearchItemTbl
}

type hotSearchItemTbl struct {
	hotSearchItemTblDo hotSearchItemTblDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	PlatformID field.Int32  // 所属平台id
	HotRank    field.Int32  // 热搜排名
	Title      field.String // 热搜标题
	URL        field.String // 热搜链接
	HotValue   field.String // 热度值
	UpdateTime field.Time   // 数据更新时间

	fieldMap map[string]field.Expr
}

func (h hotSearchItemTbl) Table(newTableName string) *hotSearchItemTbl {
	h.hotSearchItemTblDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hotSearchItemTbl) As(alias string) *hotSearchItemTbl {
	h.hotSearchItemTblDo.DO = *(h.hotSearchItemTblDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hotSearchItemTbl) updateTableName(table string) *hotSearchItemTbl {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt32(table, "id")
	h.PlatformID = field.NewInt32(table, "platform_id")
	h.HotRank = field.NewInt32(table, "hot_rank")
	h.Title = field.NewString(table, "title")
	h.URL = field.NewString(table, "url")
	h.HotValue = field.NewString(table, "hot_value")
	h.UpdateTime = field.NewTime(table, "update_time")

	h.fillFieldMap()

	return h
}

func (h *hotSearchItemTbl) WithContext(ctx context.Context) IHotSearchItemTblDo {
	return h.hotSearchItemTblDo.WithContext(ctx)
}

func (h hotSearchItemTbl) TableName() string { return h.hotSearchItemTblDo.TableName() }

func (h hotSearchItemTbl) Alias() string { return h.hotSearchItemTblDo.Alias() }

func (h hotSearchItemTbl) Columns(cols ...field.Expr) gen.Columns {
	return h.hotSearchItemTblDo.Columns(cols...)
}

func (h *hotSearchItemTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hotSearchItemTbl) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 7)
	h.fieldMap["id"] = h.ID
	h.fieldMap["platform_id"] = h.PlatformID
	h.fieldMap["hot_rank"] = h.HotRank
	h.fieldMap["title"] = h.Title
	h.fieldMap["url"] = h.URL
	h.fieldMap["hot_value"] = h.HotValue
	h.fieldMap["update_time"] = h.UpdateTime
}

func (h hotSearchItemTbl) clone(db *gorm.DB) hotSearchItemTbl {
	h.hotSearchItemTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hotSearchItemTbl) replaceDB(db *gorm.DB) hotSearchItemTbl {
	h.hotSearchItemTblDo.ReplaceDB(db)
	return h
}

type hotSearchItemTblDo struct{ gen.DO }

type IHotSearchItemTblDo interface {
	gen.SubQuery
	Debug() IHotSearchItemTblDo
	WithContext(ctx context.Context) IHotSearchItemTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHotSearchItemTblDo
	WriteDB() IHotSearchItemTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHotSearchItemTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHotSearchItemTblDo
	Not(conds ...gen.Condition) IHotSearchItemTblDo
	Or(conds ...gen.Condition) IHotSearchItemTblDo
	Select(conds ...field.Expr) IHotSearchItemTblDo
	Where(conds ...gen.Condition) IHotSearchItemTblDo
	Order(conds ...field.Expr) IHotSearchItemTblDo
	Distinct(cols ...field.Expr) IHotSearchItemTblDo
	Omit(cols ...field.Expr) IHotSearchItemTblDo
	Join(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo
	Group(cols ...field.Expr) IHotSearchItemTblDo
	Having(conds ...gen.Condition) IHotSearchItemTblDo
	Limit(limit int) IHotSearchItemTblDo
	Offset(offset int) IHotSearchItemTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHotSearchItemTblDo
	Unscoped() IHotSearchItemTblDo
	Create(values ...*model.HotSearchItemTbl) error
	CreateInBatches(values []*model.HotSearchItemTbl, batchSize int) error
	Save(values ...*model.HotSearchItemTbl) error
	First() (*model.HotSearchItemTbl, error)
	Take() (*model.HotSearchItemTbl, error)
	Last() (*model.HotSearchItemTbl, error)
	Find() ([]*model.HotSearchItemTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HotSearchItemTbl, err error)
	FindInBatches(result *[]*model.HotSearchItemTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HotSearchItemTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHotSearchItemTblDo
	Assign(attrs ...field.AssignExpr) IHotSearchItemTblDo
	Joins(fields ...field.RelationField) IHotSearchItemTblDo
	Preload(fields ...field.RelationField) IHotSearchItemTblDo
	FirstOrInit() (*model.HotSearchItemTbl, error)
	FirstOrCreate() (*model.HotSearchItemTbl, error)
	FindByPage(offset int, limit int) (result []*model.HotSearchItemTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHotSearchItemTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hotSearchItemTblDo) Debug() IHotSearchItemTblDo {
	return h.withDO(h.DO.Debug())
}

func (h hotSearchItemTblDo) WithContext(ctx context.Context) IHotSearchItemTblDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hotSearchItemTblDo) ReadDB() IHotSearchItemTblDo {
	return h.Clauses(dbresolver.Read)
}

func (h hotSearchItemTblDo) WriteDB() IHotSearchItemTblDo {
	return h.Clauses(dbresolver.Write)
}

func (h hotSearchItemTblDo) Session(config *gorm.Session) IHotSearchItemTblDo {
	return h.withDO(h.DO.Session(config))
}

func (h hotSearchItemTblDo) Clauses(conds ...clause.Expression) IHotSearchItemTblDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hotSearchItemTblDo) Returning(value interface{}, columns ...string) IHotSearchItemTblDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hotSearchItemTblDo) Not(conds ...gen.Condition) IHotSearchItemTblDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hotSearchItemTblDo) Or(conds ...gen.Condition) IHotSearchItemTblDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hotSearchItemTblDo) Select(conds ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hotSearchItemTblDo) Where(conds ...gen.Condition) IHotSearchItemTblDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hotSearchItemTblDo) Order(conds ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hotSearchItemTblDo) Distinct(cols ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hotSearchItemTblDo) Omit(cols ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hotSearchItemTblDo) Join(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hotSearchItemTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hotSearchItemTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hotSearchItemTblDo) Group(cols ...field.Expr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hotSearchItemTblDo) Having(conds ...gen.Condition) IHotSearchItemTblDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hotSearchItemTblDo) Limit(limit int) IHotSearchItemTblDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hotSearchItemTblDo) Offset(offset int) IHotSearchItemTblDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hotSearchItemTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHotSearchItemTblDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hotSearchItemTblDo) Unscoped() IHotSearchItemTblDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hotSearchItemTblDo) Create(values ...*model.HotSearchItemTbl) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hotSearchItemTblDo) CreateInBatches(values []*model.HotSearchItemTbl, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hotSearchItemTblDo) Save(values ...*model.HotSearchItemTbl) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hotSearchItemTblDo) First() (*model.HotSearchItemTbl, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotSearchItemTbl), nil
	}
}

func (h hotSearchItemTblDo) Take() (*model.HotSearchItemTbl, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotSearchItemTbl), nil
	}
}

func (h hotSearchItemTblDo) Last() (*model.HotSearchItemTbl, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotSearchItemTbl), nil
	}
}

func (h hotSearchItemTblDo) Find() ([]*model.HotSearchItemTbl, error) {
	result, err := h.DO.Find()
	return result.([]*model.HotSearchItemTbl), err
}

func (h hotSearchItemTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HotSearchItemTbl, err error) {
	buf := make([]*model.HotSearchItemTbl, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hotSearchItemTblDo) FindInBatches(result *[]*model.HotSearchItemTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hotSearchItemTblDo) Attrs(attrs ...field.AssignExpr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hotSearchItemTblDo) Assign(attrs ...field.AssignExpr) IHotSearchItemTblDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hotSearchItemTblDo) Joins(fields ...field.RelationField) IHotSearchItemTblDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hotSearchItemTblDo) Preload(fields ...field.RelationField) IHotSearchItemTblDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hotSearchItemTblDo) FirstOrInit() (*model.HotSearchItemTbl, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotSearchItemTbl), nil
	}
}

func (h hotSearchItemTblDo) FirstOrCreate() (*model.HotSearchItemTbl, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotSearchItemTbl), nil
	}
}

func (h hotSearchItemTblDo) FindByPage(offset int, limit int) (result []*model.HotSearchItemTbl, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hotSearchItemTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hotSearchItemTblDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hotSearchItemTblDo) Delete(models ...*model.HotSearchItemTbl) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hotSearchItemTblDo) withDO(do gen.Dao) *hotSearchItemTblDo {
	h.DO = *do.(*gen.DO)
	return h
}
