// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newHotelTbl(db *gorm.DB, opts ...gen.DOOption) hotelTbl {
	_hotelTbl := hotelTbl{}

	_hotelTbl.hotelTblDo.UseDB(db, opts...)
	_hotelTbl.hotelTblDo.UseModel(&model.HotelTbl{})

	tableName := _hotelTbl.hotelTblDo.TableName()
	_hotelTbl.ALL = field.NewAsterisk(tableName)
	_hotelTbl.ID = field.NewInt32(tableName, "id")
	_hotelTbl.Openid = field.NewString(tableName, "openid")
	_hotelTbl.HotelName = field.NewString(tableName, "hotel_name")
	_hotelTbl.HotelAddress = field.NewString(tableName, "hotel_address")
	_hotelTbl.ParkingNumber = field.NewInt32(tableName, "parking_number")
	_hotelTbl.Phone = field.NewString(tableName, "phone")
	_hotelTbl.Email = field.NewString(tableName, "email")
	_hotelTbl.HotelTime = field.NewString(tableName, "hotel_time")
	_hotelTbl.HotelImgID = field.NewInt32(tableName, "hotel_img_id")
	_hotelTbl.Review = field.NewInt32(tableName, "review")
	_hotelTbl.CreatTime = field.NewTime(tableName, "creat_time")

	_hotelTbl.fillFieldMap()

	return _hotelTbl
}

// hotelTbl 酒店注册信息表
type hotelTbl struct {
	hotelTblDo hotelTblDo

	ALL           field.Asterisk
	ID            field.Int32  // 主键
	Openid        field.String // 用户唯一标识符
	HotelName     field.String // 酒店名称
	HotelAddress  field.String // 酒店地址
	ParkingNumber field.Int32  // 车位数量
	Phone         field.String // 手机号
	Email         field.String // 邮箱
	HotelTime     field.String // 营业时间
	HotelImgID    field.Int32  // 酒店照片--在image表中的id
	Review        field.Int32  // 审核状态
	CreatTime     field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (h hotelTbl) Table(newTableName string) *hotelTbl {
	h.hotelTblDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hotelTbl) As(alias string) *hotelTbl {
	h.hotelTblDo.DO = *(h.hotelTblDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hotelTbl) updateTableName(table string) *hotelTbl {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt32(table, "id")
	h.Openid = field.NewString(table, "openid")
	h.HotelName = field.NewString(table, "hotel_name")
	h.HotelAddress = field.NewString(table, "hotel_address")
	h.ParkingNumber = field.NewInt32(table, "parking_number")
	h.Phone = field.NewString(table, "phone")
	h.Email = field.NewString(table, "email")
	h.HotelTime = field.NewString(table, "hotel_time")
	h.HotelImgID = field.NewInt32(table, "hotel_img_id")
	h.Review = field.NewInt32(table, "review")
	h.CreatTime = field.NewTime(table, "creat_time")

	h.fillFieldMap()

	return h
}

func (h *hotelTbl) WithContext(ctx context.Context) IHotelTblDo { return h.hotelTblDo.WithContext(ctx) }

func (h hotelTbl) TableName() string { return h.hotelTblDo.TableName() }

func (h hotelTbl) Alias() string { return h.hotelTblDo.Alias() }

func (h hotelTbl) Columns(cols ...field.Expr) gen.Columns { return h.hotelTblDo.Columns(cols...) }

func (h *hotelTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hotelTbl) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 11)
	h.fieldMap["id"] = h.ID
	h.fieldMap["openid"] = h.Openid
	h.fieldMap["hotel_name"] = h.HotelName
	h.fieldMap["hotel_address"] = h.HotelAddress
	h.fieldMap["parking_number"] = h.ParkingNumber
	h.fieldMap["phone"] = h.Phone
	h.fieldMap["email"] = h.Email
	h.fieldMap["hotel_time"] = h.HotelTime
	h.fieldMap["hotel_img_id"] = h.HotelImgID
	h.fieldMap["review"] = h.Review
	h.fieldMap["creat_time"] = h.CreatTime
}

func (h hotelTbl) clone(db *gorm.DB) hotelTbl {
	h.hotelTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hotelTbl) replaceDB(db *gorm.DB) hotelTbl {
	h.hotelTblDo.ReplaceDB(db)
	return h
}

type hotelTblDo struct{ gen.DO }

type IHotelTblDo interface {
	gen.SubQuery
	Debug() IHotelTblDo
	WithContext(ctx context.Context) IHotelTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHotelTblDo
	WriteDB() IHotelTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHotelTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHotelTblDo
	Not(conds ...gen.Condition) IHotelTblDo
	Or(conds ...gen.Condition) IHotelTblDo
	Select(conds ...field.Expr) IHotelTblDo
	Where(conds ...gen.Condition) IHotelTblDo
	Order(conds ...field.Expr) IHotelTblDo
	Distinct(cols ...field.Expr) IHotelTblDo
	Omit(cols ...field.Expr) IHotelTblDo
	Join(table schema.Tabler, on ...field.Expr) IHotelTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHotelTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHotelTblDo
	Group(cols ...field.Expr) IHotelTblDo
	Having(conds ...gen.Condition) IHotelTblDo
	Limit(limit int) IHotelTblDo
	Offset(offset int) IHotelTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHotelTblDo
	Unscoped() IHotelTblDo
	Create(values ...*model.HotelTbl) error
	CreateInBatches(values []*model.HotelTbl, batchSize int) error
	Save(values ...*model.HotelTbl) error
	First() (*model.HotelTbl, error)
	Take() (*model.HotelTbl, error)
	Last() (*model.HotelTbl, error)
	Find() ([]*model.HotelTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HotelTbl, err error)
	FindInBatches(result *[]*model.HotelTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HotelTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHotelTblDo
	Assign(attrs ...field.AssignExpr) IHotelTblDo
	Joins(fields ...field.RelationField) IHotelTblDo
	Preload(fields ...field.RelationField) IHotelTblDo
	FirstOrInit() (*model.HotelTbl, error)
	FirstOrCreate() (*model.HotelTbl, error)
	FindByPage(offset int, limit int) (result []*model.HotelTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHotelTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hotelTblDo) Debug() IHotelTblDo {
	return h.withDO(h.DO.Debug())
}

func (h hotelTblDo) WithContext(ctx context.Context) IHotelTblDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hotelTblDo) ReadDB() IHotelTblDo {
	return h.Clauses(dbresolver.Read)
}

func (h hotelTblDo) WriteDB() IHotelTblDo {
	return h.Clauses(dbresolver.Write)
}

func (h hotelTblDo) Session(config *gorm.Session) IHotelTblDo {
	return h.withDO(h.DO.Session(config))
}

func (h hotelTblDo) Clauses(conds ...clause.Expression) IHotelTblDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hotelTblDo) Returning(value interface{}, columns ...string) IHotelTblDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hotelTblDo) Not(conds ...gen.Condition) IHotelTblDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hotelTblDo) Or(conds ...gen.Condition) IHotelTblDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hotelTblDo) Select(conds ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hotelTblDo) Where(conds ...gen.Condition) IHotelTblDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hotelTblDo) Order(conds ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hotelTblDo) Distinct(cols ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hotelTblDo) Omit(cols ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hotelTblDo) Join(table schema.Tabler, on ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hotelTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hotelTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hotelTblDo) Group(cols ...field.Expr) IHotelTblDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hotelTblDo) Having(conds ...gen.Condition) IHotelTblDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hotelTblDo) Limit(limit int) IHotelTblDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hotelTblDo) Offset(offset int) IHotelTblDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hotelTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHotelTblDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hotelTblDo) Unscoped() IHotelTblDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hotelTblDo) Create(values ...*model.HotelTbl) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hotelTblDo) CreateInBatches(values []*model.HotelTbl, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hotelTblDo) Save(values ...*model.HotelTbl) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hotelTblDo) First() (*model.HotelTbl, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotelTbl), nil
	}
}

func (h hotelTblDo) Take() (*model.HotelTbl, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotelTbl), nil
	}
}

func (h hotelTblDo) Last() (*model.HotelTbl, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotelTbl), nil
	}
}

func (h hotelTblDo) Find() ([]*model.HotelTbl, error) {
	result, err := h.DO.Find()
	return result.([]*model.HotelTbl), err
}

func (h hotelTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HotelTbl, err error) {
	buf := make([]*model.HotelTbl, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hotelTblDo) FindInBatches(result *[]*model.HotelTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hotelTblDo) Attrs(attrs ...field.AssignExpr) IHotelTblDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hotelTblDo) Assign(attrs ...field.AssignExpr) IHotelTblDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hotelTblDo) Joins(fields ...field.RelationField) IHotelTblDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hotelTblDo) Preload(fields ...field.RelationField) IHotelTblDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hotelTblDo) FirstOrInit() (*model.HotelTbl, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotelTbl), nil
	}
}

func (h hotelTblDo) FirstOrCreate() (*model.HotelTbl, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HotelTbl), nil
	}
}

func (h hotelTblDo) FindByPage(offset int, limit int) (result []*model.HotelTbl, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hotelTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hotelTblDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hotelTblDo) Delete(models ...*model.HotelTbl) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hotelTblDo) withDO(do gen.Dao) *hotelTblDo {
	h.DO = *do.(*gen.DO)
	return h
}
