// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newLedMacTbl(db *gorm.DB, opts ...gen.DOOption) ledMacTbl {
	_ledMacTbl := ledMacTbl{}

	_ledMacTbl.ledMacTblDo.UseDB(db, opts...)
	_ledMacTbl.ledMacTblDo.UseModel(&model.LedMacTbl{})

	tableName := _ledMacTbl.ledMacTblDo.TableName()
	_ledMacTbl.ALL = field.NewAsterisk(tableName)
	_ledMacTbl.ID = field.NewInt32(tableName, "id")
	_ledMacTbl.LedMac = field.NewString(tableName, "led_mac")
	_ledMacTbl.Pid = field.NewString(tableName, "pid")
	_ledMacTbl.CreateTime = field.NewTime(tableName, "create_time")
	_ledMacTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_ledMacTbl.fillFieldMap()

	return _ledMacTbl
}

// ledMacTbl 车位牌
type ledMacTbl struct {
	ledMacTblDo ledMacTblDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	LedMac     field.String // led灯mac地址
	Pid        field.String // 车位锁id
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (l ledMacTbl) Table(newTableName string) *ledMacTbl {
	l.ledMacTblDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l ledMacTbl) As(alias string) *ledMacTbl {
	l.ledMacTblDo.DO = *(l.ledMacTblDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *ledMacTbl) updateTableName(table string) *ledMacTbl {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt32(table, "id")
	l.LedMac = field.NewString(table, "led_mac")
	l.Pid = field.NewString(table, "pid")
	l.CreateTime = field.NewTime(table, "create_time")
	l.UpdateTime = field.NewTime(table, "update_time")

	l.fillFieldMap()

	return l
}

func (l *ledMacTbl) WithContext(ctx context.Context) ILedMacTblDo {
	return l.ledMacTblDo.WithContext(ctx)
}

func (l ledMacTbl) TableName() string { return l.ledMacTblDo.TableName() }

func (l ledMacTbl) Alias() string { return l.ledMacTblDo.Alias() }

func (l ledMacTbl) Columns(cols ...field.Expr) gen.Columns { return l.ledMacTblDo.Columns(cols...) }

func (l *ledMacTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *ledMacTbl) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 5)
	l.fieldMap["id"] = l.ID
	l.fieldMap["led_mac"] = l.LedMac
	l.fieldMap["pid"] = l.Pid
	l.fieldMap["create_time"] = l.CreateTime
	l.fieldMap["update_time"] = l.UpdateTime
}

func (l ledMacTbl) clone(db *gorm.DB) ledMacTbl {
	l.ledMacTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l ledMacTbl) replaceDB(db *gorm.DB) ledMacTbl {
	l.ledMacTblDo.ReplaceDB(db)
	return l
}

type ledMacTblDo struct{ gen.DO }

type ILedMacTblDo interface {
	gen.SubQuery
	Debug() ILedMacTblDo
	WithContext(ctx context.Context) ILedMacTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILedMacTblDo
	WriteDB() ILedMacTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILedMacTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILedMacTblDo
	Not(conds ...gen.Condition) ILedMacTblDo
	Or(conds ...gen.Condition) ILedMacTblDo
	Select(conds ...field.Expr) ILedMacTblDo
	Where(conds ...gen.Condition) ILedMacTblDo
	Order(conds ...field.Expr) ILedMacTblDo
	Distinct(cols ...field.Expr) ILedMacTblDo
	Omit(cols ...field.Expr) ILedMacTblDo
	Join(table schema.Tabler, on ...field.Expr) ILedMacTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILedMacTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILedMacTblDo
	Group(cols ...field.Expr) ILedMacTblDo
	Having(conds ...gen.Condition) ILedMacTblDo
	Limit(limit int) ILedMacTblDo
	Offset(offset int) ILedMacTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILedMacTblDo
	Unscoped() ILedMacTblDo
	Create(values ...*model.LedMacTbl) error
	CreateInBatches(values []*model.LedMacTbl, batchSize int) error
	Save(values ...*model.LedMacTbl) error
	First() (*model.LedMacTbl, error)
	Take() (*model.LedMacTbl, error)
	Last() (*model.LedMacTbl, error)
	Find() ([]*model.LedMacTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LedMacTbl, err error)
	FindInBatches(result *[]*model.LedMacTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LedMacTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILedMacTblDo
	Assign(attrs ...field.AssignExpr) ILedMacTblDo
	Joins(fields ...field.RelationField) ILedMacTblDo
	Preload(fields ...field.RelationField) ILedMacTblDo
	FirstOrInit() (*model.LedMacTbl, error)
	FirstOrCreate() (*model.LedMacTbl, error)
	FindByPage(offset int, limit int) (result []*model.LedMacTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILedMacTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l ledMacTblDo) Debug() ILedMacTblDo {
	return l.withDO(l.DO.Debug())
}

func (l ledMacTblDo) WithContext(ctx context.Context) ILedMacTblDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l ledMacTblDo) ReadDB() ILedMacTblDo {
	return l.Clauses(dbresolver.Read)
}

func (l ledMacTblDo) WriteDB() ILedMacTblDo {
	return l.Clauses(dbresolver.Write)
}

func (l ledMacTblDo) Session(config *gorm.Session) ILedMacTblDo {
	return l.withDO(l.DO.Session(config))
}

func (l ledMacTblDo) Clauses(conds ...clause.Expression) ILedMacTblDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l ledMacTblDo) Returning(value interface{}, columns ...string) ILedMacTblDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l ledMacTblDo) Not(conds ...gen.Condition) ILedMacTblDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l ledMacTblDo) Or(conds ...gen.Condition) ILedMacTblDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l ledMacTblDo) Select(conds ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l ledMacTblDo) Where(conds ...gen.Condition) ILedMacTblDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l ledMacTblDo) Order(conds ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l ledMacTblDo) Distinct(cols ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l ledMacTblDo) Omit(cols ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l ledMacTblDo) Join(table schema.Tabler, on ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l ledMacTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l ledMacTblDo) RightJoin(table schema.Tabler, on ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l ledMacTblDo) Group(cols ...field.Expr) ILedMacTblDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l ledMacTblDo) Having(conds ...gen.Condition) ILedMacTblDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l ledMacTblDo) Limit(limit int) ILedMacTblDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l ledMacTblDo) Offset(offset int) ILedMacTblDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l ledMacTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILedMacTblDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l ledMacTblDo) Unscoped() ILedMacTblDo {
	return l.withDO(l.DO.Unscoped())
}

func (l ledMacTblDo) Create(values ...*model.LedMacTbl) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l ledMacTblDo) CreateInBatches(values []*model.LedMacTbl, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l ledMacTblDo) Save(values ...*model.LedMacTbl) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l ledMacTblDo) First() (*model.LedMacTbl, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedMacTbl), nil
	}
}

func (l ledMacTblDo) Take() (*model.LedMacTbl, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedMacTbl), nil
	}
}

func (l ledMacTblDo) Last() (*model.LedMacTbl, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedMacTbl), nil
	}
}

func (l ledMacTblDo) Find() ([]*model.LedMacTbl, error) {
	result, err := l.DO.Find()
	return result.([]*model.LedMacTbl), err
}

func (l ledMacTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LedMacTbl, err error) {
	buf := make([]*model.LedMacTbl, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l ledMacTblDo) FindInBatches(result *[]*model.LedMacTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l ledMacTblDo) Attrs(attrs ...field.AssignExpr) ILedMacTblDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l ledMacTblDo) Assign(attrs ...field.AssignExpr) ILedMacTblDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l ledMacTblDo) Joins(fields ...field.RelationField) ILedMacTblDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l ledMacTblDo) Preload(fields ...field.RelationField) ILedMacTblDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l ledMacTblDo) FirstOrInit() (*model.LedMacTbl, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedMacTbl), nil
	}
}

func (l ledMacTblDo) FirstOrCreate() (*model.LedMacTbl, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedMacTbl), nil
	}
}

func (l ledMacTblDo) FindByPage(offset int, limit int) (result []*model.LedMacTbl, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l ledMacTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l ledMacTblDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l ledMacTblDo) Delete(models ...*model.LedMacTbl) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *ledMacTblDo) withDO(do gen.Dao) *ledMacTblDo {
	l.DO = *do.(*gen.DO)
	return l
}
