// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newOrderTwiceTbl(db *gorm.DB, opts ...gen.DOOption) orderTwiceTbl {
	_orderTwiceTbl := orderTwiceTbl{}

	_orderTwiceTbl.orderTwiceTblDo.UseDB(db, opts...)
	_orderTwiceTbl.orderTwiceTblDo.UseModel(&model.OrderTwiceTbl{})

	tableName := _orderTwiceTbl.orderTwiceTblDo.TableName()
	_orderTwiceTbl.ALL = field.NewAsterisk(tableName)
	_orderTwiceTbl.Orderid = field.NewString(tableName, "orderid")
	_orderTwiceTbl.PowerRate = field.NewFloat64(tableName, "power_rate")
	_orderTwiceTbl.ServiceRate = field.NewFloat64(tableName, "service_rate")
	_orderTwiceTbl.CreateTime = field.NewTime(tableName, "create_time")
	_orderTwiceTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_orderTwiceTbl.fillFieldMap()

	return _orderTwiceTbl
}

// orderTwiceTbl 二轮车订单-计费表
type orderTwiceTbl struct {
	orderTwiceTblDo orderTwiceTblDo

	ALL         field.Asterisk
	Orderid     field.String  // 订单id
	PowerRate   field.Float64 // 电费
	ServiceRate field.Float64 // 服务费
	CreateTime  field.Time    // 创建时间
	UpdateTime  field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (o orderTwiceTbl) Table(newTableName string) *orderTwiceTbl {
	o.orderTwiceTblDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderTwiceTbl) As(alias string) *orderTwiceTbl {
	o.orderTwiceTblDo.DO = *(o.orderTwiceTblDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderTwiceTbl) updateTableName(table string) *orderTwiceTbl {
	o.ALL = field.NewAsterisk(table)
	o.Orderid = field.NewString(table, "orderid")
	o.PowerRate = field.NewFloat64(table, "power_rate")
	o.ServiceRate = field.NewFloat64(table, "service_rate")
	o.CreateTime = field.NewTime(table, "create_time")
	o.UpdateTime = field.NewTime(table, "update_time")

	o.fillFieldMap()

	return o
}

func (o *orderTwiceTbl) WithContext(ctx context.Context) IOrderTwiceTblDo {
	return o.orderTwiceTblDo.WithContext(ctx)
}

func (o orderTwiceTbl) TableName() string { return o.orderTwiceTblDo.TableName() }

func (o orderTwiceTbl) Alias() string { return o.orderTwiceTblDo.Alias() }

func (o orderTwiceTbl) Columns(cols ...field.Expr) gen.Columns {
	return o.orderTwiceTblDo.Columns(cols...)
}

func (o *orderTwiceTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderTwiceTbl) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 5)
	o.fieldMap["orderid"] = o.Orderid
	o.fieldMap["power_rate"] = o.PowerRate
	o.fieldMap["service_rate"] = o.ServiceRate
	o.fieldMap["create_time"] = o.CreateTime
	o.fieldMap["update_time"] = o.UpdateTime
}

func (o orderTwiceTbl) clone(db *gorm.DB) orderTwiceTbl {
	o.orderTwiceTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderTwiceTbl) replaceDB(db *gorm.DB) orderTwiceTbl {
	o.orderTwiceTblDo.ReplaceDB(db)
	return o
}

type orderTwiceTblDo struct{ gen.DO }

type IOrderTwiceTblDo interface {
	gen.SubQuery
	Debug() IOrderTwiceTblDo
	WithContext(ctx context.Context) IOrderTwiceTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrderTwiceTblDo
	WriteDB() IOrderTwiceTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrderTwiceTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrderTwiceTblDo
	Not(conds ...gen.Condition) IOrderTwiceTblDo
	Or(conds ...gen.Condition) IOrderTwiceTblDo
	Select(conds ...field.Expr) IOrderTwiceTblDo
	Where(conds ...gen.Condition) IOrderTwiceTblDo
	Order(conds ...field.Expr) IOrderTwiceTblDo
	Distinct(cols ...field.Expr) IOrderTwiceTblDo
	Omit(cols ...field.Expr) IOrderTwiceTblDo
	Join(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo
	Group(cols ...field.Expr) IOrderTwiceTblDo
	Having(conds ...gen.Condition) IOrderTwiceTblDo
	Limit(limit int) IOrderTwiceTblDo
	Offset(offset int) IOrderTwiceTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderTwiceTblDo
	Unscoped() IOrderTwiceTblDo
	Create(values ...*model.OrderTwiceTbl) error
	CreateInBatches(values []*model.OrderTwiceTbl, batchSize int) error
	Save(values ...*model.OrderTwiceTbl) error
	First() (*model.OrderTwiceTbl, error)
	Take() (*model.OrderTwiceTbl, error)
	Last() (*model.OrderTwiceTbl, error)
	Find() ([]*model.OrderTwiceTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderTwiceTbl, err error)
	FindInBatches(result *[]*model.OrderTwiceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OrderTwiceTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrderTwiceTblDo
	Assign(attrs ...field.AssignExpr) IOrderTwiceTblDo
	Joins(fields ...field.RelationField) IOrderTwiceTblDo
	Preload(fields ...field.RelationField) IOrderTwiceTblDo
	FirstOrInit() (*model.OrderTwiceTbl, error)
	FirstOrCreate() (*model.OrderTwiceTbl, error)
	FindByPage(offset int, limit int) (result []*model.OrderTwiceTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrderTwiceTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o orderTwiceTblDo) Debug() IOrderTwiceTblDo {
	return o.withDO(o.DO.Debug())
}

func (o orderTwiceTblDo) WithContext(ctx context.Context) IOrderTwiceTblDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderTwiceTblDo) ReadDB() IOrderTwiceTblDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderTwiceTblDo) WriteDB() IOrderTwiceTblDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderTwiceTblDo) Session(config *gorm.Session) IOrderTwiceTblDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderTwiceTblDo) Clauses(conds ...clause.Expression) IOrderTwiceTblDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderTwiceTblDo) Returning(value interface{}, columns ...string) IOrderTwiceTblDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderTwiceTblDo) Not(conds ...gen.Condition) IOrderTwiceTblDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderTwiceTblDo) Or(conds ...gen.Condition) IOrderTwiceTblDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderTwiceTblDo) Select(conds ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderTwiceTblDo) Where(conds ...gen.Condition) IOrderTwiceTblDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderTwiceTblDo) Order(conds ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderTwiceTblDo) Distinct(cols ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderTwiceTblDo) Omit(cols ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderTwiceTblDo) Join(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderTwiceTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderTwiceTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderTwiceTblDo) Group(cols ...field.Expr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderTwiceTblDo) Having(conds ...gen.Condition) IOrderTwiceTblDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderTwiceTblDo) Limit(limit int) IOrderTwiceTblDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderTwiceTblDo) Offset(offset int) IOrderTwiceTblDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderTwiceTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderTwiceTblDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderTwiceTblDo) Unscoped() IOrderTwiceTblDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderTwiceTblDo) Create(values ...*model.OrderTwiceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderTwiceTblDo) CreateInBatches(values []*model.OrderTwiceTbl, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderTwiceTblDo) Save(values ...*model.OrderTwiceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderTwiceTblDo) First() (*model.OrderTwiceTbl, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderTwiceTbl), nil
	}
}

func (o orderTwiceTblDo) Take() (*model.OrderTwiceTbl, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderTwiceTbl), nil
	}
}

func (o orderTwiceTblDo) Last() (*model.OrderTwiceTbl, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderTwiceTbl), nil
	}
}

func (o orderTwiceTblDo) Find() ([]*model.OrderTwiceTbl, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrderTwiceTbl), err
}

func (o orderTwiceTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderTwiceTbl, err error) {
	buf := make([]*model.OrderTwiceTbl, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderTwiceTblDo) FindInBatches(result *[]*model.OrderTwiceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderTwiceTblDo) Attrs(attrs ...field.AssignExpr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderTwiceTblDo) Assign(attrs ...field.AssignExpr) IOrderTwiceTblDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderTwiceTblDo) Joins(fields ...field.RelationField) IOrderTwiceTblDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderTwiceTblDo) Preload(fields ...field.RelationField) IOrderTwiceTblDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderTwiceTblDo) FirstOrInit() (*model.OrderTwiceTbl, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderTwiceTbl), nil
	}
}

func (o orderTwiceTblDo) FirstOrCreate() (*model.OrderTwiceTbl, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderTwiceTbl), nil
	}
}

func (o orderTwiceTblDo) FindByPage(offset int, limit int) (result []*model.OrderTwiceTbl, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderTwiceTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderTwiceTblDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderTwiceTblDo) Delete(models ...*model.OrderTwiceTbl) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderTwiceTblDo) withDO(do gen.Dao) *orderTwiceTblDo {
	o.DO = *do.(*gen.DO)
	return o
}
