// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newPointTbl(db *gorm.DB, opts ...gen.DOOption) pointTbl {
	_pointTbl := pointTbl{}

	_pointTbl.pointTblDo.UseDB(db, opts...)
	_pointTbl.pointTblDo.UseModel(&model.PointTbl{})

	tableName := _pointTbl.pointTblDo.TableName()
	_pointTbl.ALL = field.NewAsterisk(tableName)
	_pointTbl.ID = field.NewInt32(tableName, "id")
	_pointTbl.UserOpenid = field.NewInt32(tableName, "user_openid")
	_pointTbl.Points = field.NewString(tableName, "points")
	_pointTbl.Source = field.NewString(tableName, "source")
	_pointTbl.Type = field.NewString(tableName, "type")
	_pointTbl.CreateTime = field.NewTime(tableName, "create_time")
	_pointTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_pointTbl.fillFieldMap()

	return _pointTbl
}

// pointTbl 用户积分表
type pointTbl struct {
	pointTblDo pointTblDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	UserOpenid field.Int32  // 用户openid
	Points     field.String // 积分数量
	Source     field.String // 积分来源
	Type       field.String // 积分类型
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (p pointTbl) Table(newTableName string) *pointTbl {
	p.pointTblDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pointTbl) As(alias string) *pointTbl {
	p.pointTblDo.DO = *(p.pointTblDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pointTbl) updateTableName(table string) *pointTbl {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.UserOpenid = field.NewInt32(table, "user_openid")
	p.Points = field.NewString(table, "points")
	p.Source = field.NewString(table, "source")
	p.Type = field.NewString(table, "type")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")

	p.fillFieldMap()

	return p
}

func (p *pointTbl) WithContext(ctx context.Context) IPointTblDo { return p.pointTblDo.WithContext(ctx) }

func (p pointTbl) TableName() string { return p.pointTblDo.TableName() }

func (p pointTbl) Alias() string { return p.pointTblDo.Alias() }

func (p pointTbl) Columns(cols ...field.Expr) gen.Columns { return p.pointTblDo.Columns(cols...) }

func (p *pointTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pointTbl) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_openid"] = p.UserOpenid
	p.fieldMap["points"] = p.Points
	p.fieldMap["source"] = p.Source
	p.fieldMap["type"] = p.Type
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
}

func (p pointTbl) clone(db *gorm.DB) pointTbl {
	p.pointTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pointTbl) replaceDB(db *gorm.DB) pointTbl {
	p.pointTblDo.ReplaceDB(db)
	return p
}

type pointTblDo struct{ gen.DO }

type IPointTblDo interface {
	gen.SubQuery
	Debug() IPointTblDo
	WithContext(ctx context.Context) IPointTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPointTblDo
	WriteDB() IPointTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPointTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPointTblDo
	Not(conds ...gen.Condition) IPointTblDo
	Or(conds ...gen.Condition) IPointTblDo
	Select(conds ...field.Expr) IPointTblDo
	Where(conds ...gen.Condition) IPointTblDo
	Order(conds ...field.Expr) IPointTblDo
	Distinct(cols ...field.Expr) IPointTblDo
	Omit(cols ...field.Expr) IPointTblDo
	Join(table schema.Tabler, on ...field.Expr) IPointTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPointTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPointTblDo
	Group(cols ...field.Expr) IPointTblDo
	Having(conds ...gen.Condition) IPointTblDo
	Limit(limit int) IPointTblDo
	Offset(offset int) IPointTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPointTblDo
	Unscoped() IPointTblDo
	Create(values ...*model.PointTbl) error
	CreateInBatches(values []*model.PointTbl, batchSize int) error
	Save(values ...*model.PointTbl) error
	First() (*model.PointTbl, error)
	Take() (*model.PointTbl, error)
	Last() (*model.PointTbl, error)
	Find() ([]*model.PointTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PointTbl, err error)
	FindInBatches(result *[]*model.PointTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PointTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPointTblDo
	Assign(attrs ...field.AssignExpr) IPointTblDo
	Joins(fields ...field.RelationField) IPointTblDo
	Preload(fields ...field.RelationField) IPointTblDo
	FirstOrInit() (*model.PointTbl, error)
	FirstOrCreate() (*model.PointTbl, error)
	FindByPage(offset int, limit int) (result []*model.PointTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPointTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pointTblDo) Debug() IPointTblDo {
	return p.withDO(p.DO.Debug())
}

func (p pointTblDo) WithContext(ctx context.Context) IPointTblDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pointTblDo) ReadDB() IPointTblDo {
	return p.Clauses(dbresolver.Read)
}

func (p pointTblDo) WriteDB() IPointTblDo {
	return p.Clauses(dbresolver.Write)
}

func (p pointTblDo) Session(config *gorm.Session) IPointTblDo {
	return p.withDO(p.DO.Session(config))
}

func (p pointTblDo) Clauses(conds ...clause.Expression) IPointTblDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pointTblDo) Returning(value interface{}, columns ...string) IPointTblDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pointTblDo) Not(conds ...gen.Condition) IPointTblDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pointTblDo) Or(conds ...gen.Condition) IPointTblDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pointTblDo) Select(conds ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pointTblDo) Where(conds ...gen.Condition) IPointTblDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pointTblDo) Order(conds ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pointTblDo) Distinct(cols ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pointTblDo) Omit(cols ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pointTblDo) Join(table schema.Tabler, on ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pointTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pointTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pointTblDo) Group(cols ...field.Expr) IPointTblDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pointTblDo) Having(conds ...gen.Condition) IPointTblDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pointTblDo) Limit(limit int) IPointTblDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pointTblDo) Offset(offset int) IPointTblDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pointTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPointTblDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pointTblDo) Unscoped() IPointTblDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pointTblDo) Create(values ...*model.PointTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pointTblDo) CreateInBatches(values []*model.PointTbl, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pointTblDo) Save(values ...*model.PointTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pointTblDo) First() (*model.PointTbl, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PointTbl), nil
	}
}

func (p pointTblDo) Take() (*model.PointTbl, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PointTbl), nil
	}
}

func (p pointTblDo) Last() (*model.PointTbl, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PointTbl), nil
	}
}

func (p pointTblDo) Find() ([]*model.PointTbl, error) {
	result, err := p.DO.Find()
	return result.([]*model.PointTbl), err
}

func (p pointTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PointTbl, err error) {
	buf := make([]*model.PointTbl, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pointTblDo) FindInBatches(result *[]*model.PointTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pointTblDo) Attrs(attrs ...field.AssignExpr) IPointTblDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pointTblDo) Assign(attrs ...field.AssignExpr) IPointTblDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pointTblDo) Joins(fields ...field.RelationField) IPointTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pointTblDo) Preload(fields ...field.RelationField) IPointTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pointTblDo) FirstOrInit() (*model.PointTbl, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PointTbl), nil
	}
}

func (p pointTblDo) FirstOrCreate() (*model.PointTbl, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PointTbl), nil
	}
}

func (p pointTblDo) FindByPage(offset int, limit int) (result []*model.PointTbl, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pointTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pointTblDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pointTblDo) Delete(models ...*model.PointTbl) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pointTblDo) withDO(do gen.Dao) *pointTblDo {
	p.DO = *do.(*gen.DO)
	return p
}
