// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newPrivateChargingPriceTbl(db *gorm.DB, opts ...gen.DOOption) privateChargingPriceTbl {
	_privateChargingPriceTbl := privateChargingPriceTbl{}

	_privateChargingPriceTbl.privateChargingPriceTblDo.UseDB(db, opts...)
	_privateChargingPriceTbl.privateChargingPriceTblDo.UseModel(&model.PrivateChargingPriceTbl{})

	tableName := _privateChargingPriceTbl.privateChargingPriceTblDo.TableName()
	_privateChargingPriceTbl.ALL = field.NewAsterisk(tableName)
	_privateChargingPriceTbl.ID = field.NewInt32(tableName, "id")
	_privateChargingPriceTbl.Total = field.NewFloat64(tableName, "total")
	_privateChargingPriceTbl.Name = field.NewString(tableName, "name")
	_privateChargingPriceTbl.Service = field.NewFloat64(tableName, "service")

	_privateChargingPriceTbl.fillFieldMap()

	return _privateChargingPriceTbl
}

// privateChargingPriceTbl 私桩--电价
type privateChargingPriceTbl struct {
	privateChargingPriceTblDo privateChargingPriceTblDo

	ALL     field.Asterisk
	ID      field.Int32   // 电价id
	Total   field.Float64 // 单价
	Name    field.String  // 电价名称
	Service field.Float64 // 服务费

	fieldMap map[string]field.Expr
}

func (p privateChargingPriceTbl) Table(newTableName string) *privateChargingPriceTbl {
	p.privateChargingPriceTblDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p privateChargingPriceTbl) As(alias string) *privateChargingPriceTbl {
	p.privateChargingPriceTblDo.DO = *(p.privateChargingPriceTblDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *privateChargingPriceTbl) updateTableName(table string) *privateChargingPriceTbl {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Total = field.NewFloat64(table, "total")
	p.Name = field.NewString(table, "name")
	p.Service = field.NewFloat64(table, "service")

	p.fillFieldMap()

	return p
}

func (p *privateChargingPriceTbl) WithContext(ctx context.Context) IPrivateChargingPriceTblDo {
	return p.privateChargingPriceTblDo.WithContext(ctx)
}

func (p privateChargingPriceTbl) TableName() string { return p.privateChargingPriceTblDo.TableName() }

func (p privateChargingPriceTbl) Alias() string { return p.privateChargingPriceTblDo.Alias() }

func (p privateChargingPriceTbl) Columns(cols ...field.Expr) gen.Columns {
	return p.privateChargingPriceTblDo.Columns(cols...)
}

func (p *privateChargingPriceTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *privateChargingPriceTbl) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["total"] = p.Total
	p.fieldMap["name"] = p.Name
	p.fieldMap["service"] = p.Service
}

func (p privateChargingPriceTbl) clone(db *gorm.DB) privateChargingPriceTbl {
	p.privateChargingPriceTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p privateChargingPriceTbl) replaceDB(db *gorm.DB) privateChargingPriceTbl {
	p.privateChargingPriceTblDo.ReplaceDB(db)
	return p
}

type privateChargingPriceTblDo struct{ gen.DO }

type IPrivateChargingPriceTblDo interface {
	gen.SubQuery
	Debug() IPrivateChargingPriceTblDo
	WithContext(ctx context.Context) IPrivateChargingPriceTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrivateChargingPriceTblDo
	WriteDB() IPrivateChargingPriceTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrivateChargingPriceTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrivateChargingPriceTblDo
	Not(conds ...gen.Condition) IPrivateChargingPriceTblDo
	Or(conds ...gen.Condition) IPrivateChargingPriceTblDo
	Select(conds ...field.Expr) IPrivateChargingPriceTblDo
	Where(conds ...gen.Condition) IPrivateChargingPriceTblDo
	Order(conds ...field.Expr) IPrivateChargingPriceTblDo
	Distinct(cols ...field.Expr) IPrivateChargingPriceTblDo
	Omit(cols ...field.Expr) IPrivateChargingPriceTblDo
	Join(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo
	Group(cols ...field.Expr) IPrivateChargingPriceTblDo
	Having(conds ...gen.Condition) IPrivateChargingPriceTblDo
	Limit(limit int) IPrivateChargingPriceTblDo
	Offset(offset int) IPrivateChargingPriceTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrivateChargingPriceTblDo
	Unscoped() IPrivateChargingPriceTblDo
	Create(values ...*model.PrivateChargingPriceTbl) error
	CreateInBatches(values []*model.PrivateChargingPriceTbl, batchSize int) error
	Save(values ...*model.PrivateChargingPriceTbl) error
	First() (*model.PrivateChargingPriceTbl, error)
	Take() (*model.PrivateChargingPriceTbl, error)
	Last() (*model.PrivateChargingPriceTbl, error)
	Find() ([]*model.PrivateChargingPriceTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrivateChargingPriceTbl, err error)
	FindInBatches(result *[]*model.PrivateChargingPriceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrivateChargingPriceTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrivateChargingPriceTblDo
	Assign(attrs ...field.AssignExpr) IPrivateChargingPriceTblDo
	Joins(fields ...field.RelationField) IPrivateChargingPriceTblDo
	Preload(fields ...field.RelationField) IPrivateChargingPriceTblDo
	FirstOrInit() (*model.PrivateChargingPriceTbl, error)
	FirstOrCreate() (*model.PrivateChargingPriceTbl, error)
	FindByPage(offset int, limit int) (result []*model.PrivateChargingPriceTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrivateChargingPriceTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p privateChargingPriceTblDo) Debug() IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Debug())
}

func (p privateChargingPriceTblDo) WithContext(ctx context.Context) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p privateChargingPriceTblDo) ReadDB() IPrivateChargingPriceTblDo {
	return p.Clauses(dbresolver.Read)
}

func (p privateChargingPriceTblDo) WriteDB() IPrivateChargingPriceTblDo {
	return p.Clauses(dbresolver.Write)
}

func (p privateChargingPriceTblDo) Session(config *gorm.Session) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Session(config))
}

func (p privateChargingPriceTblDo) Clauses(conds ...clause.Expression) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p privateChargingPriceTblDo) Returning(value interface{}, columns ...string) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p privateChargingPriceTblDo) Not(conds ...gen.Condition) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p privateChargingPriceTblDo) Or(conds ...gen.Condition) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p privateChargingPriceTblDo) Select(conds ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p privateChargingPriceTblDo) Where(conds ...gen.Condition) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p privateChargingPriceTblDo) Order(conds ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p privateChargingPriceTblDo) Distinct(cols ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p privateChargingPriceTblDo) Omit(cols ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p privateChargingPriceTblDo) Join(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p privateChargingPriceTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p privateChargingPriceTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p privateChargingPriceTblDo) Group(cols ...field.Expr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p privateChargingPriceTblDo) Having(conds ...gen.Condition) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p privateChargingPriceTblDo) Limit(limit int) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p privateChargingPriceTblDo) Offset(offset int) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p privateChargingPriceTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p privateChargingPriceTblDo) Unscoped() IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Unscoped())
}

func (p privateChargingPriceTblDo) Create(values ...*model.PrivateChargingPriceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p privateChargingPriceTblDo) CreateInBatches(values []*model.PrivateChargingPriceTbl, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p privateChargingPriceTblDo) Save(values ...*model.PrivateChargingPriceTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p privateChargingPriceTblDo) First() (*model.PrivateChargingPriceTbl, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChargingPriceTbl), nil
	}
}

func (p privateChargingPriceTblDo) Take() (*model.PrivateChargingPriceTbl, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChargingPriceTbl), nil
	}
}

func (p privateChargingPriceTblDo) Last() (*model.PrivateChargingPriceTbl, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChargingPriceTbl), nil
	}
}

func (p privateChargingPriceTblDo) Find() ([]*model.PrivateChargingPriceTbl, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrivateChargingPriceTbl), err
}

func (p privateChargingPriceTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrivateChargingPriceTbl, err error) {
	buf := make([]*model.PrivateChargingPriceTbl, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p privateChargingPriceTblDo) FindInBatches(result *[]*model.PrivateChargingPriceTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p privateChargingPriceTblDo) Attrs(attrs ...field.AssignExpr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p privateChargingPriceTblDo) Assign(attrs ...field.AssignExpr) IPrivateChargingPriceTblDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p privateChargingPriceTblDo) Joins(fields ...field.RelationField) IPrivateChargingPriceTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p privateChargingPriceTblDo) Preload(fields ...field.RelationField) IPrivateChargingPriceTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p privateChargingPriceTblDo) FirstOrInit() (*model.PrivateChargingPriceTbl, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChargingPriceTbl), nil
	}
}

func (p privateChargingPriceTblDo) FirstOrCreate() (*model.PrivateChargingPriceTbl, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChargingPriceTbl), nil
	}
}

func (p privateChargingPriceTblDo) FindByPage(offset int, limit int) (result []*model.PrivateChargingPriceTbl, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p privateChargingPriceTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p privateChargingPriceTblDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p privateChargingPriceTblDo) Delete(models ...*model.PrivateChargingPriceTbl) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *privateChargingPriceTblDo) withDO(do gen.Dao) *privateChargingPriceTblDo {
	p.DO = *do.(*gen.DO)
	return p
}
