// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newPurchasePoleApplicationTbl(db *gorm.DB, opts ...gen.DOOption) purchasePoleApplicationTbl {
	_purchasePoleApplicationTbl := purchasePoleApplicationTbl{}

	_purchasePoleApplicationTbl.purchasePoleApplicationTblDo.UseDB(db, opts...)
	_purchasePoleApplicationTbl.purchasePoleApplicationTblDo.UseModel(&model.PurchasePoleApplicationTbl{})

	tableName := _purchasePoleApplicationTbl.purchasePoleApplicationTblDo.TableName()
	_purchasePoleApplicationTbl.ALL = field.NewAsterisk(tableName)
	_purchasePoleApplicationTbl.OrderNumber = field.NewString(tableName, "order_number")
	_purchasePoleApplicationTbl.Openid = field.NewString(tableName, "openid")
	_purchasePoleApplicationTbl.Name = field.NewString(tableName, "name")
	_purchasePoleApplicationTbl.IDNumber = field.NewString(tableName, "id_number")
	_purchasePoleApplicationTbl.PhoneNumber = field.NewString(tableName, "phone_number")
	_purchasePoleApplicationTbl.SelectedPackage = field.NewString(tableName, "selected_package")
	_purchasePoleApplicationTbl.SelectedColor = field.NewString(tableName, "selected_color")
	_purchasePoleApplicationTbl.InstallationDistance = field.NewFloat64(tableName, "installation_distance")
	_purchasePoleApplicationTbl.InstallationDate = field.NewString(tableName, "installation_date")
	_purchasePoleApplicationTbl.UsageScenario = field.NewString(tableName, "usage_scenario")
	_purchasePoleApplicationTbl.InstallationAddress = field.NewString(tableName, "installation_address")
	_purchasePoleApplicationTbl.DetailedAddress = field.NewString(tableName, "detailed_address")
	_purchasePoleApplicationTbl.ApplyTime = field.NewTime(tableName, "apply_time")
	_purchasePoleApplicationTbl.OrderStatus = field.NewString(tableName, "order_status")
	_purchasePoleApplicationTbl.ActualPayment = field.NewFloat64(tableName, "actual_payment")
	_purchasePoleApplicationTbl.PayTime = field.NewTime(tableName, "pay_time")
	_purchasePoleApplicationTbl.TransactionID = field.NewString(tableName, "transaction_id")
	_purchasePoleApplicationTbl.RefundReason = field.NewString(tableName, "refund_reason")
	_purchasePoleApplicationTbl.RefundTime = field.NewTime(tableName, "refund_time")
	_purchasePoleApplicationTbl.PaymentType = field.NewString(tableName, "payment_type")

	_purchasePoleApplicationTbl.fillFieldMap()

	return _purchasePoleApplicationTbl
}

// purchasePoleApplicationTbl 购桩申请表
type purchasePoleApplicationTbl struct {
	purchasePoleApplicationTblDo purchasePoleApplicationTblDo

	ALL                  field.Asterisk
	OrderNumber          field.String  // 订单号
	Openid               field.String  // 用户openid
	Name                 field.String  // 姓名
	IDNumber             field.String  // 身份证号码
	PhoneNumber          field.String  // 电话号码
	SelectedPackage      field.String  // 选购套餐
	SelectedColor        field.String  // 选购颜色
	InstallationDistance field.Float64 // 安装距离（米）
	InstallationDate     field.String  // 安装时间
	UsageScenario        field.String  // 使用场景
	InstallationAddress  field.String  // 安装地址
	DetailedAddress      field.String  // 详细地址
	ApplyTime            field.Time    // 申请时间
	OrderStatus          field.String  // 订单状态：待发货、已发货、待签收、已完成、已取消、已退款
	ActualPayment        field.Float64 // 实付款金额
	PayTime              field.Time    // 支付时间
	TransactionID        field.String  // 微信交易号
	RefundReason         field.String  // 退款原因
	RefundTime           field.Time    // 退款时间
	PaymentType          field.String  // 收款账户

	fieldMap map[string]field.Expr
}

func (p purchasePoleApplicationTbl) Table(newTableName string) *purchasePoleApplicationTbl {
	p.purchasePoleApplicationTblDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p purchasePoleApplicationTbl) As(alias string) *purchasePoleApplicationTbl {
	p.purchasePoleApplicationTblDo.DO = *(p.purchasePoleApplicationTblDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *purchasePoleApplicationTbl) updateTableName(table string) *purchasePoleApplicationTbl {
	p.ALL = field.NewAsterisk(table)
	p.OrderNumber = field.NewString(table, "order_number")
	p.Openid = field.NewString(table, "openid")
	p.Name = field.NewString(table, "name")
	p.IDNumber = field.NewString(table, "id_number")
	p.PhoneNumber = field.NewString(table, "phone_number")
	p.SelectedPackage = field.NewString(table, "selected_package")
	p.SelectedColor = field.NewString(table, "selected_color")
	p.InstallationDistance = field.NewFloat64(table, "installation_distance")
	p.InstallationDate = field.NewString(table, "installation_date")
	p.UsageScenario = field.NewString(table, "usage_scenario")
	p.InstallationAddress = field.NewString(table, "installation_address")
	p.DetailedAddress = field.NewString(table, "detailed_address")
	p.ApplyTime = field.NewTime(table, "apply_time")
	p.OrderStatus = field.NewString(table, "order_status")
	p.ActualPayment = field.NewFloat64(table, "actual_payment")
	p.PayTime = field.NewTime(table, "pay_time")
	p.TransactionID = field.NewString(table, "transaction_id")
	p.RefundReason = field.NewString(table, "refund_reason")
	p.RefundTime = field.NewTime(table, "refund_time")
	p.PaymentType = field.NewString(table, "payment_type")

	p.fillFieldMap()

	return p
}

func (p *purchasePoleApplicationTbl) WithContext(ctx context.Context) IPurchasePoleApplicationTblDo {
	return p.purchasePoleApplicationTblDo.WithContext(ctx)
}

func (p purchasePoleApplicationTbl) TableName() string {
	return p.purchasePoleApplicationTblDo.TableName()
}

func (p purchasePoleApplicationTbl) Alias() string { return p.purchasePoleApplicationTblDo.Alias() }

func (p purchasePoleApplicationTbl) Columns(cols ...field.Expr) gen.Columns {
	return p.purchasePoleApplicationTblDo.Columns(cols...)
}

func (p *purchasePoleApplicationTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *purchasePoleApplicationTbl) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 20)
	p.fieldMap["order_number"] = p.OrderNumber
	p.fieldMap["openid"] = p.Openid
	p.fieldMap["name"] = p.Name
	p.fieldMap["id_number"] = p.IDNumber
	p.fieldMap["phone_number"] = p.PhoneNumber
	p.fieldMap["selected_package"] = p.SelectedPackage
	p.fieldMap["selected_color"] = p.SelectedColor
	p.fieldMap["installation_distance"] = p.InstallationDistance
	p.fieldMap["installation_date"] = p.InstallationDate
	p.fieldMap["usage_scenario"] = p.UsageScenario
	p.fieldMap["installation_address"] = p.InstallationAddress
	p.fieldMap["detailed_address"] = p.DetailedAddress
	p.fieldMap["apply_time"] = p.ApplyTime
	p.fieldMap["order_status"] = p.OrderStatus
	p.fieldMap["actual_payment"] = p.ActualPayment
	p.fieldMap["pay_time"] = p.PayTime
	p.fieldMap["transaction_id"] = p.TransactionID
	p.fieldMap["refund_reason"] = p.RefundReason
	p.fieldMap["refund_time"] = p.RefundTime
	p.fieldMap["payment_type"] = p.PaymentType
}

func (p purchasePoleApplicationTbl) clone(db *gorm.DB) purchasePoleApplicationTbl {
	p.purchasePoleApplicationTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p purchasePoleApplicationTbl) replaceDB(db *gorm.DB) purchasePoleApplicationTbl {
	p.purchasePoleApplicationTblDo.ReplaceDB(db)
	return p
}

type purchasePoleApplicationTblDo struct{ gen.DO }

type IPurchasePoleApplicationTblDo interface {
	gen.SubQuery
	Debug() IPurchasePoleApplicationTblDo
	WithContext(ctx context.Context) IPurchasePoleApplicationTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPurchasePoleApplicationTblDo
	WriteDB() IPurchasePoleApplicationTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPurchasePoleApplicationTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPurchasePoleApplicationTblDo
	Not(conds ...gen.Condition) IPurchasePoleApplicationTblDo
	Or(conds ...gen.Condition) IPurchasePoleApplicationTblDo
	Select(conds ...field.Expr) IPurchasePoleApplicationTblDo
	Where(conds ...gen.Condition) IPurchasePoleApplicationTblDo
	Order(conds ...field.Expr) IPurchasePoleApplicationTblDo
	Distinct(cols ...field.Expr) IPurchasePoleApplicationTblDo
	Omit(cols ...field.Expr) IPurchasePoleApplicationTblDo
	Join(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo
	Group(cols ...field.Expr) IPurchasePoleApplicationTblDo
	Having(conds ...gen.Condition) IPurchasePoleApplicationTblDo
	Limit(limit int) IPurchasePoleApplicationTblDo
	Offset(offset int) IPurchasePoleApplicationTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPurchasePoleApplicationTblDo
	Unscoped() IPurchasePoleApplicationTblDo
	Create(values ...*model.PurchasePoleApplicationTbl) error
	CreateInBatches(values []*model.PurchasePoleApplicationTbl, batchSize int) error
	Save(values ...*model.PurchasePoleApplicationTbl) error
	First() (*model.PurchasePoleApplicationTbl, error)
	Take() (*model.PurchasePoleApplicationTbl, error)
	Last() (*model.PurchasePoleApplicationTbl, error)
	Find() ([]*model.PurchasePoleApplicationTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PurchasePoleApplicationTbl, err error)
	FindInBatches(result *[]*model.PurchasePoleApplicationTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PurchasePoleApplicationTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPurchasePoleApplicationTblDo
	Assign(attrs ...field.AssignExpr) IPurchasePoleApplicationTblDo
	Joins(fields ...field.RelationField) IPurchasePoleApplicationTblDo
	Preload(fields ...field.RelationField) IPurchasePoleApplicationTblDo
	FirstOrInit() (*model.PurchasePoleApplicationTbl, error)
	FirstOrCreate() (*model.PurchasePoleApplicationTbl, error)
	FindByPage(offset int, limit int) (result []*model.PurchasePoleApplicationTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPurchasePoleApplicationTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p purchasePoleApplicationTblDo) Debug() IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Debug())
}

func (p purchasePoleApplicationTblDo) WithContext(ctx context.Context) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p purchasePoleApplicationTblDo) ReadDB() IPurchasePoleApplicationTblDo {
	return p.Clauses(dbresolver.Read)
}

func (p purchasePoleApplicationTblDo) WriteDB() IPurchasePoleApplicationTblDo {
	return p.Clauses(dbresolver.Write)
}

func (p purchasePoleApplicationTblDo) Session(config *gorm.Session) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Session(config))
}

func (p purchasePoleApplicationTblDo) Clauses(conds ...clause.Expression) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p purchasePoleApplicationTblDo) Returning(value interface{}, columns ...string) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p purchasePoleApplicationTblDo) Not(conds ...gen.Condition) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p purchasePoleApplicationTblDo) Or(conds ...gen.Condition) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p purchasePoleApplicationTblDo) Select(conds ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p purchasePoleApplicationTblDo) Where(conds ...gen.Condition) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p purchasePoleApplicationTblDo) Order(conds ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p purchasePoleApplicationTblDo) Distinct(cols ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p purchasePoleApplicationTblDo) Omit(cols ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p purchasePoleApplicationTblDo) Join(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p purchasePoleApplicationTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p purchasePoleApplicationTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p purchasePoleApplicationTblDo) Group(cols ...field.Expr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p purchasePoleApplicationTblDo) Having(conds ...gen.Condition) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p purchasePoleApplicationTblDo) Limit(limit int) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p purchasePoleApplicationTblDo) Offset(offset int) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p purchasePoleApplicationTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p purchasePoleApplicationTblDo) Unscoped() IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Unscoped())
}

func (p purchasePoleApplicationTblDo) Create(values ...*model.PurchasePoleApplicationTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p purchasePoleApplicationTblDo) CreateInBatches(values []*model.PurchasePoleApplicationTbl, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p purchasePoleApplicationTblDo) Save(values ...*model.PurchasePoleApplicationTbl) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p purchasePoleApplicationTblDo) First() (*model.PurchasePoleApplicationTbl, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PurchasePoleApplicationTbl), nil
	}
}

func (p purchasePoleApplicationTblDo) Take() (*model.PurchasePoleApplicationTbl, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PurchasePoleApplicationTbl), nil
	}
}

func (p purchasePoleApplicationTblDo) Last() (*model.PurchasePoleApplicationTbl, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PurchasePoleApplicationTbl), nil
	}
}

func (p purchasePoleApplicationTblDo) Find() ([]*model.PurchasePoleApplicationTbl, error) {
	result, err := p.DO.Find()
	return result.([]*model.PurchasePoleApplicationTbl), err
}

func (p purchasePoleApplicationTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PurchasePoleApplicationTbl, err error) {
	buf := make([]*model.PurchasePoleApplicationTbl, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p purchasePoleApplicationTblDo) FindInBatches(result *[]*model.PurchasePoleApplicationTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p purchasePoleApplicationTblDo) Attrs(attrs ...field.AssignExpr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p purchasePoleApplicationTblDo) Assign(attrs ...field.AssignExpr) IPurchasePoleApplicationTblDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p purchasePoleApplicationTblDo) Joins(fields ...field.RelationField) IPurchasePoleApplicationTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p purchasePoleApplicationTblDo) Preload(fields ...field.RelationField) IPurchasePoleApplicationTblDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p purchasePoleApplicationTblDo) FirstOrInit() (*model.PurchasePoleApplicationTbl, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PurchasePoleApplicationTbl), nil
	}
}

func (p purchasePoleApplicationTblDo) FirstOrCreate() (*model.PurchasePoleApplicationTbl, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PurchasePoleApplicationTbl), nil
	}
}

func (p purchasePoleApplicationTblDo) FindByPage(offset int, limit int) (result []*model.PurchasePoleApplicationTbl, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p purchasePoleApplicationTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p purchasePoleApplicationTblDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p purchasePoleApplicationTblDo) Delete(models ...*model.PurchasePoleApplicationTbl) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *purchasePoleApplicationTblDo) withDO(do gen.Dao) *purchasePoleApplicationTblDo {
	p.DO = *do.(*gen.DO)
	return p
}
