// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newRechargeOrderTblSorted(db *gorm.DB, opts ...gen.DOOption) rechargeOrderTblSorted {
	_rechargeOrderTblSorted := rechargeOrderTblSorted{}

	_rechargeOrderTblSorted.rechargeOrderTblSortedDo.UseDB(db, opts...)
	_rechargeOrderTblSorted.rechargeOrderTblSortedDo.UseModel(&model.RechargeOrderTblSorted{})

	tableName := _rechargeOrderTblSorted.rechargeOrderTblSortedDo.TableName()
	_rechargeOrderTblSorted.ALL = field.NewAsterisk(tableName)
	_rechargeOrderTblSorted.OrderID = field.NewString(tableName, "order_id")
	_rechargeOrderTblSorted.Openid = field.NewString(tableName, "openid")
	_rechargeOrderTblSorted.RechargeAmount = field.NewFloat64(tableName, "recharge_amount")
	_rechargeOrderTblSorted.RefundedAmount = field.NewFloat64(tableName, "refunded_amount")
	_rechargeOrderTblSorted.RemainingRefundAmount = field.NewFloat64(tableName, "remaining_refund_amount")
	_rechargeOrderTblSorted.OrderStatus = field.NewString(tableName, "order_status")
	_rechargeOrderTblSorted.CreateTime = field.NewTime(tableName, "create_time")
	_rechargeOrderTblSorted.UpdateTime = field.NewTime(tableName, "update_time")
	_rechargeOrderTblSorted.PaymentTime = field.NewTime(tableName, "payment_time")
	_rechargeOrderTblSorted.RefundTime = field.NewTime(tableName, "refund_time")
	_rechargeOrderTblSorted.RefundCount = field.NewInt32(tableName, "refund_count")
	_rechargeOrderTblSorted.MaxRefundAmount = field.NewFloat64(tableName, "max_refund_amount")
	_rechargeOrderTblSorted.RefundApplyCount = field.NewInt32(tableName, "refund_apply_count")
	_rechargeOrderTblSorted.WechatTransactionID = field.NewString(tableName, "wechat_transaction_id")

	_rechargeOrderTblSorted.fillFieldMap()

	return _rechargeOrderTblSorted
}

// rechargeOrderTblSorted VIEW
type rechargeOrderTblSorted struct {
	rechargeOrderTblSortedDo rechargeOrderTblSortedDo

	ALL                   field.Asterisk
	OrderID               field.String  // 充值订单号
	Openid                field.String  // 用户openid
	RechargeAmount        field.Float64 // 充值金额
	RefundedAmount        field.Float64 // 已退款金额
	RemainingRefundAmount field.Float64 // 剩余可退金额
	OrderStatus           field.String  // 订单状态（待支付、已支付、已退款、已关闭）
	CreateTime            field.Time    // 创建时间
	UpdateTime            field.Time    // 更新时间
	PaymentTime           field.Time    // 支付时间
	RefundTime            field.Time    // 退款时间
	RefundCount           field.Int32   // 退款次数
	MaxRefundAmount       field.Float64 // 最大可退金额
	RefundApplyCount      field.Int32   // 退款申请次数
	WechatTransactionID   field.String  // 微信支付交易号

	fieldMap map[string]field.Expr
}

func (r rechargeOrderTblSorted) Table(newTableName string) *rechargeOrderTblSorted {
	r.rechargeOrderTblSortedDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rechargeOrderTblSorted) As(alias string) *rechargeOrderTblSorted {
	r.rechargeOrderTblSortedDo.DO = *(r.rechargeOrderTblSortedDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rechargeOrderTblSorted) updateTableName(table string) *rechargeOrderTblSorted {
	r.ALL = field.NewAsterisk(table)
	r.OrderID = field.NewString(table, "order_id")
	r.Openid = field.NewString(table, "openid")
	r.RechargeAmount = field.NewFloat64(table, "recharge_amount")
	r.RefundedAmount = field.NewFloat64(table, "refunded_amount")
	r.RemainingRefundAmount = field.NewFloat64(table, "remaining_refund_amount")
	r.OrderStatus = field.NewString(table, "order_status")
	r.CreateTime = field.NewTime(table, "create_time")
	r.UpdateTime = field.NewTime(table, "update_time")
	r.PaymentTime = field.NewTime(table, "payment_time")
	r.RefundTime = field.NewTime(table, "refund_time")
	r.RefundCount = field.NewInt32(table, "refund_count")
	r.MaxRefundAmount = field.NewFloat64(table, "max_refund_amount")
	r.RefundApplyCount = field.NewInt32(table, "refund_apply_count")
	r.WechatTransactionID = field.NewString(table, "wechat_transaction_id")

	r.fillFieldMap()

	return r
}

func (r *rechargeOrderTblSorted) WithContext(ctx context.Context) IRechargeOrderTblSortedDo {
	return r.rechargeOrderTblSortedDo.WithContext(ctx)
}

func (r rechargeOrderTblSorted) TableName() string { return r.rechargeOrderTblSortedDo.TableName() }

func (r rechargeOrderTblSorted) Alias() string { return r.rechargeOrderTblSortedDo.Alias() }

func (r rechargeOrderTblSorted) Columns(cols ...field.Expr) gen.Columns {
	return r.rechargeOrderTblSortedDo.Columns(cols...)
}

func (r *rechargeOrderTblSorted) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rechargeOrderTblSorted) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["order_id"] = r.OrderID
	r.fieldMap["openid"] = r.Openid
	r.fieldMap["recharge_amount"] = r.RechargeAmount
	r.fieldMap["refunded_amount"] = r.RefundedAmount
	r.fieldMap["remaining_refund_amount"] = r.RemainingRefundAmount
	r.fieldMap["order_status"] = r.OrderStatus
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["update_time"] = r.UpdateTime
	r.fieldMap["payment_time"] = r.PaymentTime
	r.fieldMap["refund_time"] = r.RefundTime
	r.fieldMap["refund_count"] = r.RefundCount
	r.fieldMap["max_refund_amount"] = r.MaxRefundAmount
	r.fieldMap["refund_apply_count"] = r.RefundApplyCount
	r.fieldMap["wechat_transaction_id"] = r.WechatTransactionID
}

func (r rechargeOrderTblSorted) clone(db *gorm.DB) rechargeOrderTblSorted {
	r.rechargeOrderTblSortedDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rechargeOrderTblSorted) replaceDB(db *gorm.DB) rechargeOrderTblSorted {
	r.rechargeOrderTblSortedDo.ReplaceDB(db)
	return r
}

type rechargeOrderTblSortedDo struct{ gen.DO }

type IRechargeOrderTblSortedDo interface {
	gen.SubQuery
	Debug() IRechargeOrderTblSortedDo
	WithContext(ctx context.Context) IRechargeOrderTblSortedDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRechargeOrderTblSortedDo
	WriteDB() IRechargeOrderTblSortedDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRechargeOrderTblSortedDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRechargeOrderTblSortedDo
	Not(conds ...gen.Condition) IRechargeOrderTblSortedDo
	Or(conds ...gen.Condition) IRechargeOrderTblSortedDo
	Select(conds ...field.Expr) IRechargeOrderTblSortedDo
	Where(conds ...gen.Condition) IRechargeOrderTblSortedDo
	Order(conds ...field.Expr) IRechargeOrderTblSortedDo
	Distinct(cols ...field.Expr) IRechargeOrderTblSortedDo
	Omit(cols ...field.Expr) IRechargeOrderTblSortedDo
	Join(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo
	Group(cols ...field.Expr) IRechargeOrderTblSortedDo
	Having(conds ...gen.Condition) IRechargeOrderTblSortedDo
	Limit(limit int) IRechargeOrderTblSortedDo
	Offset(offset int) IRechargeOrderTblSortedDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRechargeOrderTblSortedDo
	Unscoped() IRechargeOrderTblSortedDo
	Create(values ...*model.RechargeOrderTblSorted) error
	CreateInBatches(values []*model.RechargeOrderTblSorted, batchSize int) error
	Save(values ...*model.RechargeOrderTblSorted) error
	First() (*model.RechargeOrderTblSorted, error)
	Take() (*model.RechargeOrderTblSorted, error)
	Last() (*model.RechargeOrderTblSorted, error)
	Find() ([]*model.RechargeOrderTblSorted, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RechargeOrderTblSorted, err error)
	FindInBatches(result *[]*model.RechargeOrderTblSorted, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RechargeOrderTblSorted) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRechargeOrderTblSortedDo
	Assign(attrs ...field.AssignExpr) IRechargeOrderTblSortedDo
	Joins(fields ...field.RelationField) IRechargeOrderTblSortedDo
	Preload(fields ...field.RelationField) IRechargeOrderTblSortedDo
	FirstOrInit() (*model.RechargeOrderTblSorted, error)
	FirstOrCreate() (*model.RechargeOrderTblSorted, error)
	FindByPage(offset int, limit int) (result []*model.RechargeOrderTblSorted, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRechargeOrderTblSortedDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rechargeOrderTblSortedDo) Debug() IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Debug())
}

func (r rechargeOrderTblSortedDo) WithContext(ctx context.Context) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rechargeOrderTblSortedDo) ReadDB() IRechargeOrderTblSortedDo {
	return r.Clauses(dbresolver.Read)
}

func (r rechargeOrderTblSortedDo) WriteDB() IRechargeOrderTblSortedDo {
	return r.Clauses(dbresolver.Write)
}

func (r rechargeOrderTblSortedDo) Session(config *gorm.Session) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Session(config))
}

func (r rechargeOrderTblSortedDo) Clauses(conds ...clause.Expression) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rechargeOrderTblSortedDo) Returning(value interface{}, columns ...string) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rechargeOrderTblSortedDo) Not(conds ...gen.Condition) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rechargeOrderTblSortedDo) Or(conds ...gen.Condition) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rechargeOrderTblSortedDo) Select(conds ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rechargeOrderTblSortedDo) Where(conds ...gen.Condition) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rechargeOrderTblSortedDo) Order(conds ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rechargeOrderTblSortedDo) Distinct(cols ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rechargeOrderTblSortedDo) Omit(cols ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rechargeOrderTblSortedDo) Join(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rechargeOrderTblSortedDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rechargeOrderTblSortedDo) RightJoin(table schema.Tabler, on ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rechargeOrderTblSortedDo) Group(cols ...field.Expr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rechargeOrderTblSortedDo) Having(conds ...gen.Condition) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rechargeOrderTblSortedDo) Limit(limit int) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rechargeOrderTblSortedDo) Offset(offset int) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rechargeOrderTblSortedDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rechargeOrderTblSortedDo) Unscoped() IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rechargeOrderTblSortedDo) Create(values ...*model.RechargeOrderTblSorted) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rechargeOrderTblSortedDo) CreateInBatches(values []*model.RechargeOrderTblSorted, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rechargeOrderTblSortedDo) Save(values ...*model.RechargeOrderTblSorted) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rechargeOrderTblSortedDo) First() (*model.RechargeOrderTblSorted, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RechargeOrderTblSorted), nil
	}
}

func (r rechargeOrderTblSortedDo) Take() (*model.RechargeOrderTblSorted, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RechargeOrderTblSorted), nil
	}
}

func (r rechargeOrderTblSortedDo) Last() (*model.RechargeOrderTblSorted, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RechargeOrderTblSorted), nil
	}
}

func (r rechargeOrderTblSortedDo) Find() ([]*model.RechargeOrderTblSorted, error) {
	result, err := r.DO.Find()
	return result.([]*model.RechargeOrderTblSorted), err
}

func (r rechargeOrderTblSortedDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RechargeOrderTblSorted, err error) {
	buf := make([]*model.RechargeOrderTblSorted, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rechargeOrderTblSortedDo) FindInBatches(result *[]*model.RechargeOrderTblSorted, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rechargeOrderTblSortedDo) Attrs(attrs ...field.AssignExpr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rechargeOrderTblSortedDo) Assign(attrs ...field.AssignExpr) IRechargeOrderTblSortedDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rechargeOrderTblSortedDo) Joins(fields ...field.RelationField) IRechargeOrderTblSortedDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rechargeOrderTblSortedDo) Preload(fields ...field.RelationField) IRechargeOrderTblSortedDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rechargeOrderTblSortedDo) FirstOrInit() (*model.RechargeOrderTblSorted, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RechargeOrderTblSorted), nil
	}
}

func (r rechargeOrderTblSortedDo) FirstOrCreate() (*model.RechargeOrderTblSorted, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RechargeOrderTblSorted), nil
	}
}

func (r rechargeOrderTblSortedDo) FindByPage(offset int, limit int) (result []*model.RechargeOrderTblSorted, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rechargeOrderTblSortedDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rechargeOrderTblSortedDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rechargeOrderTblSortedDo) Delete(models ...*model.RechargeOrderTblSorted) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rechargeOrderTblSortedDo) withDO(do gen.Dao) *rechargeOrderTblSortedDo {
	r.DO = *do.(*gen.DO)
	return r
}
