// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newShopStaffTbl(db *gorm.DB, opts ...gen.DOOption) shopStaffTbl {
	_shopStaffTbl := shopStaffTbl{}

	_shopStaffTbl.shopStaffTblDo.UseDB(db, opts...)
	_shopStaffTbl.shopStaffTblDo.UseModel(&model.ShopStaffTbl{})

	tableName := _shopStaffTbl.shopStaffTblDo.TableName()
	_shopStaffTbl.ALL = field.NewAsterisk(tableName)
	_shopStaffTbl.ID = field.NewInt32(tableName, "id")
	_shopStaffTbl.OpenID = field.NewString(tableName, "openId")
	_shopStaffTbl.ShopID = field.NewString(tableName, "shopId")
	_shopStaffTbl.Dust = field.NewString(tableName, "dust")
	_shopStaffTbl.Name = field.NewString(tableName, "name")
	_shopStaffTbl.Age = field.NewString(tableName, "age")
	_shopStaffTbl.Number = field.NewString(tableName, "number")
	_shopStaffTbl.CreatTime = field.NewString(tableName, "creatTime")
	_shopStaffTbl.Email = field.NewString(tableName, "email")
	_shopStaffTbl.Phone = field.NewString(tableName, "phone")
	_shopStaffTbl.Icon = field.NewString(tableName, "icon")
	_shopStaffTbl.LockPermissions = field.NewString(tableName, "lockPermissions")

	_shopStaffTbl.fillFieldMap()

	return _shopStaffTbl
}

type shopStaffTbl struct {
	shopStaffTblDo shopStaffTblDo

	ALL             field.Asterisk
	ID              field.Int32  // 与逻辑无关主键
	OpenID          field.String // 用户id
	ShopID          field.String // 商铺的id
	Dust            field.String
	Name            field.String
	Age             field.String // 年纪
	Number          field.String // 编号
	CreatTime       field.String // 入职时间
	Email           field.String // 电子邮件
	Phone           field.String // 手机
	Icon            field.String // 头像
	LockPermissions field.String // 0代表没有开锁权限，1代表有

	fieldMap map[string]field.Expr
}

func (s shopStaffTbl) Table(newTableName string) *shopStaffTbl {
	s.shopStaffTblDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shopStaffTbl) As(alias string) *shopStaffTbl {
	s.shopStaffTblDo.DO = *(s.shopStaffTblDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shopStaffTbl) updateTableName(table string) *shopStaffTbl {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.OpenID = field.NewString(table, "openId")
	s.ShopID = field.NewString(table, "shopId")
	s.Dust = field.NewString(table, "dust")
	s.Name = field.NewString(table, "name")
	s.Age = field.NewString(table, "age")
	s.Number = field.NewString(table, "number")
	s.CreatTime = field.NewString(table, "creatTime")
	s.Email = field.NewString(table, "email")
	s.Phone = field.NewString(table, "phone")
	s.Icon = field.NewString(table, "icon")
	s.LockPermissions = field.NewString(table, "lockPermissions")

	s.fillFieldMap()

	return s
}

func (s *shopStaffTbl) WithContext(ctx context.Context) IShopStaffTblDo {
	return s.shopStaffTblDo.WithContext(ctx)
}

func (s shopStaffTbl) TableName() string { return s.shopStaffTblDo.TableName() }

func (s shopStaffTbl) Alias() string { return s.shopStaffTblDo.Alias() }

func (s shopStaffTbl) Columns(cols ...field.Expr) gen.Columns {
	return s.shopStaffTblDo.Columns(cols...)
}

func (s *shopStaffTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shopStaffTbl) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["openId"] = s.OpenID
	s.fieldMap["shopId"] = s.ShopID
	s.fieldMap["dust"] = s.Dust
	s.fieldMap["name"] = s.Name
	s.fieldMap["age"] = s.Age
	s.fieldMap["number"] = s.Number
	s.fieldMap["creatTime"] = s.CreatTime
	s.fieldMap["email"] = s.Email
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["lockPermissions"] = s.LockPermissions
}

func (s shopStaffTbl) clone(db *gorm.DB) shopStaffTbl {
	s.shopStaffTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shopStaffTbl) replaceDB(db *gorm.DB) shopStaffTbl {
	s.shopStaffTblDo.ReplaceDB(db)
	return s
}

type shopStaffTblDo struct{ gen.DO }

type IShopStaffTblDo interface {
	gen.SubQuery
	Debug() IShopStaffTblDo
	WithContext(ctx context.Context) IShopStaffTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShopStaffTblDo
	WriteDB() IShopStaffTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShopStaffTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShopStaffTblDo
	Not(conds ...gen.Condition) IShopStaffTblDo
	Or(conds ...gen.Condition) IShopStaffTblDo
	Select(conds ...field.Expr) IShopStaffTblDo
	Where(conds ...gen.Condition) IShopStaffTblDo
	Order(conds ...field.Expr) IShopStaffTblDo
	Distinct(cols ...field.Expr) IShopStaffTblDo
	Omit(cols ...field.Expr) IShopStaffTblDo
	Join(table schema.Tabler, on ...field.Expr) IShopStaffTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShopStaffTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShopStaffTblDo
	Group(cols ...field.Expr) IShopStaffTblDo
	Having(conds ...gen.Condition) IShopStaffTblDo
	Limit(limit int) IShopStaffTblDo
	Offset(offset int) IShopStaffTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShopStaffTblDo
	Unscoped() IShopStaffTblDo
	Create(values ...*model.ShopStaffTbl) error
	CreateInBatches(values []*model.ShopStaffTbl, batchSize int) error
	Save(values ...*model.ShopStaffTbl) error
	First() (*model.ShopStaffTbl, error)
	Take() (*model.ShopStaffTbl, error)
	Last() (*model.ShopStaffTbl, error)
	Find() ([]*model.ShopStaffTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShopStaffTbl, err error)
	FindInBatches(result *[]*model.ShopStaffTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ShopStaffTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShopStaffTblDo
	Assign(attrs ...field.AssignExpr) IShopStaffTblDo
	Joins(fields ...field.RelationField) IShopStaffTblDo
	Preload(fields ...field.RelationField) IShopStaffTblDo
	FirstOrInit() (*model.ShopStaffTbl, error)
	FirstOrCreate() (*model.ShopStaffTbl, error)
	FindByPage(offset int, limit int) (result []*model.ShopStaffTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShopStaffTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shopStaffTblDo) Debug() IShopStaffTblDo {
	return s.withDO(s.DO.Debug())
}

func (s shopStaffTblDo) WithContext(ctx context.Context) IShopStaffTblDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shopStaffTblDo) ReadDB() IShopStaffTblDo {
	return s.Clauses(dbresolver.Read)
}

func (s shopStaffTblDo) WriteDB() IShopStaffTblDo {
	return s.Clauses(dbresolver.Write)
}

func (s shopStaffTblDo) Session(config *gorm.Session) IShopStaffTblDo {
	return s.withDO(s.DO.Session(config))
}

func (s shopStaffTblDo) Clauses(conds ...clause.Expression) IShopStaffTblDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shopStaffTblDo) Returning(value interface{}, columns ...string) IShopStaffTblDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shopStaffTblDo) Not(conds ...gen.Condition) IShopStaffTblDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shopStaffTblDo) Or(conds ...gen.Condition) IShopStaffTblDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shopStaffTblDo) Select(conds ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shopStaffTblDo) Where(conds ...gen.Condition) IShopStaffTblDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shopStaffTblDo) Order(conds ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shopStaffTblDo) Distinct(cols ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shopStaffTblDo) Omit(cols ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shopStaffTblDo) Join(table schema.Tabler, on ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shopStaffTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shopStaffTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shopStaffTblDo) Group(cols ...field.Expr) IShopStaffTblDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shopStaffTblDo) Having(conds ...gen.Condition) IShopStaffTblDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shopStaffTblDo) Limit(limit int) IShopStaffTblDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shopStaffTblDo) Offset(offset int) IShopStaffTblDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shopStaffTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShopStaffTblDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shopStaffTblDo) Unscoped() IShopStaffTblDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shopStaffTblDo) Create(values ...*model.ShopStaffTbl) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shopStaffTblDo) CreateInBatches(values []*model.ShopStaffTbl, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shopStaffTblDo) Save(values ...*model.ShopStaffTbl) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shopStaffTblDo) First() (*model.ShopStaffTbl, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopStaffTbl), nil
	}
}

func (s shopStaffTblDo) Take() (*model.ShopStaffTbl, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopStaffTbl), nil
	}
}

func (s shopStaffTblDo) Last() (*model.ShopStaffTbl, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopStaffTbl), nil
	}
}

func (s shopStaffTblDo) Find() ([]*model.ShopStaffTbl, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShopStaffTbl), err
}

func (s shopStaffTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShopStaffTbl, err error) {
	buf := make([]*model.ShopStaffTbl, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shopStaffTblDo) FindInBatches(result *[]*model.ShopStaffTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shopStaffTblDo) Attrs(attrs ...field.AssignExpr) IShopStaffTblDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shopStaffTblDo) Assign(attrs ...field.AssignExpr) IShopStaffTblDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shopStaffTblDo) Joins(fields ...field.RelationField) IShopStaffTblDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shopStaffTblDo) Preload(fields ...field.RelationField) IShopStaffTblDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shopStaffTblDo) FirstOrInit() (*model.ShopStaffTbl, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopStaffTbl), nil
	}
}

func (s shopStaffTblDo) FirstOrCreate() (*model.ShopStaffTbl, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopStaffTbl), nil
	}
}

func (s shopStaffTblDo) FindByPage(offset int, limit int) (result []*model.ShopStaffTbl, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shopStaffTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shopStaffTblDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shopStaffTblDo) Delete(models ...*model.ShopStaffTbl) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shopStaffTblDo) withDO(do gen.Dao) *shopStaffTblDo {
	s.DO = *do.(*gen.DO)
	return s
}
