// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newTabProduct(db *gorm.DB, opts ...gen.DOOption) tabProduct {
	_tabProduct := tabProduct{}

	_tabProduct.tabProductDo.UseDB(db, opts...)
	_tabProduct.tabProductDo.UseModel(&model.TabProduct{})

	tableName := _tabProduct.tabProductDo.TableName()
	_tabProduct.ALL = field.NewAsterisk(tableName)
	_tabProduct.Pid = field.NewString(tableName, "pid")
	_tabProduct.Nid = field.NewString(tableName, "nid")
	_tabProduct.Imei = field.NewString(tableName, "Imei")
	_tabProduct.GatewayID = field.NewInt32(tableName, "gateway_id")
	_tabProduct.Environment = field.NewString(tableName, "environment")
	_tabProduct.ProductionTime = field.NewTime(tableName, "production_time")
	_tabProduct.IsTwicecar = field.NewInt32(tableName, "is_twicecar")
	_tabProduct.HasCpLine = field.NewInt32(tableName, "has_cp_line")

	_tabProduct.fillFieldMap()

	return _tabProduct
}

// tabProduct 产品
type tabProduct struct {
	tabProductDo tabProductDo

	ALL            field.Asterisk
	Pid            field.String // 产品id
	Nid            field.String // 设备id
	Imei           field.String // 4G通讯的唯一标识
	GatewayID      field.Int32  // 设备所在网关id
	Environment    field.String // 适用环境
	ProductionTime field.Time   // 生产日期
	IsTwicecar     field.Int32  // 是否为二轮车充电站
	HasCpLine      field.Int32  // 是否有CP线

	fieldMap map[string]field.Expr
}

func (t tabProduct) Table(newTableName string) *tabProduct {
	t.tabProductDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tabProduct) As(alias string) *tabProduct {
	t.tabProductDo.DO = *(t.tabProductDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tabProduct) updateTableName(table string) *tabProduct {
	t.ALL = field.NewAsterisk(table)
	t.Pid = field.NewString(table, "pid")
	t.Nid = field.NewString(table, "nid")
	t.Imei = field.NewString(table, "Imei")
	t.GatewayID = field.NewInt32(table, "gateway_id")
	t.Environment = field.NewString(table, "environment")
	t.ProductionTime = field.NewTime(table, "production_time")
	t.IsTwicecar = field.NewInt32(table, "is_twicecar")
	t.HasCpLine = field.NewInt32(table, "has_cp_line")

	t.fillFieldMap()

	return t
}

func (t *tabProduct) WithContext(ctx context.Context) ITabProductDo {
	return t.tabProductDo.WithContext(ctx)
}

func (t tabProduct) TableName() string { return t.tabProductDo.TableName() }

func (t tabProduct) Alias() string { return t.tabProductDo.Alias() }

func (t tabProduct) Columns(cols ...field.Expr) gen.Columns { return t.tabProductDo.Columns(cols...) }

func (t *tabProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tabProduct) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["pid"] = t.Pid
	t.fieldMap["nid"] = t.Nid
	t.fieldMap["Imei"] = t.Imei
	t.fieldMap["gateway_id"] = t.GatewayID
	t.fieldMap["environment"] = t.Environment
	t.fieldMap["production_time"] = t.ProductionTime
	t.fieldMap["is_twicecar"] = t.IsTwicecar
	t.fieldMap["has_cp_line"] = t.HasCpLine
}

func (t tabProduct) clone(db *gorm.DB) tabProduct {
	t.tabProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tabProduct) replaceDB(db *gorm.DB) tabProduct {
	t.tabProductDo.ReplaceDB(db)
	return t
}

type tabProductDo struct{ gen.DO }

type ITabProductDo interface {
	gen.SubQuery
	Debug() ITabProductDo
	WithContext(ctx context.Context) ITabProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITabProductDo
	WriteDB() ITabProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITabProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITabProductDo
	Not(conds ...gen.Condition) ITabProductDo
	Or(conds ...gen.Condition) ITabProductDo
	Select(conds ...field.Expr) ITabProductDo
	Where(conds ...gen.Condition) ITabProductDo
	Order(conds ...field.Expr) ITabProductDo
	Distinct(cols ...field.Expr) ITabProductDo
	Omit(cols ...field.Expr) ITabProductDo
	Join(table schema.Tabler, on ...field.Expr) ITabProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITabProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITabProductDo
	Group(cols ...field.Expr) ITabProductDo
	Having(conds ...gen.Condition) ITabProductDo
	Limit(limit int) ITabProductDo
	Offset(offset int) ITabProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITabProductDo
	Unscoped() ITabProductDo
	Create(values ...*model.TabProduct) error
	CreateInBatches(values []*model.TabProduct, batchSize int) error
	Save(values ...*model.TabProduct) error
	First() (*model.TabProduct, error)
	Take() (*model.TabProduct, error)
	Last() (*model.TabProduct, error)
	Find() ([]*model.TabProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabProduct, err error)
	FindInBatches(result *[]*model.TabProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TabProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITabProductDo
	Assign(attrs ...field.AssignExpr) ITabProductDo
	Joins(fields ...field.RelationField) ITabProductDo
	Preload(fields ...field.RelationField) ITabProductDo
	FirstOrInit() (*model.TabProduct, error)
	FirstOrCreate() (*model.TabProduct, error)
	FindByPage(offset int, limit int) (result []*model.TabProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITabProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tabProductDo) Debug() ITabProductDo {
	return t.withDO(t.DO.Debug())
}

func (t tabProductDo) WithContext(ctx context.Context) ITabProductDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tabProductDo) ReadDB() ITabProductDo {
	return t.Clauses(dbresolver.Read)
}

func (t tabProductDo) WriteDB() ITabProductDo {
	return t.Clauses(dbresolver.Write)
}

func (t tabProductDo) Session(config *gorm.Session) ITabProductDo {
	return t.withDO(t.DO.Session(config))
}

func (t tabProductDo) Clauses(conds ...clause.Expression) ITabProductDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tabProductDo) Returning(value interface{}, columns ...string) ITabProductDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tabProductDo) Not(conds ...gen.Condition) ITabProductDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tabProductDo) Or(conds ...gen.Condition) ITabProductDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tabProductDo) Select(conds ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tabProductDo) Where(conds ...gen.Condition) ITabProductDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tabProductDo) Order(conds ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tabProductDo) Distinct(cols ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tabProductDo) Omit(cols ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tabProductDo) Join(table schema.Tabler, on ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tabProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tabProductDo) RightJoin(table schema.Tabler, on ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tabProductDo) Group(cols ...field.Expr) ITabProductDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tabProductDo) Having(conds ...gen.Condition) ITabProductDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tabProductDo) Limit(limit int) ITabProductDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tabProductDo) Offset(offset int) ITabProductDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tabProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITabProductDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tabProductDo) Unscoped() ITabProductDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tabProductDo) Create(values ...*model.TabProduct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tabProductDo) CreateInBatches(values []*model.TabProduct, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tabProductDo) Save(values ...*model.TabProduct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tabProductDo) First() (*model.TabProduct, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabProduct), nil
	}
}

func (t tabProductDo) Take() (*model.TabProduct, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabProduct), nil
	}
}

func (t tabProductDo) Last() (*model.TabProduct, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabProduct), nil
	}
}

func (t tabProductDo) Find() ([]*model.TabProduct, error) {
	result, err := t.DO.Find()
	return result.([]*model.TabProduct), err
}

func (t tabProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabProduct, err error) {
	buf := make([]*model.TabProduct, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tabProductDo) FindInBatches(result *[]*model.TabProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tabProductDo) Attrs(attrs ...field.AssignExpr) ITabProductDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tabProductDo) Assign(attrs ...field.AssignExpr) ITabProductDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tabProductDo) Joins(fields ...field.RelationField) ITabProductDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tabProductDo) Preload(fields ...field.RelationField) ITabProductDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tabProductDo) FirstOrInit() (*model.TabProduct, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabProduct), nil
	}
}

func (t tabProductDo) FirstOrCreate() (*model.TabProduct, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabProduct), nil
	}
}

func (t tabProductDo) FindByPage(offset int, limit int) (result []*model.TabProduct, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tabProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tabProductDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tabProductDo) Delete(models ...*model.TabProduct) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tabProductDo) withDO(do gen.Dao) *tabProductDo {
	t.DO = *do.(*gen.DO)
	return t
}
