// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newTabVideo(db *gorm.DB, opts ...gen.DOOption) tabVideo {
	_tabVideo := tabVideo{}

	_tabVideo.tabVideoDo.UseDB(db, opts...)
	_tabVideo.tabVideoDo.UseModel(&model.TabVideo{})

	tableName := _tabVideo.tabVideoDo.TableName()
	_tabVideo.ALL = field.NewAsterisk(tableName)
	_tabVideo.ID = field.NewInt32(tableName, "id")
	_tabVideo.FileID = field.NewString(tableName, "file_id")
	_tabVideo.VideoType = field.NewString(tableName, "video_type")
	_tabVideo.UploadTime = field.NewTime(tableName, "upload_time")

	_tabVideo.fillFieldMap()

	return _tabVideo
}

// tabVideo 视频信息表
type tabVideo struct {
	tabVideoDo tabVideoDo

	ALL        field.Asterisk
	ID         field.Int32  // 序号
	FileID     field.String // 文件ID
	VideoType  field.String // 视频类型
	UploadTime field.Time   // 上传时间

	fieldMap map[string]field.Expr
}

func (t tabVideo) Table(newTableName string) *tabVideo {
	t.tabVideoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tabVideo) As(alias string) *tabVideo {
	t.tabVideoDo.DO = *(t.tabVideoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tabVideo) updateTableName(table string) *tabVideo {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.FileID = field.NewString(table, "file_id")
	t.VideoType = field.NewString(table, "video_type")
	t.UploadTime = field.NewTime(table, "upload_time")

	t.fillFieldMap()

	return t
}

func (t *tabVideo) WithContext(ctx context.Context) ITabVideoDo { return t.tabVideoDo.WithContext(ctx) }

func (t tabVideo) TableName() string { return t.tabVideoDo.TableName() }

func (t tabVideo) Alias() string { return t.tabVideoDo.Alias() }

func (t tabVideo) Columns(cols ...field.Expr) gen.Columns { return t.tabVideoDo.Columns(cols...) }

func (t *tabVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tabVideo) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["file_id"] = t.FileID
	t.fieldMap["video_type"] = t.VideoType
	t.fieldMap["upload_time"] = t.UploadTime
}

func (t tabVideo) clone(db *gorm.DB) tabVideo {
	t.tabVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tabVideo) replaceDB(db *gorm.DB) tabVideo {
	t.tabVideoDo.ReplaceDB(db)
	return t
}

type tabVideoDo struct{ gen.DO }

type ITabVideoDo interface {
	gen.SubQuery
	Debug() ITabVideoDo
	WithContext(ctx context.Context) ITabVideoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITabVideoDo
	WriteDB() ITabVideoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITabVideoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITabVideoDo
	Not(conds ...gen.Condition) ITabVideoDo
	Or(conds ...gen.Condition) ITabVideoDo
	Select(conds ...field.Expr) ITabVideoDo
	Where(conds ...gen.Condition) ITabVideoDo
	Order(conds ...field.Expr) ITabVideoDo
	Distinct(cols ...field.Expr) ITabVideoDo
	Omit(cols ...field.Expr) ITabVideoDo
	Join(table schema.Tabler, on ...field.Expr) ITabVideoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITabVideoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITabVideoDo
	Group(cols ...field.Expr) ITabVideoDo
	Having(conds ...gen.Condition) ITabVideoDo
	Limit(limit int) ITabVideoDo
	Offset(offset int) ITabVideoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITabVideoDo
	Unscoped() ITabVideoDo
	Create(values ...*model.TabVideo) error
	CreateInBatches(values []*model.TabVideo, batchSize int) error
	Save(values ...*model.TabVideo) error
	First() (*model.TabVideo, error)
	Take() (*model.TabVideo, error)
	Last() (*model.TabVideo, error)
	Find() ([]*model.TabVideo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabVideo, err error)
	FindInBatches(result *[]*model.TabVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TabVideo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITabVideoDo
	Assign(attrs ...field.AssignExpr) ITabVideoDo
	Joins(fields ...field.RelationField) ITabVideoDo
	Preload(fields ...field.RelationField) ITabVideoDo
	FirstOrInit() (*model.TabVideo, error)
	FirstOrCreate() (*model.TabVideo, error)
	FindByPage(offset int, limit int) (result []*model.TabVideo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITabVideoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tabVideoDo) Debug() ITabVideoDo {
	return t.withDO(t.DO.Debug())
}

func (t tabVideoDo) WithContext(ctx context.Context) ITabVideoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tabVideoDo) ReadDB() ITabVideoDo {
	return t.Clauses(dbresolver.Read)
}

func (t tabVideoDo) WriteDB() ITabVideoDo {
	return t.Clauses(dbresolver.Write)
}

func (t tabVideoDo) Session(config *gorm.Session) ITabVideoDo {
	return t.withDO(t.DO.Session(config))
}

func (t tabVideoDo) Clauses(conds ...clause.Expression) ITabVideoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tabVideoDo) Returning(value interface{}, columns ...string) ITabVideoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tabVideoDo) Not(conds ...gen.Condition) ITabVideoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tabVideoDo) Or(conds ...gen.Condition) ITabVideoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tabVideoDo) Select(conds ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tabVideoDo) Where(conds ...gen.Condition) ITabVideoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tabVideoDo) Order(conds ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tabVideoDo) Distinct(cols ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tabVideoDo) Omit(cols ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tabVideoDo) Join(table schema.Tabler, on ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tabVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tabVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tabVideoDo) Group(cols ...field.Expr) ITabVideoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tabVideoDo) Having(conds ...gen.Condition) ITabVideoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tabVideoDo) Limit(limit int) ITabVideoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tabVideoDo) Offset(offset int) ITabVideoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tabVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITabVideoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tabVideoDo) Unscoped() ITabVideoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tabVideoDo) Create(values ...*model.TabVideo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tabVideoDo) CreateInBatches(values []*model.TabVideo, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tabVideoDo) Save(values ...*model.TabVideo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tabVideoDo) First() (*model.TabVideo, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideo), nil
	}
}

func (t tabVideoDo) Take() (*model.TabVideo, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideo), nil
	}
}

func (t tabVideoDo) Last() (*model.TabVideo, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideo), nil
	}
}

func (t tabVideoDo) Find() ([]*model.TabVideo, error) {
	result, err := t.DO.Find()
	return result.([]*model.TabVideo), err
}

func (t tabVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabVideo, err error) {
	buf := make([]*model.TabVideo, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tabVideoDo) FindInBatches(result *[]*model.TabVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tabVideoDo) Attrs(attrs ...field.AssignExpr) ITabVideoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tabVideoDo) Assign(attrs ...field.AssignExpr) ITabVideoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tabVideoDo) Joins(fields ...field.RelationField) ITabVideoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tabVideoDo) Preload(fields ...field.RelationField) ITabVideoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tabVideoDo) FirstOrInit() (*model.TabVideo, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideo), nil
	}
}

func (t tabVideoDo) FirstOrCreate() (*model.TabVideo, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideo), nil
	}
}

func (t tabVideoDo) FindByPage(offset int, limit int) (result []*model.TabVideo, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tabVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tabVideoDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tabVideoDo) Delete(models ...*model.TabVideo) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tabVideoDo) withDO(do gen.Dao) *tabVideoDo {
	t.DO = *do.(*gen.DO)
	return t
}
