// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newTabVideoWatchRecord(db *gorm.DB, opts ...gen.DOOption) tabVideoWatchRecord {
	_tabVideoWatchRecord := tabVideoWatchRecord{}

	_tabVideoWatchRecord.tabVideoWatchRecordDo.UseDB(db, opts...)
	_tabVideoWatchRecord.tabVideoWatchRecordDo.UseModel(&model.TabVideoWatchRecord{})

	tableName := _tabVideoWatchRecord.tabVideoWatchRecordDo.TableName()
	_tabVideoWatchRecord.ALL = field.NewAsterisk(tableName)
	_tabVideoWatchRecord.ID = field.NewInt32(tableName, "id")
	_tabVideoWatchRecord.FileID = field.NewString(tableName, "file_id")
	_tabVideoWatchRecord.Openid = field.NewString(tableName, "openid")
	_tabVideoWatchRecord.Status = field.NewBool(tableName, "status")
	_tabVideoWatchRecord.WatchTime = field.NewTime(tableName, "watch_time")

	_tabVideoWatchRecord.fillFieldMap()

	return _tabVideoWatchRecord
}

// tabVideoWatchRecord 视频观看记录表
type tabVideoWatchRecord struct {
	tabVideoWatchRecordDo tabVideoWatchRecordDo

	ALL       field.Asterisk
	ID        field.Int32  // 序号
	FileID    field.String // 文件ID
	Openid    field.String // 用户openid
	Status    field.Bool   // 观看状态（1-已观看，0-未观看）
	WatchTime field.Time   // 观看时间

	fieldMap map[string]field.Expr
}

func (t tabVideoWatchRecord) Table(newTableName string) *tabVideoWatchRecord {
	t.tabVideoWatchRecordDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tabVideoWatchRecord) As(alias string) *tabVideoWatchRecord {
	t.tabVideoWatchRecordDo.DO = *(t.tabVideoWatchRecordDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tabVideoWatchRecord) updateTableName(table string) *tabVideoWatchRecord {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.FileID = field.NewString(table, "file_id")
	t.Openid = field.NewString(table, "openid")
	t.Status = field.NewBool(table, "status")
	t.WatchTime = field.NewTime(table, "watch_time")

	t.fillFieldMap()

	return t
}

func (t *tabVideoWatchRecord) WithContext(ctx context.Context) ITabVideoWatchRecordDo {
	return t.tabVideoWatchRecordDo.WithContext(ctx)
}

func (t tabVideoWatchRecord) TableName() string { return t.tabVideoWatchRecordDo.TableName() }

func (t tabVideoWatchRecord) Alias() string { return t.tabVideoWatchRecordDo.Alias() }

func (t tabVideoWatchRecord) Columns(cols ...field.Expr) gen.Columns {
	return t.tabVideoWatchRecordDo.Columns(cols...)
}

func (t *tabVideoWatchRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tabVideoWatchRecord) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["file_id"] = t.FileID
	t.fieldMap["openid"] = t.Openid
	t.fieldMap["status"] = t.Status
	t.fieldMap["watch_time"] = t.WatchTime
}

func (t tabVideoWatchRecord) clone(db *gorm.DB) tabVideoWatchRecord {
	t.tabVideoWatchRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tabVideoWatchRecord) replaceDB(db *gorm.DB) tabVideoWatchRecord {
	t.tabVideoWatchRecordDo.ReplaceDB(db)
	return t
}

type tabVideoWatchRecordDo struct{ gen.DO }

type ITabVideoWatchRecordDo interface {
	gen.SubQuery
	Debug() ITabVideoWatchRecordDo
	WithContext(ctx context.Context) ITabVideoWatchRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITabVideoWatchRecordDo
	WriteDB() ITabVideoWatchRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITabVideoWatchRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITabVideoWatchRecordDo
	Not(conds ...gen.Condition) ITabVideoWatchRecordDo
	Or(conds ...gen.Condition) ITabVideoWatchRecordDo
	Select(conds ...field.Expr) ITabVideoWatchRecordDo
	Where(conds ...gen.Condition) ITabVideoWatchRecordDo
	Order(conds ...field.Expr) ITabVideoWatchRecordDo
	Distinct(cols ...field.Expr) ITabVideoWatchRecordDo
	Omit(cols ...field.Expr) ITabVideoWatchRecordDo
	Join(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo
	Group(cols ...field.Expr) ITabVideoWatchRecordDo
	Having(conds ...gen.Condition) ITabVideoWatchRecordDo
	Limit(limit int) ITabVideoWatchRecordDo
	Offset(offset int) ITabVideoWatchRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITabVideoWatchRecordDo
	Unscoped() ITabVideoWatchRecordDo
	Create(values ...*model.TabVideoWatchRecord) error
	CreateInBatches(values []*model.TabVideoWatchRecord, batchSize int) error
	Save(values ...*model.TabVideoWatchRecord) error
	First() (*model.TabVideoWatchRecord, error)
	Take() (*model.TabVideoWatchRecord, error)
	Last() (*model.TabVideoWatchRecord, error)
	Find() ([]*model.TabVideoWatchRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabVideoWatchRecord, err error)
	FindInBatches(result *[]*model.TabVideoWatchRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TabVideoWatchRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITabVideoWatchRecordDo
	Assign(attrs ...field.AssignExpr) ITabVideoWatchRecordDo
	Joins(fields ...field.RelationField) ITabVideoWatchRecordDo
	Preload(fields ...field.RelationField) ITabVideoWatchRecordDo
	FirstOrInit() (*model.TabVideoWatchRecord, error)
	FirstOrCreate() (*model.TabVideoWatchRecord, error)
	FindByPage(offset int, limit int) (result []*model.TabVideoWatchRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITabVideoWatchRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tabVideoWatchRecordDo) Debug() ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Debug())
}

func (t tabVideoWatchRecordDo) WithContext(ctx context.Context) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tabVideoWatchRecordDo) ReadDB() ITabVideoWatchRecordDo {
	return t.Clauses(dbresolver.Read)
}

func (t tabVideoWatchRecordDo) WriteDB() ITabVideoWatchRecordDo {
	return t.Clauses(dbresolver.Write)
}

func (t tabVideoWatchRecordDo) Session(config *gorm.Session) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Session(config))
}

func (t tabVideoWatchRecordDo) Clauses(conds ...clause.Expression) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tabVideoWatchRecordDo) Returning(value interface{}, columns ...string) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tabVideoWatchRecordDo) Not(conds ...gen.Condition) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tabVideoWatchRecordDo) Or(conds ...gen.Condition) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tabVideoWatchRecordDo) Select(conds ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tabVideoWatchRecordDo) Where(conds ...gen.Condition) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tabVideoWatchRecordDo) Order(conds ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tabVideoWatchRecordDo) Distinct(cols ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tabVideoWatchRecordDo) Omit(cols ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tabVideoWatchRecordDo) Join(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tabVideoWatchRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tabVideoWatchRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tabVideoWatchRecordDo) Group(cols ...field.Expr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tabVideoWatchRecordDo) Having(conds ...gen.Condition) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tabVideoWatchRecordDo) Limit(limit int) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tabVideoWatchRecordDo) Offset(offset int) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tabVideoWatchRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tabVideoWatchRecordDo) Unscoped() ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tabVideoWatchRecordDo) Create(values ...*model.TabVideoWatchRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tabVideoWatchRecordDo) CreateInBatches(values []*model.TabVideoWatchRecord, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tabVideoWatchRecordDo) Save(values ...*model.TabVideoWatchRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tabVideoWatchRecordDo) First() (*model.TabVideoWatchRecord, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideoWatchRecord), nil
	}
}

func (t tabVideoWatchRecordDo) Take() (*model.TabVideoWatchRecord, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideoWatchRecord), nil
	}
}

func (t tabVideoWatchRecordDo) Last() (*model.TabVideoWatchRecord, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideoWatchRecord), nil
	}
}

func (t tabVideoWatchRecordDo) Find() ([]*model.TabVideoWatchRecord, error) {
	result, err := t.DO.Find()
	return result.([]*model.TabVideoWatchRecord), err
}

func (t tabVideoWatchRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabVideoWatchRecord, err error) {
	buf := make([]*model.TabVideoWatchRecord, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tabVideoWatchRecordDo) FindInBatches(result *[]*model.TabVideoWatchRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tabVideoWatchRecordDo) Attrs(attrs ...field.AssignExpr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tabVideoWatchRecordDo) Assign(attrs ...field.AssignExpr) ITabVideoWatchRecordDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tabVideoWatchRecordDo) Joins(fields ...field.RelationField) ITabVideoWatchRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tabVideoWatchRecordDo) Preload(fields ...field.RelationField) ITabVideoWatchRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tabVideoWatchRecordDo) FirstOrInit() (*model.TabVideoWatchRecord, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideoWatchRecord), nil
	}
}

func (t tabVideoWatchRecordDo) FirstOrCreate() (*model.TabVideoWatchRecord, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabVideoWatchRecord), nil
	}
}

func (t tabVideoWatchRecordDo) FindByPage(offset int, limit int) (result []*model.TabVideoWatchRecord, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tabVideoWatchRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tabVideoWatchRecordDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tabVideoWatchRecordDo) Delete(models ...*model.TabVideoWatchRecord) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tabVideoWatchRecordDo) withDO(do gen.Dao) *tabVideoWatchRecordDo {
	t.DO = *do.(*gen.DO)
	return t
}
