// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newTabPriceTimeSpring(db *gorm.DB, opts ...gen.DOOption) tabPriceTimeSpring {
	_tabPriceTimeSpring := tabPriceTimeSpring{}

	_tabPriceTimeSpring.tabPriceTimeSpringDo.UseDB(db, opts...)
	_tabPriceTimeSpring.tabPriceTimeSpringDo.UseModel(&model.TabPriceTimeSpring{})

	tableName := _tabPriceTimeSpring.tabPriceTimeSpringDo.TableName()
	_tabPriceTimeSpring.ALL = field.NewAsterisk(tableName)
	_tabPriceTimeSpring.ID = field.NewInt32(tableName, "id")
	_tabPriceTimeSpring.StartTime = field.NewTime(tableName, "start_time")
	_tabPriceTimeSpring.OverTime = field.NewTime(tableName, "over_time")
	_tabPriceTimeSpring.PriceID = field.NewInt32(tableName, "price_id")

	_tabPriceTimeSpring.fillFieldMap()

	return _tabPriceTimeSpring
}

// tabPriceTimeSpring 春秋季--时段电价
type tabPriceTimeSpring struct {
	tabPriceTimeSpringDo tabPriceTimeSpringDo

	ALL       field.Asterisk
	ID        field.Int32 // 价格时段id
	StartTime field.Time  // 开始时间
	OverTime  field.Time  // 结束时间
	PriceID   field.Int32 // 电价id

	fieldMap map[string]field.Expr
}

func (t tabPriceTimeSpring) Table(newTableName string) *tabPriceTimeSpring {
	t.tabPriceTimeSpringDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tabPriceTimeSpring) As(alias string) *tabPriceTimeSpring {
	t.tabPriceTimeSpringDo.DO = *(t.tabPriceTimeSpringDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tabPriceTimeSpring) updateTableName(table string) *tabPriceTimeSpring {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.StartTime = field.NewTime(table, "start_time")
	t.OverTime = field.NewTime(table, "over_time")
	t.PriceID = field.NewInt32(table, "price_id")

	t.fillFieldMap()

	return t
}

func (t *tabPriceTimeSpring) WithContext(ctx context.Context) ITabPriceTimeSpringDo {
	return t.tabPriceTimeSpringDo.WithContext(ctx)
}

func (t tabPriceTimeSpring) TableName() string { return t.tabPriceTimeSpringDo.TableName() }

func (t tabPriceTimeSpring) Alias() string { return t.tabPriceTimeSpringDo.Alias() }

func (t tabPriceTimeSpring) Columns(cols ...field.Expr) gen.Columns {
	return t.tabPriceTimeSpringDo.Columns(cols...)
}

func (t *tabPriceTimeSpring) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tabPriceTimeSpring) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["start_time"] = t.StartTime
	t.fieldMap["over_time"] = t.OverTime
	t.fieldMap["price_id"] = t.PriceID
}

func (t tabPriceTimeSpring) clone(db *gorm.DB) tabPriceTimeSpring {
	t.tabPriceTimeSpringDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tabPriceTimeSpring) replaceDB(db *gorm.DB) tabPriceTimeSpring {
	t.tabPriceTimeSpringDo.ReplaceDB(db)
	return t
}

type tabPriceTimeSpringDo struct{ gen.DO }

type ITabPriceTimeSpringDo interface {
	gen.SubQuery
	Debug() ITabPriceTimeSpringDo
	WithContext(ctx context.Context) ITabPriceTimeSpringDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITabPriceTimeSpringDo
	WriteDB() ITabPriceTimeSpringDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITabPriceTimeSpringDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITabPriceTimeSpringDo
	Not(conds ...gen.Condition) ITabPriceTimeSpringDo
	Or(conds ...gen.Condition) ITabPriceTimeSpringDo
	Select(conds ...field.Expr) ITabPriceTimeSpringDo
	Where(conds ...gen.Condition) ITabPriceTimeSpringDo
	Order(conds ...field.Expr) ITabPriceTimeSpringDo
	Distinct(cols ...field.Expr) ITabPriceTimeSpringDo
	Omit(cols ...field.Expr) ITabPriceTimeSpringDo
	Join(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo
	Group(cols ...field.Expr) ITabPriceTimeSpringDo
	Having(conds ...gen.Condition) ITabPriceTimeSpringDo
	Limit(limit int) ITabPriceTimeSpringDo
	Offset(offset int) ITabPriceTimeSpringDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITabPriceTimeSpringDo
	Unscoped() ITabPriceTimeSpringDo
	Create(values ...*model.TabPriceTimeSpring) error
	CreateInBatches(values []*model.TabPriceTimeSpring, batchSize int) error
	Save(values ...*model.TabPriceTimeSpring) error
	First() (*model.TabPriceTimeSpring, error)
	Take() (*model.TabPriceTimeSpring, error)
	Last() (*model.TabPriceTimeSpring, error)
	Find() ([]*model.TabPriceTimeSpring, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabPriceTimeSpring, err error)
	FindInBatches(result *[]*model.TabPriceTimeSpring, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TabPriceTimeSpring) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITabPriceTimeSpringDo
	Assign(attrs ...field.AssignExpr) ITabPriceTimeSpringDo
	Joins(fields ...field.RelationField) ITabPriceTimeSpringDo
	Preload(fields ...field.RelationField) ITabPriceTimeSpringDo
	FirstOrInit() (*model.TabPriceTimeSpring, error)
	FirstOrCreate() (*model.TabPriceTimeSpring, error)
	FindByPage(offset int, limit int) (result []*model.TabPriceTimeSpring, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITabPriceTimeSpringDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tabPriceTimeSpringDo) Debug() ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Debug())
}

func (t tabPriceTimeSpringDo) WithContext(ctx context.Context) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tabPriceTimeSpringDo) ReadDB() ITabPriceTimeSpringDo {
	return t.Clauses(dbresolver.Read)
}

func (t tabPriceTimeSpringDo) WriteDB() ITabPriceTimeSpringDo {
	return t.Clauses(dbresolver.Write)
}

func (t tabPriceTimeSpringDo) Session(config *gorm.Session) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Session(config))
}

func (t tabPriceTimeSpringDo) Clauses(conds ...clause.Expression) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tabPriceTimeSpringDo) Returning(value interface{}, columns ...string) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tabPriceTimeSpringDo) Not(conds ...gen.Condition) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tabPriceTimeSpringDo) Or(conds ...gen.Condition) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tabPriceTimeSpringDo) Select(conds ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tabPriceTimeSpringDo) Where(conds ...gen.Condition) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tabPriceTimeSpringDo) Order(conds ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tabPriceTimeSpringDo) Distinct(cols ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tabPriceTimeSpringDo) Omit(cols ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tabPriceTimeSpringDo) Join(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tabPriceTimeSpringDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tabPriceTimeSpringDo) RightJoin(table schema.Tabler, on ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tabPriceTimeSpringDo) Group(cols ...field.Expr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tabPriceTimeSpringDo) Having(conds ...gen.Condition) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tabPriceTimeSpringDo) Limit(limit int) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tabPriceTimeSpringDo) Offset(offset int) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tabPriceTimeSpringDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tabPriceTimeSpringDo) Unscoped() ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tabPriceTimeSpringDo) Create(values ...*model.TabPriceTimeSpring) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tabPriceTimeSpringDo) CreateInBatches(values []*model.TabPriceTimeSpring, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tabPriceTimeSpringDo) Save(values ...*model.TabPriceTimeSpring) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tabPriceTimeSpringDo) First() (*model.TabPriceTimeSpring, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabPriceTimeSpring), nil
	}
}

func (t tabPriceTimeSpringDo) Take() (*model.TabPriceTimeSpring, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabPriceTimeSpring), nil
	}
}

func (t tabPriceTimeSpringDo) Last() (*model.TabPriceTimeSpring, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabPriceTimeSpring), nil
	}
}

func (t tabPriceTimeSpringDo) Find() ([]*model.TabPriceTimeSpring, error) {
	result, err := t.DO.Find()
	return result.([]*model.TabPriceTimeSpring), err
}

func (t tabPriceTimeSpringDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TabPriceTimeSpring, err error) {
	buf := make([]*model.TabPriceTimeSpring, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tabPriceTimeSpringDo) FindInBatches(result *[]*model.TabPriceTimeSpring, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tabPriceTimeSpringDo) Attrs(attrs ...field.AssignExpr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tabPriceTimeSpringDo) Assign(attrs ...field.AssignExpr) ITabPriceTimeSpringDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tabPriceTimeSpringDo) Joins(fields ...field.RelationField) ITabPriceTimeSpringDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tabPriceTimeSpringDo) Preload(fields ...field.RelationField) ITabPriceTimeSpringDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tabPriceTimeSpringDo) FirstOrInit() (*model.TabPriceTimeSpring, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabPriceTimeSpring), nil
	}
}

func (t tabPriceTimeSpringDo) FirstOrCreate() (*model.TabPriceTimeSpring, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TabPriceTimeSpring), nil
	}
}

func (t tabPriceTimeSpringDo) FindByPage(offset int, limit int) (result []*model.TabPriceTimeSpring, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tabPriceTimeSpringDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tabPriceTimeSpringDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tabPriceTimeSpringDo) Delete(models ...*model.TabPriceTimeSpring) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tabPriceTimeSpringDo) withDO(do gen.Dao) *tabPriceTimeSpringDo {
	t.DO = *do.(*gen.DO)
	return t
}
