// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newUserShopTbl(db *gorm.DB, opts ...gen.DOOption) userShopTbl {
	_userShopTbl := userShopTbl{}

	_userShopTbl.userShopTblDo.UseDB(db, opts...)
	_userShopTbl.userShopTblDo.UseModel(&model.UserShopTbl{})

	tableName := _userShopTbl.userShopTblDo.TableName()
	_userShopTbl.ALL = field.NewAsterisk(tableName)
	_userShopTbl.ID = field.NewInt32(tableName, "id")
	_userShopTbl.OpenID = field.NewString(tableName, "open_id")
	_userShopTbl.ShopID = field.NewString(tableName, "shop_id")

	_userShopTbl.fillFieldMap()

	return _userShopTbl
}

type userShopTbl struct {
	userShopTblDo userShopTblDo

	ALL    field.Asterisk
	ID     field.Int32  // 无逻辑主键
	OpenID field.String // wechart user key
	ShopID field.String // shop key

	fieldMap map[string]field.Expr
}

func (u userShopTbl) Table(newTableName string) *userShopTbl {
	u.userShopTblDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userShopTbl) As(alias string) *userShopTbl {
	u.userShopTblDo.DO = *(u.userShopTblDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userShopTbl) updateTableName(table string) *userShopTbl {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.OpenID = field.NewString(table, "open_id")
	u.ShopID = field.NewString(table, "shop_id")

	u.fillFieldMap()

	return u
}

func (u *userShopTbl) WithContext(ctx context.Context) IUserShopTblDo {
	return u.userShopTblDo.WithContext(ctx)
}

func (u userShopTbl) TableName() string { return u.userShopTblDo.TableName() }

func (u userShopTbl) Alias() string { return u.userShopTblDo.Alias() }

func (u userShopTbl) Columns(cols ...field.Expr) gen.Columns { return u.userShopTblDo.Columns(cols...) }

func (u *userShopTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userShopTbl) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["id"] = u.ID
	u.fieldMap["open_id"] = u.OpenID
	u.fieldMap["shop_id"] = u.ShopID
}

func (u userShopTbl) clone(db *gorm.DB) userShopTbl {
	u.userShopTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userShopTbl) replaceDB(db *gorm.DB) userShopTbl {
	u.userShopTblDo.ReplaceDB(db)
	return u
}

type userShopTblDo struct{ gen.DO }

type IUserShopTblDo interface {
	gen.SubQuery
	Debug() IUserShopTblDo
	WithContext(ctx context.Context) IUserShopTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserShopTblDo
	WriteDB() IUserShopTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserShopTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserShopTblDo
	Not(conds ...gen.Condition) IUserShopTblDo
	Or(conds ...gen.Condition) IUserShopTblDo
	Select(conds ...field.Expr) IUserShopTblDo
	Where(conds ...gen.Condition) IUserShopTblDo
	Order(conds ...field.Expr) IUserShopTblDo
	Distinct(cols ...field.Expr) IUserShopTblDo
	Omit(cols ...field.Expr) IUserShopTblDo
	Join(table schema.Tabler, on ...field.Expr) IUserShopTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserShopTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserShopTblDo
	Group(cols ...field.Expr) IUserShopTblDo
	Having(conds ...gen.Condition) IUserShopTblDo
	Limit(limit int) IUserShopTblDo
	Offset(offset int) IUserShopTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserShopTblDo
	Unscoped() IUserShopTblDo
	Create(values ...*model.UserShopTbl) error
	CreateInBatches(values []*model.UserShopTbl, batchSize int) error
	Save(values ...*model.UserShopTbl) error
	First() (*model.UserShopTbl, error)
	Take() (*model.UserShopTbl, error)
	Last() (*model.UserShopTbl, error)
	Find() ([]*model.UserShopTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserShopTbl, err error)
	FindInBatches(result *[]*model.UserShopTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserShopTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserShopTblDo
	Assign(attrs ...field.AssignExpr) IUserShopTblDo
	Joins(fields ...field.RelationField) IUserShopTblDo
	Preload(fields ...field.RelationField) IUserShopTblDo
	FirstOrInit() (*model.UserShopTbl, error)
	FirstOrCreate() (*model.UserShopTbl, error)
	FindByPage(offset int, limit int) (result []*model.UserShopTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserShopTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userShopTblDo) Debug() IUserShopTblDo {
	return u.withDO(u.DO.Debug())
}

func (u userShopTblDo) WithContext(ctx context.Context) IUserShopTblDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userShopTblDo) ReadDB() IUserShopTblDo {
	return u.Clauses(dbresolver.Read)
}

func (u userShopTblDo) WriteDB() IUserShopTblDo {
	return u.Clauses(dbresolver.Write)
}

func (u userShopTblDo) Session(config *gorm.Session) IUserShopTblDo {
	return u.withDO(u.DO.Session(config))
}

func (u userShopTblDo) Clauses(conds ...clause.Expression) IUserShopTblDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userShopTblDo) Returning(value interface{}, columns ...string) IUserShopTblDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userShopTblDo) Not(conds ...gen.Condition) IUserShopTblDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userShopTblDo) Or(conds ...gen.Condition) IUserShopTblDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userShopTblDo) Select(conds ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userShopTblDo) Where(conds ...gen.Condition) IUserShopTblDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userShopTblDo) Order(conds ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userShopTblDo) Distinct(cols ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userShopTblDo) Omit(cols ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userShopTblDo) Join(table schema.Tabler, on ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userShopTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userShopTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userShopTblDo) Group(cols ...field.Expr) IUserShopTblDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userShopTblDo) Having(conds ...gen.Condition) IUserShopTblDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userShopTblDo) Limit(limit int) IUserShopTblDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userShopTblDo) Offset(offset int) IUserShopTblDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userShopTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserShopTblDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userShopTblDo) Unscoped() IUserShopTblDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userShopTblDo) Create(values ...*model.UserShopTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userShopTblDo) CreateInBatches(values []*model.UserShopTbl, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userShopTblDo) Save(values ...*model.UserShopTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userShopTblDo) First() (*model.UserShopTbl, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShopTbl), nil
	}
}

func (u userShopTblDo) Take() (*model.UserShopTbl, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShopTbl), nil
	}
}

func (u userShopTblDo) Last() (*model.UserShopTbl, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShopTbl), nil
	}
}

func (u userShopTblDo) Find() ([]*model.UserShopTbl, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserShopTbl), err
}

func (u userShopTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserShopTbl, err error) {
	buf := make([]*model.UserShopTbl, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userShopTblDo) FindInBatches(result *[]*model.UserShopTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userShopTblDo) Attrs(attrs ...field.AssignExpr) IUserShopTblDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userShopTblDo) Assign(attrs ...field.AssignExpr) IUserShopTblDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userShopTblDo) Joins(fields ...field.RelationField) IUserShopTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userShopTblDo) Preload(fields ...field.RelationField) IUserShopTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userShopTblDo) FirstOrInit() (*model.UserShopTbl, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShopTbl), nil
	}
}

func (u userShopTblDo) FirstOrCreate() (*model.UserShopTbl, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserShopTbl), nil
	}
}

func (u userShopTblDo) FindByPage(offset int, limit int) (result []*model.UserShopTbl, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userShopTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userShopTblDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userShopTblDo) Delete(models ...*model.UserShopTbl) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userShopTblDo) withDO(do gen.Dao) *userShopTblDo {
	u.DO = *do.(*gen.DO)
	return u
}
