// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newUsermessageTbl(db *gorm.DB, opts ...gen.DOOption) usermessageTbl {
	_usermessageTbl := usermessageTbl{}

	_usermessageTbl.usermessageTblDo.UseDB(db, opts...)
	_usermessageTbl.usermessageTblDo.UseModel(&model.UsermessageTbl{})

	tableName := _usermessageTbl.usermessageTblDo.TableName()
	_usermessageTbl.ALL = field.NewAsterisk(tableName)
	_usermessageTbl.ID = field.NewInt32(tableName, "id")
	_usermessageTbl.Openid = field.NewString(tableName, "openid")
	_usermessageTbl.Message = field.NewString(tableName, "message")
	_usermessageTbl.MsgTime = field.NewString(tableName, "msgTime")
	_usermessageTbl.Status = field.NewString(tableName, "status")
	_usermessageTbl.IsDelete = field.NewInt32(tableName, "isDelete")
	_usermessageTbl.CreateTime = field.NewTime(tableName, "createTime")
	_usermessageTbl.UpdateTime = field.NewTime(tableName, "updateTime")

	_usermessageTbl.fillFieldMap()

	return _usermessageTbl
}

// usermessageTbl 已废弃
type usermessageTbl struct {
	usermessageTblDo usermessageTblDo

	ALL        field.Asterisk
	ID         field.Int32
	Openid     field.String
	Message    field.String
	MsgTime    field.String
	Status     field.String
	IsDelete   field.Int32
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (u usermessageTbl) Table(newTableName string) *usermessageTbl {
	u.usermessageTblDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u usermessageTbl) As(alias string) *usermessageTbl {
	u.usermessageTblDo.DO = *(u.usermessageTblDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *usermessageTbl) updateTableName(table string) *usermessageTbl {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Openid = field.NewString(table, "openid")
	u.Message = field.NewString(table, "message")
	u.MsgTime = field.NewString(table, "msgTime")
	u.Status = field.NewString(table, "status")
	u.IsDelete = field.NewInt32(table, "isDelete")
	u.CreateTime = field.NewTime(table, "createTime")
	u.UpdateTime = field.NewTime(table, "updateTime")

	u.fillFieldMap()

	return u
}

func (u *usermessageTbl) WithContext(ctx context.Context) IUsermessageTblDo {
	return u.usermessageTblDo.WithContext(ctx)
}

func (u usermessageTbl) TableName() string { return u.usermessageTblDo.TableName() }

func (u usermessageTbl) Alias() string { return u.usermessageTblDo.Alias() }

func (u usermessageTbl) Columns(cols ...field.Expr) gen.Columns {
	return u.usermessageTblDo.Columns(cols...)
}

func (u *usermessageTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *usermessageTbl) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["openid"] = u.Openid
	u.fieldMap["message"] = u.Message
	u.fieldMap["msgTime"] = u.MsgTime
	u.fieldMap["status"] = u.Status
	u.fieldMap["isDelete"] = u.IsDelete
	u.fieldMap["createTime"] = u.CreateTime
	u.fieldMap["updateTime"] = u.UpdateTime
}

func (u usermessageTbl) clone(db *gorm.DB) usermessageTbl {
	u.usermessageTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u usermessageTbl) replaceDB(db *gorm.DB) usermessageTbl {
	u.usermessageTblDo.ReplaceDB(db)
	return u
}

type usermessageTblDo struct{ gen.DO }

type IUsermessageTblDo interface {
	gen.SubQuery
	Debug() IUsermessageTblDo
	WithContext(ctx context.Context) IUsermessageTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUsermessageTblDo
	WriteDB() IUsermessageTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUsermessageTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUsermessageTblDo
	Not(conds ...gen.Condition) IUsermessageTblDo
	Or(conds ...gen.Condition) IUsermessageTblDo
	Select(conds ...field.Expr) IUsermessageTblDo
	Where(conds ...gen.Condition) IUsermessageTblDo
	Order(conds ...field.Expr) IUsermessageTblDo
	Distinct(cols ...field.Expr) IUsermessageTblDo
	Omit(cols ...field.Expr) IUsermessageTblDo
	Join(table schema.Tabler, on ...field.Expr) IUsermessageTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUsermessageTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUsermessageTblDo
	Group(cols ...field.Expr) IUsermessageTblDo
	Having(conds ...gen.Condition) IUsermessageTblDo
	Limit(limit int) IUsermessageTblDo
	Offset(offset int) IUsermessageTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUsermessageTblDo
	Unscoped() IUsermessageTblDo
	Create(values ...*model.UsermessageTbl) error
	CreateInBatches(values []*model.UsermessageTbl, batchSize int) error
	Save(values ...*model.UsermessageTbl) error
	First() (*model.UsermessageTbl, error)
	Take() (*model.UsermessageTbl, error)
	Last() (*model.UsermessageTbl, error)
	Find() ([]*model.UsermessageTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UsermessageTbl, err error)
	FindInBatches(result *[]*model.UsermessageTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UsermessageTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUsermessageTblDo
	Assign(attrs ...field.AssignExpr) IUsermessageTblDo
	Joins(fields ...field.RelationField) IUsermessageTblDo
	Preload(fields ...field.RelationField) IUsermessageTblDo
	FirstOrInit() (*model.UsermessageTbl, error)
	FirstOrCreate() (*model.UsermessageTbl, error)
	FindByPage(offset int, limit int) (result []*model.UsermessageTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUsermessageTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u usermessageTblDo) Debug() IUsermessageTblDo {
	return u.withDO(u.DO.Debug())
}

func (u usermessageTblDo) WithContext(ctx context.Context) IUsermessageTblDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usermessageTblDo) ReadDB() IUsermessageTblDo {
	return u.Clauses(dbresolver.Read)
}

func (u usermessageTblDo) WriteDB() IUsermessageTblDo {
	return u.Clauses(dbresolver.Write)
}

func (u usermessageTblDo) Session(config *gorm.Session) IUsermessageTblDo {
	return u.withDO(u.DO.Session(config))
}

func (u usermessageTblDo) Clauses(conds ...clause.Expression) IUsermessageTblDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usermessageTblDo) Returning(value interface{}, columns ...string) IUsermessageTblDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usermessageTblDo) Not(conds ...gen.Condition) IUsermessageTblDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usermessageTblDo) Or(conds ...gen.Condition) IUsermessageTblDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usermessageTblDo) Select(conds ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usermessageTblDo) Where(conds ...gen.Condition) IUsermessageTblDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usermessageTblDo) Order(conds ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usermessageTblDo) Distinct(cols ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usermessageTblDo) Omit(cols ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usermessageTblDo) Join(table schema.Tabler, on ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usermessageTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usermessageTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usermessageTblDo) Group(cols ...field.Expr) IUsermessageTblDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usermessageTblDo) Having(conds ...gen.Condition) IUsermessageTblDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usermessageTblDo) Limit(limit int) IUsermessageTblDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usermessageTblDo) Offset(offset int) IUsermessageTblDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usermessageTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUsermessageTblDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usermessageTblDo) Unscoped() IUsermessageTblDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usermessageTblDo) Create(values ...*model.UsermessageTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usermessageTblDo) CreateInBatches(values []*model.UsermessageTbl, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usermessageTblDo) Save(values ...*model.UsermessageTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usermessageTblDo) First() (*model.UsermessageTbl, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsermessageTbl), nil
	}
}

func (u usermessageTblDo) Take() (*model.UsermessageTbl, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsermessageTbl), nil
	}
}

func (u usermessageTblDo) Last() (*model.UsermessageTbl, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsermessageTbl), nil
	}
}

func (u usermessageTblDo) Find() ([]*model.UsermessageTbl, error) {
	result, err := u.DO.Find()
	return result.([]*model.UsermessageTbl), err
}

func (u usermessageTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UsermessageTbl, err error) {
	buf := make([]*model.UsermessageTbl, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usermessageTblDo) FindInBatches(result *[]*model.UsermessageTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usermessageTblDo) Attrs(attrs ...field.AssignExpr) IUsermessageTblDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usermessageTblDo) Assign(attrs ...field.AssignExpr) IUsermessageTblDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usermessageTblDo) Joins(fields ...field.RelationField) IUsermessageTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usermessageTblDo) Preload(fields ...field.RelationField) IUsermessageTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usermessageTblDo) FirstOrInit() (*model.UsermessageTbl, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsermessageTbl), nil
	}
}

func (u usermessageTblDo) FirstOrCreate() (*model.UsermessageTbl, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsermessageTbl), nil
	}
}

func (u usermessageTblDo) FindByPage(offset int, limit int) (result []*model.UsermessageTbl, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usermessageTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usermessageTblDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usermessageTblDo) Delete(models ...*model.UsermessageTbl) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usermessageTblDo) withDO(do gen.Dao) *usermessageTblDo {
	u.DO = *do.(*gen.DO)
	return u
}
