// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newUserBankCardTbl(db *gorm.DB, opts ...gen.DOOption) userBankCardTbl {
	_userBankCardTbl := userBankCardTbl{}

	_userBankCardTbl.userBankCardTblDo.UseDB(db, opts...)
	_userBankCardTbl.userBankCardTblDo.UseModel(&model.UserBankCardTbl{})

	tableName := _userBankCardTbl.userBankCardTblDo.TableName()
	_userBankCardTbl.ALL = field.NewAsterisk(tableName)
	_userBankCardTbl.ID = field.NewInt32(tableName, "id")
	_userBankCardTbl.Openid = field.NewString(tableName, "openid")
	_userBankCardTbl.CardNumber = field.NewString(tableName, "card_number")
	_userBankCardTbl.HolderName = field.NewString(tableName, "holder_name")
	_userBankCardTbl.Bank = field.NewString(tableName, "bank")
	_userBankCardTbl.CreateTime = field.NewTime(tableName, "create_time")
	_userBankCardTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_userBankCardTbl.fillFieldMap()

	return _userBankCardTbl
}

// userBankCardTbl 用户银行卡信息表
type userBankCardTbl struct {
	userBankCardTblDo userBankCardTblDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	Openid     field.String // 微信用户唯一openid
	CardNumber field.String // 银行卡账号
	HolderName field.String // 开户人姓名
	Bank       field.String // 开户行
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (u userBankCardTbl) Table(newTableName string) *userBankCardTbl {
	u.userBankCardTblDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userBankCardTbl) As(alias string) *userBankCardTbl {
	u.userBankCardTblDo.DO = *(u.userBankCardTblDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userBankCardTbl) updateTableName(table string) *userBankCardTbl {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Openid = field.NewString(table, "openid")
	u.CardNumber = field.NewString(table, "card_number")
	u.HolderName = field.NewString(table, "holder_name")
	u.Bank = field.NewString(table, "bank")
	u.CreateTime = field.NewTime(table, "create_time")
	u.UpdateTime = field.NewTime(table, "update_time")

	u.fillFieldMap()

	return u
}

func (u *userBankCardTbl) WithContext(ctx context.Context) IUserBankCardTblDo {
	return u.userBankCardTblDo.WithContext(ctx)
}

func (u userBankCardTbl) TableName() string { return u.userBankCardTblDo.TableName() }

func (u userBankCardTbl) Alias() string { return u.userBankCardTblDo.Alias() }

func (u userBankCardTbl) Columns(cols ...field.Expr) gen.Columns {
	return u.userBankCardTblDo.Columns(cols...)
}

func (u *userBankCardTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userBankCardTbl) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["openid"] = u.Openid
	u.fieldMap["card_number"] = u.CardNumber
	u.fieldMap["holder_name"] = u.HolderName
	u.fieldMap["bank"] = u.Bank
	u.fieldMap["create_time"] = u.CreateTime
	u.fieldMap["update_time"] = u.UpdateTime
}

func (u userBankCardTbl) clone(db *gorm.DB) userBankCardTbl {
	u.userBankCardTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userBankCardTbl) replaceDB(db *gorm.DB) userBankCardTbl {
	u.userBankCardTblDo.ReplaceDB(db)
	return u
}

type userBankCardTblDo struct{ gen.DO }

type IUserBankCardTblDo interface {
	gen.SubQuery
	Debug() IUserBankCardTblDo
	WithContext(ctx context.Context) IUserBankCardTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserBankCardTblDo
	WriteDB() IUserBankCardTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserBankCardTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserBankCardTblDo
	Not(conds ...gen.Condition) IUserBankCardTblDo
	Or(conds ...gen.Condition) IUserBankCardTblDo
	Select(conds ...field.Expr) IUserBankCardTblDo
	Where(conds ...gen.Condition) IUserBankCardTblDo
	Order(conds ...field.Expr) IUserBankCardTblDo
	Distinct(cols ...field.Expr) IUserBankCardTblDo
	Omit(cols ...field.Expr) IUserBankCardTblDo
	Join(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo
	Group(cols ...field.Expr) IUserBankCardTblDo
	Having(conds ...gen.Condition) IUserBankCardTblDo
	Limit(limit int) IUserBankCardTblDo
	Offset(offset int) IUserBankCardTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBankCardTblDo
	Unscoped() IUserBankCardTblDo
	Create(values ...*model.UserBankCardTbl) error
	CreateInBatches(values []*model.UserBankCardTbl, batchSize int) error
	Save(values ...*model.UserBankCardTbl) error
	First() (*model.UserBankCardTbl, error)
	Take() (*model.UserBankCardTbl, error)
	Last() (*model.UserBankCardTbl, error)
	Find() ([]*model.UserBankCardTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBankCardTbl, err error)
	FindInBatches(result *[]*model.UserBankCardTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserBankCardTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserBankCardTblDo
	Assign(attrs ...field.AssignExpr) IUserBankCardTblDo
	Joins(fields ...field.RelationField) IUserBankCardTblDo
	Preload(fields ...field.RelationField) IUserBankCardTblDo
	FirstOrInit() (*model.UserBankCardTbl, error)
	FirstOrCreate() (*model.UserBankCardTbl, error)
	FindByPage(offset int, limit int) (result []*model.UserBankCardTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserBankCardTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userBankCardTblDo) Debug() IUserBankCardTblDo {
	return u.withDO(u.DO.Debug())
}

func (u userBankCardTblDo) WithContext(ctx context.Context) IUserBankCardTblDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userBankCardTblDo) ReadDB() IUserBankCardTblDo {
	return u.Clauses(dbresolver.Read)
}

func (u userBankCardTblDo) WriteDB() IUserBankCardTblDo {
	return u.Clauses(dbresolver.Write)
}

func (u userBankCardTblDo) Session(config *gorm.Session) IUserBankCardTblDo {
	return u.withDO(u.DO.Session(config))
}

func (u userBankCardTblDo) Clauses(conds ...clause.Expression) IUserBankCardTblDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userBankCardTblDo) Returning(value interface{}, columns ...string) IUserBankCardTblDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userBankCardTblDo) Not(conds ...gen.Condition) IUserBankCardTblDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userBankCardTblDo) Or(conds ...gen.Condition) IUserBankCardTblDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userBankCardTblDo) Select(conds ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userBankCardTblDo) Where(conds ...gen.Condition) IUserBankCardTblDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userBankCardTblDo) Order(conds ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userBankCardTblDo) Distinct(cols ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userBankCardTblDo) Omit(cols ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userBankCardTblDo) Join(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userBankCardTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userBankCardTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userBankCardTblDo) Group(cols ...field.Expr) IUserBankCardTblDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userBankCardTblDo) Having(conds ...gen.Condition) IUserBankCardTblDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userBankCardTblDo) Limit(limit int) IUserBankCardTblDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userBankCardTblDo) Offset(offset int) IUserBankCardTblDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userBankCardTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBankCardTblDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userBankCardTblDo) Unscoped() IUserBankCardTblDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userBankCardTblDo) Create(values ...*model.UserBankCardTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userBankCardTblDo) CreateInBatches(values []*model.UserBankCardTbl, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userBankCardTblDo) Save(values ...*model.UserBankCardTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userBankCardTblDo) First() (*model.UserBankCardTbl, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBankCardTbl), nil
	}
}

func (u userBankCardTblDo) Take() (*model.UserBankCardTbl, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBankCardTbl), nil
	}
}

func (u userBankCardTblDo) Last() (*model.UserBankCardTbl, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBankCardTbl), nil
	}
}

func (u userBankCardTblDo) Find() ([]*model.UserBankCardTbl, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserBankCardTbl), err
}

func (u userBankCardTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBankCardTbl, err error) {
	buf := make([]*model.UserBankCardTbl, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userBankCardTblDo) FindInBatches(result *[]*model.UserBankCardTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userBankCardTblDo) Attrs(attrs ...field.AssignExpr) IUserBankCardTblDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userBankCardTblDo) Assign(attrs ...field.AssignExpr) IUserBankCardTblDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userBankCardTblDo) Joins(fields ...field.RelationField) IUserBankCardTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userBankCardTblDo) Preload(fields ...field.RelationField) IUserBankCardTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userBankCardTblDo) FirstOrInit() (*model.UserBankCardTbl, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBankCardTbl), nil
	}
}

func (u userBankCardTblDo) FirstOrCreate() (*model.UserBankCardTbl, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBankCardTbl), nil
	}
}

func (u userBankCardTblDo) FindByPage(offset int, limit int) (result []*model.UserBankCardTbl, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userBankCardTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userBankCardTblDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userBankCardTblDo) Delete(models ...*model.UserBankCardTbl) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userBankCardTblDo) withDO(do gen.Dao) *userBankCardTblDo {
	u.DO = *do.(*gen.DO)
	return u
}
