// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package objects

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"caicai-go/model"
)

func newUserTbl(db *gorm.DB, opts ...gen.DOOption) userTbl {
	_userTbl := userTbl{}

	_userTbl.userTblDo.UseDB(db, opts...)
	_userTbl.userTblDo.UseModel(&model.UserTbl{})

	tableName := _userTbl.userTblDo.TableName()
	_userTbl.ALL = field.NewAsterisk(tableName)
	_userTbl.Openid = field.NewString(tableName, "openid")
	_userTbl.Omid = field.NewString(tableName, "omid")
	_userTbl.YiparlOpenid = field.NewString(tableName, "yiparl_openid")
	_userTbl.NickName = field.NewString(tableName, "nick_name")
	_userTbl.Province = field.NewString(tableName, "province")
	_userTbl.City = field.NewString(tableName, "city")
	_userTbl.Phone = field.NewString(tableName, "phone")
	_userTbl.Integral = field.NewString(tableName, "integral")
	_userTbl.FreeTime = field.NewString(tableName, "free_time")
	_userTbl.PlateNum = field.NewString(tableName, "plate_num")
	_userTbl.IDNumber = field.NewString(tableName, "id_number")
	_userTbl.Name = field.NewString(tableName, "name")
	_userTbl.Avatar = field.NewBytes(tableName, "avatar")
	_userTbl.IDCardEmblem = field.NewInt32(tableName, "id_card_emblem")
	_userTbl.IDCardAvatar = field.NewInt32(tableName, "id_card_avatar")
	_userTbl.Balans = field.NewFloat64(tableName, "balans")
	_userTbl.FreezeBalans = field.NewFloat64(tableName, "freeze_balans")
	_userTbl.IDEntity = field.NewString(tableName, "id_entity")
	_userTbl.OmEnable = field.NewString(tableName, "om_enable")
	_userTbl.IsSteer = field.NewString(tableName, "is_steer")
	_userTbl.IsProcedure = field.NewString(tableName, "is_procedure")
	_userTbl.IsLogin = field.NewString(tableName, "is_login")
	_userTbl.CreateTime = field.NewTime(tableName, "create_time")
	_userTbl.UpdateTime = field.NewTime(tableName, "update_time")

	_userTbl.fillFieldMap()

	return _userTbl
}

// userTbl 用户表
type userTbl struct {
	userTblDo userTblDo

	ALL          field.Asterisk
	Openid       field.String  // 用户唯一标识
	Omid         field.String  // 运维微信id
	YiparlOpenid field.String  // 逸泊停车微信id
	NickName     field.String  // 用户昵称
	Province     field.String  // 微信所在省
	City         field.String  // 微信所在市
	Phone        field.String  // 手机号
	Integral     field.String  // 用户积分
	FreeTime     field.String  // 免费停车时长
	PlateNum     field.String  // 用户首选车牌
	IDNumber     field.String  // 用户身份证号
	Name         field.String  // 用户姓名
	Avatar       field.Bytes   // 头像
	IDCardEmblem field.Int32   // 身份证国徽面image_id
	IDCardAvatar field.Int32   // 身份证头像面image_id
	Balans       field.Float64 // 用户余额
	FreezeBalans field.Float64 // 用户冻结金额
	IDEntity     field.String  // 身份标识 , 1驾驶人员,2业主,3酒店老板,4酒店管理人员
	OmEnable     field.String  // 运维身份审核,0未审核,1,审核通过,-1审核未通过
	IsSteer      field.String  // 首页用户引导状态(0,未读,1,已读)
	IsProcedure  field.String  // 二轮车充电操作流程状态(0,未读,1,已读)
	IsLogin      field.String  // 是否登录(0,未登录,1,已登录)
	CreateTime   field.Time    // 创建账户时间
	UpdateTime   field.Time    // 修改时间

	fieldMap map[string]field.Expr
}

func (u userTbl) Table(newTableName string) *userTbl {
	u.userTblDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userTbl) As(alias string) *userTbl {
	u.userTblDo.DO = *(u.userTblDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userTbl) updateTableName(table string) *userTbl {
	u.ALL = field.NewAsterisk(table)
	u.Openid = field.NewString(table, "openid")
	u.Omid = field.NewString(table, "omid")
	u.YiparlOpenid = field.NewString(table, "yiparl_openid")
	u.NickName = field.NewString(table, "nick_name")
	u.Province = field.NewString(table, "province")
	u.City = field.NewString(table, "city")
	u.Phone = field.NewString(table, "phone")
	u.Integral = field.NewString(table, "integral")
	u.FreeTime = field.NewString(table, "free_time")
	u.PlateNum = field.NewString(table, "plate_num")
	u.IDNumber = field.NewString(table, "id_number")
	u.Name = field.NewString(table, "name")
	u.Avatar = field.NewBytes(table, "avatar")
	u.IDCardEmblem = field.NewInt32(table, "id_card_emblem")
	u.IDCardAvatar = field.NewInt32(table, "id_card_avatar")
	u.Balans = field.NewFloat64(table, "balans")
	u.FreezeBalans = field.NewFloat64(table, "freeze_balans")
	u.IDEntity = field.NewString(table, "id_entity")
	u.OmEnable = field.NewString(table, "om_enable")
	u.IsSteer = field.NewString(table, "is_steer")
	u.IsProcedure = field.NewString(table, "is_procedure")
	u.IsLogin = field.NewString(table, "is_login")
	u.CreateTime = field.NewTime(table, "create_time")
	u.UpdateTime = field.NewTime(table, "update_time")

	u.fillFieldMap()

	return u
}

func (u *userTbl) WithContext(ctx context.Context) IUserTblDo { return u.userTblDo.WithContext(ctx) }

func (u userTbl) TableName() string { return u.userTblDo.TableName() }

func (u userTbl) Alias() string { return u.userTblDo.Alias() }

func (u userTbl) Columns(cols ...field.Expr) gen.Columns { return u.userTblDo.Columns(cols...) }

func (u *userTbl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userTbl) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 24)
	u.fieldMap["openid"] = u.Openid
	u.fieldMap["omid"] = u.Omid
	u.fieldMap["yiparl_openid"] = u.YiparlOpenid
	u.fieldMap["nick_name"] = u.NickName
	u.fieldMap["province"] = u.Province
	u.fieldMap["city"] = u.City
	u.fieldMap["phone"] = u.Phone
	u.fieldMap["integral"] = u.Integral
	u.fieldMap["free_time"] = u.FreeTime
	u.fieldMap["plate_num"] = u.PlateNum
	u.fieldMap["id_number"] = u.IDNumber
	u.fieldMap["name"] = u.Name
	u.fieldMap["avatar"] = u.Avatar
	u.fieldMap["id_card_emblem"] = u.IDCardEmblem
	u.fieldMap["id_card_avatar"] = u.IDCardAvatar
	u.fieldMap["balans"] = u.Balans
	u.fieldMap["freeze_balans"] = u.FreezeBalans
	u.fieldMap["id_entity"] = u.IDEntity
	u.fieldMap["om_enable"] = u.OmEnable
	u.fieldMap["is_steer"] = u.IsSteer
	u.fieldMap["is_procedure"] = u.IsProcedure
	u.fieldMap["is_login"] = u.IsLogin
	u.fieldMap["create_time"] = u.CreateTime
	u.fieldMap["update_time"] = u.UpdateTime
}

func (u userTbl) clone(db *gorm.DB) userTbl {
	u.userTblDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userTbl) replaceDB(db *gorm.DB) userTbl {
	u.userTblDo.ReplaceDB(db)
	return u
}

type userTblDo struct{ gen.DO }

type IUserTblDo interface {
	gen.SubQuery
	Debug() IUserTblDo
	WithContext(ctx context.Context) IUserTblDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserTblDo
	WriteDB() IUserTblDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserTblDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserTblDo
	Not(conds ...gen.Condition) IUserTblDo
	Or(conds ...gen.Condition) IUserTblDo
	Select(conds ...field.Expr) IUserTblDo
	Where(conds ...gen.Condition) IUserTblDo
	Order(conds ...field.Expr) IUserTblDo
	Distinct(cols ...field.Expr) IUserTblDo
	Omit(cols ...field.Expr) IUserTblDo
	Join(table schema.Tabler, on ...field.Expr) IUserTblDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserTblDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserTblDo
	Group(cols ...field.Expr) IUserTblDo
	Having(conds ...gen.Condition) IUserTblDo
	Limit(limit int) IUserTblDo
	Offset(offset int) IUserTblDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserTblDo
	Unscoped() IUserTblDo
	Create(values ...*model.UserTbl) error
	CreateInBatches(values []*model.UserTbl, batchSize int) error
	Save(values ...*model.UserTbl) error
	First() (*model.UserTbl, error)
	Take() (*model.UserTbl, error)
	Last() (*model.UserTbl, error)
	Find() ([]*model.UserTbl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserTbl, err error)
	FindInBatches(result *[]*model.UserTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserTbl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserTblDo
	Assign(attrs ...field.AssignExpr) IUserTblDo
	Joins(fields ...field.RelationField) IUserTblDo
	Preload(fields ...field.RelationField) IUserTblDo
	FirstOrInit() (*model.UserTbl, error)
	FirstOrCreate() (*model.UserTbl, error)
	FindByPage(offset int, limit int) (result []*model.UserTbl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserTblDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userTblDo) Debug() IUserTblDo {
	return u.withDO(u.DO.Debug())
}

func (u userTblDo) WithContext(ctx context.Context) IUserTblDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userTblDo) ReadDB() IUserTblDo {
	return u.Clauses(dbresolver.Read)
}

func (u userTblDo) WriteDB() IUserTblDo {
	return u.Clauses(dbresolver.Write)
}

func (u userTblDo) Session(config *gorm.Session) IUserTblDo {
	return u.withDO(u.DO.Session(config))
}

func (u userTblDo) Clauses(conds ...clause.Expression) IUserTblDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userTblDo) Returning(value interface{}, columns ...string) IUserTblDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userTblDo) Not(conds ...gen.Condition) IUserTblDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userTblDo) Or(conds ...gen.Condition) IUserTblDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userTblDo) Select(conds ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userTblDo) Where(conds ...gen.Condition) IUserTblDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userTblDo) Order(conds ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userTblDo) Distinct(cols ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userTblDo) Omit(cols ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userTblDo) Join(table schema.Tabler, on ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userTblDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userTblDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userTblDo) Group(cols ...field.Expr) IUserTblDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userTblDo) Having(conds ...gen.Condition) IUserTblDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userTblDo) Limit(limit int) IUserTblDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userTblDo) Offset(offset int) IUserTblDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userTblDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserTblDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userTblDo) Unscoped() IUserTblDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userTblDo) Create(values ...*model.UserTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userTblDo) CreateInBatches(values []*model.UserTbl, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userTblDo) Save(values ...*model.UserTbl) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userTblDo) First() (*model.UserTbl, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserTbl), nil
	}
}

func (u userTblDo) Take() (*model.UserTbl, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserTbl), nil
	}
}

func (u userTblDo) Last() (*model.UserTbl, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserTbl), nil
	}
}

func (u userTblDo) Find() ([]*model.UserTbl, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserTbl), err
}

func (u userTblDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserTbl, err error) {
	buf := make([]*model.UserTbl, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userTblDo) FindInBatches(result *[]*model.UserTbl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userTblDo) Attrs(attrs ...field.AssignExpr) IUserTblDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userTblDo) Assign(attrs ...field.AssignExpr) IUserTblDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userTblDo) Joins(fields ...field.RelationField) IUserTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userTblDo) Preload(fields ...field.RelationField) IUserTblDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userTblDo) FirstOrInit() (*model.UserTbl, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserTbl), nil
	}
}

func (u userTblDo) FirstOrCreate() (*model.UserTbl, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserTbl), nil
	}
}

func (u userTblDo) FindByPage(offset int, limit int) (result []*model.UserTbl, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userTblDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userTblDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userTblDo) Delete(models ...*model.UserTbl) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userTblDo) withDO(do gen.Dao) *userTblDo {
	u.DO = *do.(*gen.DO)
	return u
}
